### ISSUE TITLE
Hard-coded binary installation path?

### ISSUE THREAD

**Issue by mjpost** [marian-nmt/marian#100]
Line 7 of the top-level `CMakeLists.txt` is:

    set(CMAKE_BINARY_DIR ${CMAKE_SOURCE_DIR}/build)

This means that if you are using a different build directory (perhaps for debugging, or for alternate architectures), your binaries and shared libs are still going to get installed in `build`. It seems to me this should be

    set(CMAKE_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR})

so that if e.g., you are building in `build.test` everything will be installed there. Any objections to this change?

**Comment by hieuhoang** [comment]
go for it
