### ISSUE TITLE
I can't download the artificially created data (514M) - Broken link

### ISSUE THREAD

**Issue by luisvp** [marian-nmt/marian#101]
Hi, it seems to me that there is a broken link in https://github.com/marian-nmt/marian/wiki/AmuNMT-for-Automatic-Post-Editing
I can't download the artificially created data.

**Comment by emjotde** [comment]
@snukky odkrykwa is down?

**Comment by snukky** [comment]
@emjotde No, both links work fine. Maybe it was a temporal down of the server.

**Comment by emjotde** [comment]
Seems to be fixed.
