### ISSUE TITLE
s2s usage issues

### ISSUE THREAD

**Issue by phikoehn** [marian-nmt/marian#106]
(1) s2s simply ignores input that is longer than 1000 words. not sure what the right behavior ios but currently it can happen that I want to translate a batch of sentences and the number of output sentences is smaller than the number of input sentences.

(2) how hard it is to get s2s to flush on input... the idea is to use s2s on demand - pipe in one sentence, get translation back as soon as possible... wait... pipe in another sentence, get translation back, etc. Amun allows this with the --wipo option, which circumvents  the thread-pool, is the same required here, or is there another work-around?

(3) there is no CPU version on s2s, and there never will be. right?

**Comment by emjotde** [comment]
ad 1) there is a parameter --max-length N that you can change. Let me know if there are still problems with that. Also, what are you doing with sentences >1000 ? :)

ad 2) It is the same threadpool I believe. In the worst case, you can just hack into this. Ideally this should be configurable in threadpool itself. I will take a look at that soon. 

ad 3) I hope there will be one. Currently there are several ways that could be happening. We either get one from Intel (@kpu, @XapaJIaMnu ?) or we will in the end have configurable backends. I would then want to have a CPU backend. Might however take a while.

**Comment by phikoehn** [comment]
Hi,

I'll take a stab at coding a piped version of the deciding loop over the
next days.

-phi

**Comment by phikoehn** [comment]
It looks like (2) is now handled by the server command.
