### ISSUE TITLE
Python library for s2s

### ISSUE THREAD

**Issue by beichao1314** [marian-nmt/marian#108]
Hello，
I'm try decoding s2s model with python library, but I get the exception:
`Error: /home/beichao/train/enzh_7k/marian/marian/src/amun/common/config.cpp:91 in void amunmt::Validate(const YAML::Node&) threw amunmt::util::Exception because !config["scorers"] || config["scorers"].size() == 0'.`
Dose the python library support the s2s model?
Thanks!

**Comment by hieuhoang** [comment]
I dont believe s2s has been packaged into a library that can be called by
python yet

Hieu Hoang
Sent while bumping into things

**Comment by beichao1314** [comment]
Thanks for your reply. @hieuhoang 
I mean compile python bindings and import it as python library like this:
`import libamunmt as nmt`
Does it only support the type of amu?

**Comment by hieuhoang** [comment]
correct, there is no equivalent libs2s

**Comment by beichao1314** [comment]
Is there any plan to add it?

**Comment by snukky** [comment]
There is still one issue with the python s2s bindings (an exception when a python script is closing), but it works and it's available in `marian-dev`.

You can compile it with `make -j pymarian`.
An example is in [/scripts/python](https://github.com/marian-nmt/marian-dev/tree/master/scripts/python).

For web socket server, there is `s2s_server`.

**Comment by beichao1314** [comment]
Thanks for all your excellent work!
But when compile `marian-dev` with gcc 4.9 on Ubuntu 14.04, I got the error in [make.txt](https://github.com/marian-nmt/marian/files/1241505/make.txt). And then, I update the gcc to 5.4, it works well.

**Comment by beichao1314** [comment]
It‘s OK with gcc 5.4, and I will close the issue. Thanks for all.
