### ISSUE TITLE
Training Examples small

### ISSUE THREAD

**Issue by roblim1** [marian-nmt/marian#110]
Are there other examples for Marian training for single GPU runs that do not take ~24 hours and also scores well?  Currently looking at improving single GPU runs, but would like an example that takes shorter duration and is somewhat representative of the current training examples (e.g. past year's competition winners).

**Comment by emjotde** [comment]
Not quite sure I understand. You want an example that converges in a couple of hours on a single GPU, but has WMT-grade quality? 

Don't we all? :)
