### ISSUE TITLE
Clipping weights

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian#111]
I'm trying to replicate (Devlin 2017) results for half precision, coming up with overflows in gElementwiseOps(). Devlin get round this by clipping weights and activations. Is there any functionality in the marian training to clip weights?

**Comment by emjotde** [comment]
Nope. You are doing this in amun?

**Comment by hieuhoang** [comment]
yep

**Comment by emjotde** [comment]
Do you have the right hardware for that?

W dniu 20.09.2017 o 20:35, Hieu Hoang pisze:

**Comment by hieuhoang** [comment]
no but i can get them

**Comment by kpu** [comment]
You're welcome.

**Comment by emjotde** [comment]
Add some nice comments. Will be cool to add it to Marian later.

**Comment by hieuhoang** [comment]
yep, if its faster. For now i've clipped the weights during loading in amun which works but gives some weird results

 There's 2 fp16 types - 
   1. half (replacement for float)
   2. half2 (2 half types in 32 bits)
It may be that I actually have to do some major rewriting of code to use half2 to get it to run siginificantly faster

**Comment by emjotde** [comment]
Since 80% time is spent in GEMM just doing a conversion to/from fp16 around GEMMs will give you most of the speed benefit, I guess?

**Comment by hieuhoang** [comment]
fingers crossed
