### ISSUE TITLE
Best Translation is empty when it ends in "@@"

### ISSUE THREAD

**Issue by domjehle** [marian-nmt/marian#115]
Hi,
With the Amun decoder we found that the translation returned is empty when it ends in "@@" before de-bpe is applied. This was observed for segments that have a one-word translation.
When this happens, no result is given, the entire translation string is empty. However, nbest shows entries for the next best translations.
We would like to know if this is expected behavior or rather a bug?

SAN Juan
Search took 0.572s
Best translation 0 : 0 |||  ||| F0= -2.217 ||| -1.108
0 ||| Сан-Хуан-а ||| F0= -4.123 ||| -1.374
0 ||| Сан-Хуан-П ||| F0= -4.814 ||| -1.605

(no-debpe=true)
SAN Juan
Search took 0.624s
Best translation 0 : 0 ||| Сан-Хуан-@@ ||| F0= -2.217 ||| -1.108
0 ||| Сан-Хуан-@@ а ||| F0= -4.123 ||| -1.374
0 ||| Сан-Хуан-@@ П ||| F0= -4.814 ||| -1.605

Thanks,
Dominic

**Comment by hieuhoang** [comment]
sounds like a bug

**Comment by emjotde** [comment]
@tomekd Can you take a look at this?

**Comment by tomekd** [comment]
Hi @domjehle

I pushed the fix to ``fix-debpe`` branch. Can you check whether it resolves your problem?

**Comment by mkaeshammer** [comment]
I noticed the same issue, and it works for me now with the fix in the branch.

**Comment by tomekd** [comment]
Thanks, @mkaeshammer . The fix is in the master branch now. Closing
