### ISSUE TITLE
Best deep?

### ISSUE THREAD

**Issue by mjpost** [marian-nmt/marian#121]
Hi — Can you list exactly what `--best-deep` does? I assume it is a shortcut for a number of parameter settings, but it actually seems to have no effect.

**Comment by tomekd** [comment]
Take a look at https://github.com/marian-nmt/marian-dev/blob/18aca9170051d86ca6119c9ff04c41915a304bab/src/common/config_parser.cpp#L695

In other words, if on, it overwrites the settings with those values, e.g. setting layer-normalization, tie-embeddings, and so on.

**Comment by emjotde** [comment]
Concerning no effect: you should see a considerably larger model size during allocation and the mentioned option changes in the log.

**Comment by mjpost** [comment]
Ah, that explains my problem: the code is in marian-dev. However, the command-line switch is present in github.com/marian-nmt/marian, where it indeed doesn't seem to do anything.

**Comment by emjotde** [comment]
No, should work there too. I see the code snippet when I check.

**Comment by mjpost** [comment]
If I use those individual settings in Marian, is it the same as Marian-dev? Or do I need to start over with Marian-dev?

**Comment by emjotde** [comment]
That should work. @phikoehn used this successfully to reproduce the Edinburgh paper for WMT2017. The `--best-deep` option works with `marian`, too, just checked. If you use `marian-dev`, we renamed `--dynamic-batching` to `--mini-batch-fit` in order to avoid confusion.

**Comment by mjpost** [comment]
You're right of course, I see my mistake. Thanks.
