### ISSUE TITLE
Nematus style soft alignments

### ISSUE THREAD

**Issue by M4t1ss** [marian-nmt/marian#122]
Hi! 
I would like to reproduce the soft alignment format that is used in Nematus:

> sentence id ||| target words ||| score ||| source words ||| number of source words ||| number of target words
> soft alignment matrix
> newline

I kind-of got the source sentence, but I'm guessing that `hypothesis->GetCost()` that I use as the score is not really correct 😆 . Also, It looks like the soft alignment matrix has an `<EOS>` value for the source sentence but not for the target one. I just print 0s now instead, but I'd like to have some actual values there 😄 
https://github.com/marian-nmt/marian/compare/master...M4t1ss:master

Is there a way to get a score value just like in Nematus and the last row of soft alignments?

**Comment by tomekd** [comment]
Hi,

Let's go through the questions.
 * Lack of  ``EOS`` symbol on the target side. In ``GetNematusAlignmentString`` change:
 ``` c++
HypothesisPtr last = hypothesis->GetPrevHyp();
```
to
``` c++
HypothesisPtr last = hypothesis;
```
 * Cost.  I don't know why ``hypothesis->GetCost()`` doesn't help. Is it a huge difference? Maybe normalization?

**Comment by M4t1ss** [comment]
Thanks! Got the EOS alignment 🔢 
About the cost and score - I wasn't really planning on using it, but I wanted to get exactly the same output using the same model as I get with Nematus. If there is no quick & easy way to get that, then I'll keep it as it is with the cost.

But there is a difference. Some examples when translating five sentences with the same model:
- Nematus
  - 0.161136252539
  - 0.302387787746
  - 0.359853895087
  - 0.57152001063
  - 0.644340066349

- Amun
  - -1.12795
  - -3.93105
  - -6.83722
  - -10.2874
  - -10.9538

**Comment by emjotde** [comment]
Are these our final costs? Can you post the commands you used for nematus and amun and the full n-best lists?

**Comment by tomekd** [comment]
You normalize scores in Nematus but not in amun:
 * -1.12795 / 0.161136252539 = -6.99999
 * -3.93105 / 0.302387787746 = -13
 * -6.83722 / 0.359853895087 = -18.9999
 * -10.2874 / 0.57152001063 = -18
 * -10.9538 / 0.644340066349 = -17

Those numbers cannot be miningless.

**Comment by emjotde** [comment]
Good catch. Most likely sentence length, that's why I was asking for the n-best lists and the commands. I suppose using amun with `-n` should give the same scores.

**Comment by snukky** [comment]
Be also aware that for deep models in amun (CPU only) the difference may be up to one or two decimal places. For shallow models the scores are nearly identical.

**Comment by M4t1ss** [comment]
Awesome! Thanks a lot! After normalization the scores match 👍
Is it OK to merge this #124 ?

**Comment by tomekd** [comment]
@M4t1ss : Many thanks!
