### ISSUE TITLE
Handling number, date, email and url?

### ISSUE THREAD

**Issue by lkfo415579** [marian-nmt/marian#123]
Hi developers, is there any support or recommand approach of handling _number, date, email_ and _url_?
And does marian have a function like moses's _place holder_? it means replace number with _XML tag_, while inputing it into decoder it won't be translated.

**Comment by emjotde** [comment]
Hi,
the issue with NMT is that doing Moses-style XML tags is a technically really hard problem. There is no easy way to control the output and being able to do so require quite significant modification of the beam-search algorithms. It's pretty messy. 

I think the easiest way might be to prepare your training corpus in such a way that you insert placeholders in your training data on both sides and then hope that they are correctly inserted and generated by the translator. For numbers for instance my recommendation would be to try something like <NUM1> with increasing counter. It might make sense to split the symbols artifically as BPE units "<NUM@@ 1>". You should have matching placeholders on both side. Getting them right later would be your responsibility.

**Comment by lkfo415579** [comment]
@emjotde thanks for your suggestion. do you have your own placeholders replace program? may i have a look just for reference.

**Comment by emjotde** [comment]
Sorry no, I didn't do much actual work on building systems recently, more low-level stuff. Maybe someone else can share?

Anyway, if I were to do something like that I would start out with old-school word alignment. For numbers it might be easy as they should usually match on both sides, but other stuff will require word alignment to identify matching pairs in parallel data.

**Comment by emjotde** [comment]
Ah, by the way, are you using BPE subwords? While building our systems at WIPO we found that they are actually pretty good for copying stuff over. Therefor we did not invest time into building a placeholder system. And at WIPO we were translating patents, so lots of numbers etc, but also lots of data, that might be the difference.

**Comment by alvations** [comment]
BPE does solve some problems but for emails and http, I had quite a headache when it gets too smart and translate URLs and email addresses... lolz

**Comment by emjotde** [comment]
It worked fairly well for us as we had for some language pairs hundreds of millions of sentences in-domain. For others however it would start rounding numbers :) After all 5.9 is pretty close to 6. So let's go with 6. Not that great for patents.

**Comment by emjotde** [comment]
Ah, what I wanted to try for things like e-mails etc. I wonder if surrounding them by special tags would help:
<keep> email@@ @@@ email.@@ com </keep>. Even just on the source side. That should be a pretty strong signal for the network.

**Comment by alvations** [comment]
Tried something similar `<keep>...</keep>` but in a more brutish manner with `__email@email.com__` and replace things between `__` but if there's more than one of those in the sentence and the order in target should be different than the source, then it will need some rules after translation.

We had a few of those but they're obvious so we knew they're wrong but yeah we still get points for unigram in BLEU ;P

**Comment by emjotde** [comment]
Not quite the same, I think? If I understand correctly, you want to prevent the network from processing the address, while with the tags I would like the network to learn how to process them. Without any replacement afterwards.

**Comment by alvations** [comment]
Ah yes not the same. You want the network to learn to keep words. While I let it do whatever it wants and override it with replacements after.

**Comment by CatarinaSilva** [comment]
@alvations I am working with that and use some replacement tags (imagine something like `___NUM___ `  for example) that don't appear normally in the vocabulary. Actually subword-nmt has a feature to keep special tags like this, you pass them as a list  in the field **glossaries** so it does not try to segment them. In the models I have been training, the model learns to keep these words pretty well. I do a simple replacement before the preprocessing with regular expressions.

**Comment by lkfo415579** [comment]
@CatarinaSilva thanks, after decoder decoded a sentence, if the result cotains two or more `__NUM__`, do you use NMT alignment information (the matrix ones) to implement the replacement?

**Comment by CatarinaSilva** [comment]
@lkfo415579 yes since I am using a standard bidirectional RNN with attention, I use the attention as a basic way to put everything back. There are some corner cases where it fails, but mostly it works pretty well.
