### ISSUE TITLE
May i use the marian(type s2s) to decode with nematus deep model?

### ISSUE THREAD

**Issue by 520jefferson** [marian-nmt/marian#128]
I train with nematus and with the configuration as follows:
--layer_normalisation\
--tie_decoder_embeddings \
--enc_depth 4 \
--dec_depth 4 \
--dec_deep_context \
--enc_recurrence_transition_depth 2 \
--dec_base_recurrence_transition_depth 4 \
--dec_high_recurrence_transition_depth 2 \

I try to decode with marian and there are some logs：
[2017-11-03 12:55:07] No model settings found in model file

then i put marian's config 512-1024-en_ch.npz.yml into nematus's model folder, and the same log appear.

Does It work using marian(type s2s) to decode with nematus's deep model?

**Comment by snukky** [comment]
You should be able to use `marian-decoder` with a deep model trained with Nematus, but you have to manually specify model parameters as they are not included in the model .npz file. Use the newest version of marian from `marian-dev` repo. 

A mapping between Nematus and Marian model parameters is [on Wiki](https://github.com/marian-nmt/marian-dev/wiki/Mapping-Nematus-Model-Parameters-to-S2S).
You may also use `script/contrib/inject_s2s_config.py` script to add model parameters to .npz file (make a copy of your model before doing so!).

For an example usage take a look at our regression tests, e.g.:
* https://github.com/marian-nmt/marian-regression-tests/blob/master/tests/decoder/wmt17/test_ende.sh
* https://github.com/marian-nmt/marian-regression-tests/blob/master/models/wmt17_systems/marian.en-de.yml

**Comment by 520jefferson** [comment]
I get another question ,how can i decode with marian using model ensemble 
I found this  in run-me.sh 
# create configuration file for model ensemble
../../build/amun -m en-de/model-ens?.npz -s en-de/vocab.en.json -t en-de/vocab.de.json \
    --mini-batch 1 --maxi-batch 1 -d $GPUS --gpu-threads 1 -b 12 -n --bpe en-de/ende.bpe \
    --relative-paths --dump-config > ensemble.yml
 # translate
 ../../build/amun -c ensemble.yml --gpu-threads 1 | \

but i am confused,whether i should  just put the  ensemble model  into en-de folder ? could i write the concrete model  ,if 2 model ensemble i write the  specify 2 models, if 3 model ensemble i specify 3 models ?

**Comment by 520jefferson** [comment]
@snukky 
i translate nematus model as your told me
first i change a nematus model with scripts/contrib/inject_s2s_config.py 
the i translate with the new model like the example you provide ,then i g et this :

[2017-11-05 17:53:12] --type nematus does not currently support multiple encoder layers, use --type s2s
Aborted from marian::Nematus::Nematus(marian::Ptr<marian::Options>) [with Args = {}; marian::Ptr<marian::Options> = std::shared_ptr<marian::Options>] in marian-dev/src/models/nematus.h: 19
Aborted (core dumped)

**Comment by emjotde** [comment]
How did that go in the end?
