### ISSUE TITLE
need usage of scripts (optimize.pl, wrapper.pl)

### ISSUE THREAD

**Issue by lkfo415579** [marian-nmt/marian#129]
I tried **optimize.pl** program, it seems to be a mert tuning program but it doesn't work. (while inputing weight to decode n-best list, it occurs an error.) And may i ask what is the purpose of **wrapper.pl**?

**Comment by emjotde** [comment]
Oh my, these are highly experimental and likely outdated. What are you trying to achieve?

**Comment by lkfo415579** [comment]
ha ha, i was trying to look at you guys's scripts in order to achieve better performance of NMT. BTW would you tell me how to tune the NMT model by giving a dev-set? (optimize.pl)

**Comment by emjotde** [comment]
MERT won't do anything for you with a single model. Even for ensembles of similar models it very unlikely you will see improvement. I only used this to find out weight for ensembles with different input languages. And later I was actually better at finding those weights by hand on a dev set.
