### ISSUE TITLE
Error:  parallel_for failed: PTX JIT compiler library not found

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian#131]
Anyone getting this error with CUDA 9/NVIDIA 984? It's happening on some GPUs (940MX) but not others (GTX 1080)

**Comment by tomekd** [comment]
Hi, nope. But i found that people get the same problem in theano, so I suppose it's not a problem with marian.

**Comment by hieuhoang** [comment]
you're right, doesn't seem to affect marian or s2s. I'll dig around why

**Comment by hieuhoang** [comment]
found the problem and pushed the solution to master - don't use thrust vectors.

For related reasons, needed to change the compile flag. https://github.com/marian-nmt/marian/commit/89ce664765575d816cb3d885def125fe0ea57ee2

Anyone know how to update the marian submodule to use thes flags? Or disentangle amun and marian's NVCC flags? For the moment, i've prevented marian compilation

**Comment by hieuhoang** [comment]
all done
