### ISSUE TITLE
--tie-embeddings-all support for amun

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#135]
Amun can already tie target embeddings and the output layer. If I am not wrong this is done by looking at the model file and determining which matrices are present. Marian can also tie source embeddings with target embeddings (--tie-embeddings-src) and do a complete three-way tying (--tie-embeddings-all). Would be good to support that too in amun. 

If I am not wrong, this was work by @tomekd

**Comment by tomekd** [comment]
Yes, you're right. It's already supported, both on CPU/GPU backend.

If there is no src emb ``Wemb``, take the trg one: ``Wemb_dec``.

**Comment by emjotde** [comment]
Is this how Nematus does it? Cos in Marian I have been doing it the opposite way, use `Wemb` everywhere.

**Comment by tomekd** [comment]
Added in ``tied-amun`` branch. I need a model for testing now Have you already got such model? Or I need to train a new one?

**Comment by emjotde** [comment]
For clarification, I would like to know what matrix names are use for Nematus for all possible options. That way I will be able to adjust Marian.

**Comment by emjotde** [comment]
@tomekd Looks good, thanks.
