### ISSUE TITLE
amun segfaults with return-alignment

### ISSUE THREAD

**Issue by oraveczcsaba** [marian-nmt/marian#136]
Just tried the latest version (0c1297b) and it seems to work until I want it to return the alignment (scores). A previous version (12897cc) does not have this problem.

**Comment by hieuhoang** [comment]
What is the exact command you rant? If possible, could you please make your model available for download

**Comment by oraveczcsaba** [comment]
this one works:
`amun -m model.npz -s ./clean-bpe.en.json -t ./clean-bpe.de.json`
...
the Commission accepted the decision .
Search took 0.034s
Best translation 1 : die Kommission akzeptierte die Entscheidung .
die Kommission akzeptierte die Entscheidung .

----
this fails:
`amun -m model.npz -s ./clean-bpe.en.json -t ./clean-bpe.de.json --return-alignment`
...
the Commission accepted the decision .
Search took 0.036s
Segmentation fault

I put the resources here:
http://budling.nytud.hu/~oravecz/download/endesample.zip

**Comment by oraveczcsaba** [comment]
thanks. it would be nice to have this option (returning alignment) for marian-decoder, too.

**Comment by emjotde** [comment]
Agreed. I have filed an issue to remind myself, no guarantee though how quickly it will be added. I have a couple of later projects in Marian planned. Maybe someone else want to give it a try. 

https://github.com/marian-nmt/marian-dev/issues/145

**Comment by lkfo415579** [comment]
Another amun problem:
About the `marian/src/amun/python/amunmt.cpp`, when you use command like `python test.py "-c marian_python/MARIAN_SETTING --mini-batch 5 --maxi-batch 100 " < 4.en.bpe > 4.output` it will occur an error.
Solve:
I discovered when you set **--mini-batch** greater than **1** , amunmt.cpp's maxiBatchCopy has a bug.
change `maxiBatchCopy->push_back(miniBatch->at(0));` to 
`    for (size_t i = 0; i < miniBatch->size(); ++i)
          maxiBatchCopy->push_back(miniBatch->at(i));` the problem will be solved.

**Comment by hieuhoang** [comment]
this is not related the the alignment problem, create another issue if you want. I'm closing this issue as the alignment problem is solved imo
