### ISSUE TITLE
Build error from master

### ISSUE THREAD

**Issue by vince62s** [marian-nmt/marian#142]
at make -j
Thanks !

[ 82%] Building NVCC (Device) object src/amun/CMakeFiles/amun.dir/gpu/amun_generated_types-gpu.cu.o
[ 82%] Building CXX object src/amun/CMakeFiles/amun.dir/common/decoder_main.cpp.o
[ 83%] Linking CXX executable ../../amun
[ 83%] Built target amun
/home/moses/marian/src/marian/src/training/graph_group_async.h: In lambda function:
/home/moses/marian/src/marian/src/training/graph_group_async.h:61:6: error: ‘void marian::AsyncGraphGroup::updateMovingAverage(marian::Tensor, marian::Tensor, size_t)’ is protected
   void updateMovingAverage(Tensor paramsAvg, Tensor params, size_t batches);
      ^
/home/moses/marian/src/marian/src/training/graph_group_async_drop.cu:117:112: error: within this context
             AsyncGraphGroup::updateMovingAverage(
                                                                                                                ^
CMake Error at marian_generated_graph_group_async_drop.cu.o.cmake:262 (message):
  Error generating file
  /home/moses/marian/build/src/marian/src/CMakeFiles/marian.dir/training/./marian_generated_graph_group_async_drop.cu.o

make[2]: *** [src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_async_drop.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/marian/src/CMakeFiles/marian.dir/all] Error 2
make: *** [all] Error 2

**Comment by hieuhoang** [comment]
what version of CUDA/gcc/OS are you using? Are you using marian for training or only amun for translating?

**Comment by emjotde** [comment]
Hi,
Eh, we haven't tested on older set ups in a while. Any chance you can update the compiler to 5.2 or higher? 4.9 is apparently quite borderline and seems to be hit and miss.

**Comment by vince62s** [comment]
ah, was looking for 6, is there any ppa for 5.2 ? I'll look for it

**Comment by vince62s** [comment]
ok guys, with gcc 5.4.1 compiled fine. might be good to update the requirements from the home.
cheers.
