### ISSUE TITLE
sacrebleu repo has changed

### ISSUE THREAD

**Issue by vince62s** [marian-nmt/marian#144]
this breaks the run-me.sh

**Comment by emjotde** [comment]
@snukky 
I think that can be fixed by explicitly checking out master.

**Comment by snukky** [comment]
I think it has been already fixed: https://github.com/marian-nmt/marian-examples/commit/301c42debbea493cb146484c250e0ab2c0ca556d

Just update the submodule and/or remove `tools/sacreBLEU` and `make all` again.

**Comment by vince62s** [comment]
I mean it has moved here: https://github.com/awslabs/sockeye/tree/master/contrib/sacrebleu

**Comment by snukky** [comment]
The master branch in `mjpost/sacreBLEU` seems to contain a newer version of the script. It makes no sense to clone sockeye, I would rather prefer to install it via pip3 as recommended.

**Comment by vince62s** [comment]
yes sorry I must have done something wrong while checking out on a previous hash.
