### ISSUE TITLE
Can't download data and model files

### ISSUE THREAD

**Issue by snailcoder** [marian-nmt/marian#148]
Hi, I'm trying to download the data and model files of Winning system of the WMT 2016 APE shared task, but neither data nor model can be downloaded through these links:

 http://odkrywka.wmi.amu.edu.pl/static/data/ape/data.tgz
http://odkrywka.wmi.amu.edu.pl/static/data/ape/system.tgz

Are there new available links?

**Comment by snukky** [comment]
Thanks! I've moved both files here:

http://data.statmt.org/romang/ape-wmt16/

**Comment by emjotde** [comment]
Can you update the links everywhere, for instance here:
https://github.com/marian-nmt/marian/wiki/AmuNMT-for-Automatic-Post-Editing

**Comment by snukky** [comment]
I updated the links on Wiki and on the webpage with examples.
