### ISSUE TITLE
Boost Not Found During Compilation

### ISSUE THREAD

**Issue by elmines** [marian-nmt/marian#149]
I am attempting to compile Marian on a CentOS Linux server with the following modules loaded:

Currently Loaded Modules:
  1) **cmake/3.10.1**   2) **cuda/8.0.44**   3) ofed/4.1-1.0.2.0   4) openmpi/2.1.1-gnu-pmi2   5) **boost/1.58.0**   6) autogen/5.11.1   7) **gcc/5.4.0**

I understand Marian has these following dependencies:
CMake 3.5.1
GCC/G++ 5.4
Boost 1.58
CUDA 8.0

Would my use of newer versions of CMake and Cuda be causing the issue? Here is the output when I run `cmake ..`

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /opt/asn/apps/gcc_5.4.0/bin/cc
-- Check for working C compiler: /opt/asn/apps/gcc_5.4.0/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/asn/apps/gcc_5.4.0/bin/c++
-- Check for working CXX compiler: /opt/asn/apps/gcc_5.4.0/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /opt/asn/apps/cuda_8.0.44 (found version "8.0")
-- Compiling with CUDA support
CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:75 (find_package)

-- Could NOT find Boost
CMake Error at CMakeLists.txt:93 (message):
  Cannot find Boost libraries.  Terminating.

-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7")
-- Found Python
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Found Git: /usr/bin/git (found version "1.8.3.1")
-- Git version: d3fb526
-- Could NOT find SparseHash (missing: SPARSEHASH_INCLUDE_DIR)
-- Project name: marian
-- Project version: v1.0.0+d3fb526
-- Found CUDA: /opt/asn/apps/cuda_8.0.44 (found suitable version "8.0", minimum required is "8.0")
-- Not Found Tcmalloc
CMake Warning at src/marian/CMakeLists.txt:57 (message):
  Cannot find TCMalloc library.  Continuing.

-- Found Python
-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k")
-- Found OpenSSL
CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

CMake Warning at /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:567 (message):
  Imported targets and dependency information not available for Boost version
  (all versions older than 1.33)
Call Stack (most recent call first):
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:907 (_Boost_COMPONENT_DEPENDENCIES)
  /mnt/homeapps/apps/uv/apps/cmake_3.10.1/share/cmake-3.10/Modules/FindBoost.cmake:1542 (_Boost_MISSING_DEPENDENCIES)
  src/marian/CMakeLists.txt:90 (find_package)

-- Could NOT find Boost
CMake Error at src/marian/CMakeLists.txt:95 (message):
  Cannot find Boost libraries.  Terminating.

-- Found Doxygen: /usr/bin/doxygen (found version "1.8.5") found components:  doxygen dot
-- Configuring incomplete, errors occurred!
See also "/home/ualelm/marian/build/CMakeFiles/CMakeOutput.log".
See also "/home/ualelm/marian/build/CMakeFiles/CMakeError.log".

**Comment by emjotde** [comment]
Where are your boost libraries located?

**Comment by elmines** [comment]
The libraries are found in /opt/asn/apps/boost_1.58.0/lib. I have verified that this directory has been added to both my LD_LIBRARY_PATH and LIBRARY_PATH environment variables.

**Comment by emjotde** [comment]
I believe CMake does not check there. Try
``
cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_DIR=/opt/asn/apps/boost_1.58.0
``

**Comment by elmines** [comment]
At the moment, the same error occurs even with those command line options. I am currently investigating FindBoost.cmake to find out why it says the Boost version is older than 1.33.

**Comment by elmines** [comment]
It appears I had to do something similar to what you suggested, but I had to use a different CMake variable:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/opt/asn/apps/boost_1.58.0`

With that command, the compilation worked flawlessly. Thank you for your help; I do greatly appreciate it. Since the issue is resolved, I will close the thread.

**Comment by emjotde** [comment]
For reference:
https://github.com/marian-nmt/marian-dev/wiki/Compiling-Marian-with-custom-Boost

**Comment by elmines** [comment]
Thank you, and I apologize for not carefully looking through the Wiki in the first place.

**Comment by emjotde** [comment]
This wasn't direct at you actually. More as a reference for future searches.
