### ISSUE TITLE
Undefined reference errors in /decoder/amun_generated_encoder_decoder.cu

### ISSUE THREAD

**Issue by qiuyedyc** [marian-nmt/marian#151]
make
[  0%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/regex_yaml.cpp.o
[  0%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/nodebuilder.cpp.o
[  1%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/scanscalar.cpp.o
[  1%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/scanner.cpp.o
[  2%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/parser.cpp.o
[  2%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/stream.cpp.o
[  2%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/convert.cpp.o
[  4%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/directives.cpp.o
[  4%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/singledocparser.cpp.o
[  5%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/memory.cpp.o
[  5%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/node.cpp.o
[  5%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/exp.cpp.o
[  7%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/emitter.cpp.o
[  7%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/emit.cpp.o
[  7%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/null.cpp.o
[  8%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/binary.cpp.o
[  8%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/emitfromevents.cpp.o
[ 10%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/scantoken.cpp.o
[ 10%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/emitterstate.cpp.o
[ 10%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/scantag.cpp.o
[ 11%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/simplekey.cpp.o
[ 11%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/nodeevents.cpp.o
[ 11%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/tag.cpp.o
[ 13%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/contrib/graphbuilderadapter.cpp.o
[ 13%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/contrib/graphbuilder.cpp.o
[ 14%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/node_data.cpp.o
[ 14%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/emitterutils.cpp.o
[ 14%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/parse.cpp.o
[ 16%] Building CXX object src/amun/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp-amun.dir/ostream_wrapper.cpp.o
[ 16%] Built target libyaml-cpp-amun
[ 17%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/git_version.cpp.o
[ 17%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/base_best_hyps.cpp.o
[ 17%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/base_matrix.cpp.o
[ 19%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/config.cpp.o
[ 19%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/exception.cpp.o
[ 20%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/filter.cpp.o
[ 20%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/god.cpp.o
[ 20%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/history.cpp.o
[ 22%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/histories.cpp.o
[ 22%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/hypothesis.cpp.o
[ 23%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/loader.cpp.o
[ 23%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/logging.cpp.o
[ 23%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/output_collector.cpp.o
[ 25%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/printer.cpp.o
[ 25%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/processor/bpe.cpp.o
[ 25%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/scorer.cpp.o
[ 26%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/search.cpp.o
[ 26%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/sentence.cpp.o
[ 28%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/sentences.cpp.o
[ 28%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/types.cpp.o
[ 28%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/utils.cpp.o
[ 29%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/vocab.cpp.o
[ 29%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/factor_vocab.cpp.o
[ 29%] Building CXX object src/amun/CMakeFiles/libcommon.dir/common/translation_task.cpp.o
[ 29%] Built target libcommon
[ 29%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/mblas/matrix.cpp.o
[ 29%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/mblas/phoenix_functions.cpp.o
[ 31%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/decoder/encoder_decoder.cpp.o
[ 31%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/decoder/encoder_decoder_state.cpp.o
[ 32%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/decoder/encoder_decoder_loader.cpp.o
[ 32%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/dl4mt/encoder.cpp.o
[ 32%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/dl4mt/gru.cpp.o
[ 34%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/dl4mt/model.cpp.o
[ 34%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/dl4mt/encoder_decoder.cpp.o
[ 34%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/nematus/encoder.cpp.o
[ 35%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/nematus/model.cpp.o
[ 35%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/nematus/gru.cpp.o
[ 37%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/nematus/transition.cpp.o
[ 37%] Building CXX object src/amun/CMakeFiles/cpumode.dir/cpu/nematus/encoder_decoder.cpp.o
[ 37%] Built target cpumode
[ 37%] Building CXX object src/amun/3rd_party/CMakeFiles/libcnpy.dir/cnpy/cnpy.cpp.o
[ 37%] Built target libcnpy
[ 37%] Building CXX object src/amun/CMakeFiles/amun.dir/common/decoder_main.cpp.o

▽
[ 38%] Linking CXX executable ../../amun
CMakeFiles/amun.dir/gpu/decoder/amun_generated_encoder_decoder.cu.o: In function `amunmt::GPU::EncoderDecoder::EncoderDecoder(amunmt::God const&, std::string const&, YAML::Node const&, unsigned long, amunmt::GPU::Weights const&)':
tmpxft_0000c3b3_00000000-4_encoder_decoder.compute_61.cudafe1.cpp:(.text+0x105b): undefined reference to `amunmt::Scorer::Scorer(amunmt::God const&, std::string const&, YAML::Node const&, unsigned long)'
CMakeFiles/amun.dir/gpu/decoder/amun_generated_encoder_decoder.cu.o: In function `amunmt::GPU::EncoderDecoder::~EncoderDecoder()':
tmpxft_0000c3b3_00000000-4_encoder_decoder.compute_61.cudafe1.cpp:(.text+0x25bb): undefined reference to `boost::timer::format(boost::timer::cpu_times const&, short, std::string const&)'
CMakeFiles/amun.dir/gpu/decoder/amun_generated_encoder_decoder.cu.o: In function `amunmt::GPU::mblas::TMatrix<float>::Debug(unsigned long) const':
tmpxft_0000c3b3_00000000-4_encoder_decoder.compute_61.cudafe1.cpp:(.text._ZNK6amunmt3GPU5mblas7TMatrixIfE5DebugEm[_ZNK6amunmt3GPU5mblas7TMatrixIfE5DebugEm]+0x3c): undefined reference to `amunmt::BaseMatrix::Debug(unsigned long) const'
CMakeFiles/amun.dir/gpu/decoder/amun_generated_encoder_decoder_loader.cu.o: In function `amunmt::GPU::EncoderDecoderLoader::Load(amunmt::God const&)':
tmpxft_0000c3bb_00000000-4_encoder_decoder_loader.compute_61.cudafe1.cpp:(.text+0x2c96): undefined reference to `YAML::detail::node_data::empty_scalar'
CMakeFiles/amun.dir/gpu/amun_generated_npz_converter.cu.o: In function `amunmt::GPU::NpzConverter::NpzConverter(std::string const&)':
tmpxft_0000c142_00000000-4_npz_converter.compute_61.cudafe1.cpp:(.text+0x3b): undefined reference to `cnpy::npz_load(std::string)'
CMakeFiles/amun.dir/common/amun_generated_loader_factory.cpp.o: In function `amunmt::LoaderFactory::CreateCPU(amunmt::God const&, std::string const&, YAML::Node const&)':
tmpxft_0000c096_00000000-4_loader_factory.compute_61.cudafe1.cpp:(.text+0xe64): undefined reference to `amunmt::CPU::EncoderDecoderLoader::EncoderDecoderLoader(std::string, YAML::Node const&)'
tmpxft_0000c096_00000000-4_loader_factory.compute_61.cudafe1.cpp:(.text+0xee9): undefined reference to `amunmt::CPU::EncoderDecoderLoader::EncoderDecoderLoader(std::string, YAML::Node const&)'
tmpxft_0000c096_00000000-4_loader_factory.compute_61.cudafe1.cpp:(.text+0xf50): undefined reference to `amunmt::CPU::EncoderDecoderLoader::EncoderDecoderLoader(std::string, YAML::Node const&)'
tmpxft_0000c096_00000000-4_loader_factory.compute_61.cudafe1.cpp:(.text+0xf96): undefined reference to `amunmt::CPU::EncoderDecoderLoader::EncoderDecoderLoader(std::string, YAML::Node const&)'
CMakeFiles/libcommon.dir/common/god.cpp.o: In function `amunmt::God::LoadScorers()':
god.cpp:(.text+0x4fe3): undefined reference to `amunmt::LoaderFactory::Create(amunmt::God const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, YAML::Node const&, amunmt::DeviceType)'
god.cpp:(.text+0x529e): undefined reference to `amunmt::LoaderFactory::Create(amunmt::God const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, YAML::Node const&, amunmt::DeviceType)'
collect2: error: ld returned 1 exit status
make[2]: *** [amun] Error 1
make[1]: *** [src/amun/CMakeFiles/amun.dir/all] Error 2
make: *** [all] Error 2

**Comment by tomekd** [comment]
Hi @qiuyedyc 
can you send your settings, e.g. GCC version, CUDA and linux distro?

**Comment by qiuyedyc** [comment]
On centos 7

$cmake -DCMAKE_CXX_COMPILER=/usr/local/bin/g++ ..
-- Found CUDA: /usr/local/cuda (found version "8.0")
-- Compiling with CUDA support
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   timer
--   iostreams
--   python
--   thread
--   chrono
--   regex
--   date_time
--   atomic
-- Found Python
-- Git version: d3fb526
-- Project name: marian
-- Project version: v1.0.0+d3fb526
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "8.0")
-- Found Tcmalloc: /usr/local/lib/libtcmalloc_minimal.so
-- Found Python
-- Found OpenSSL
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   timer
--   iostreams
--   filesystem
--   chrono
--   program_options
--   thread
--   python
--   regex
--   date_time
--   atomic
-- Configuring done
-- Generating done

**Comment by hieuhoang** [comment]
is this problem still occuring? I'll take a look at it if it is, otherwise please close the issue

**Comment by hieuhoang** [comment]
closing. re-open if you still have problems
