### ISSUE TITLE
Perform final validation when training finishes based on other criterion than early stopping

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#155]
@phikoehn noticed that final models do not get validated (see https://github.com/marian-nmt/marian/issues/154) if the stopping criterion is not based on validation, e.g. `--after-batches` or `--after-epochs`. This may fall between two validation steps, then this information is missing. 

So validation should be triggered when stopping criterions are matched.

**Comment by snukky** [comment]
Fixed with https://github.com/marian-nmt/marian-dev/commit/869e93436f4b1ab45442ba58ca3d9e21602caa44 and added regression tests.
