### ISSUE TITLE
learning-rate warm-up skipped for very first minibatch

### ISSUE THREAD

**Issue by frankseide** [marian-nmt/marian#156]
Hi Marcin, as we just discussed in person, the learning-rate warm-up has a minor bug.

The learning-rate warm-up currently is done in a post-update operation, with the consequence that the very first minibatch uses the original learning rate instead of the reduced one. The log, however, already reports the reduced learning rate. Maybe the LR update should be done in a pre-update operation?

Thanks!

Frank

**Comment by kpu** [comment]
Frank!  Good to see you.
