### ISSUE TITLE
Incompatabilities in Amun's LSTM implementation

### ISSUE THREAD

**Issue by rihardsk** [marian-nmt/marian#161]
[Amun's LSTM](https://github.com/marian-nmt/marian/blob/1de1e7cb22c5e953eb309395ed059297f0583a0d/src/amun/gpu/dl4mt/lstm.h#L18) uses some extra matrices which aren't present in Marian, namely `*_Ux`, `*_bx` and `*_Wx`. Marian has these as extra columns in `*_U`, `*_b` and `*_W` respectively.

My plan is to bring Amun's implementation in sync with Marian and keep the model loading backwards compatible. To achieve this [model.cu](https://github.com/marian-nmt/marian/blob/8536335da6fbb1c9a5da93409a585f42452303be/src/amun/gpu/dl4mt/model.cu#L112) would append the `*x` matrices to `*_U`, `*_b` and `*_W` if they're present in the model file. 

After this, I think we could enable running Marian-trained LSTM models on Amun. I'll open a separate issue for this on `marian-dev`.

**Comment by emjotde** [comment]
I have a bit mixed feeling about this. I would go as far as too say that no-one apart from the people in this issue ever used the LSTM in amun. If so we are probably not risking to much incompatibilities and complaints and I would rather like to see the Amun format to follow Marian?

**Comment by emjotde** [comment]
I started looking at it: https://github.com/marian-nmt/marian-dev/issues/175

**Comment by rihardsk** [comment]
Yup, that's what I'm proposing - to modify Amun so that those extra matrices don't appear on their own but as columns in `U`, `b` and `W` matrices. Same as in Marian.

So I plan to modify [lstm.h](https://github.com/marian-nmt/marian/blob/8536335da6fbb1c9a5da93409a585f42452303be/src/amun/gpu/dl4mt/lstm.h) to handle matrices like Marian does, and also modify [model.cu](https://github.com/marian-nmt/marian/blob/8536335da6fbb1c9a5da93409a585f42452303be/src/amun/gpu/dl4mt/model.cu#L112) to accept the new matrix format, but also handle the old format in a backwards-compatible way.

Backwards compatibility would currently probably only benefit Tilde but after taking a quick look at [param_init_lstm() in Nematus](https://github.com/EdinburghNLP/nematus/blob/84dfedbab2bf99ed17c438a5658b1271f5f95fbc/nematus/layers.py#L652) it seems that the same mechanism could also be used to support Nematus-trained LSTM models in future, if desired. They have different matrix namings but otherwise the format seems to be the same as currently implemented in Amun.
