### ISSUE TITLE
Undefined reference while compiling amun

### ISSUE THREAD

**Issue by Soupstraw** [marian-nmt/marian#166]
I got this error while trying to compile amun for CPU:

``[ 97%] Linking CXX executable ../../amun CMakeFiles/amun.dir/common/decoder_main.cpp.o: In function `main': decoder_main.cpp:(.text.startup+0x1004): undefined reference to `boost::timer::format[abi:cxx11](boost::timer::cpu_times const&, short)' CMakeFiles/libcommon.dir/common/config.cpp.o: In function `amunmt::Config::AddOptions(unsigned int, char**)':``

I'm currently using:
cmake-3.5.1
gcc-5.4.0
boost-1.58.0

**Comment by hieuhoang** [comment]
See issue 165. For Amun, always use master which should always be stable

**Comment by emjotde** [comment]
Hi, 
what Linux distribution is this?

**Comment by Soupstraw** [comment]
The HPC server I tried compiling marian on is running CentOS Linux release 7.4.1708.

**Comment by emjotde** [comment]
Ah, we traditionally have problems with CentOS. I will try to have a look at that.

**Comment by Soupstraw** [comment]
Here is the command that I used for compilation.
`CXX=~/gcc-5.4.0/bin/g++-5.4.0 CC=~/gcc-5.4.0/bin/gcc-5.4.0 ~/cmake-3.11.0-rc4-Linux-x86_64/bin/cmake -DBoost_NO_BOOST_CMAKE=TRUE -DBOOST_ROOT=~/boost_1_58_0 -DBoost_LIBRARY_DIRS=~/boost_1_58_0/stage/lib ..`

I also tried boost-1.66 and gcc-7.3.0 but still no luck.

**Comment by hieuhoang** [comment]
it compiled ok on my centos 7.3 VM (gcc 7.2, boost 1.66). Personally, I set the boost env variables, rather than passing them to the compiler as arguments.
  export BOOST_ROOT=/home/hieu/workspace/boost/boost
  export BOOST_INCLUDEDIR=$BOOST_ROOT/include
   export BOOST_LIBRARYDIR=$BOOST_ROOT/lib64
Also, you may have mispelt BOOST_LIBRARYDIR as Boost_LIBRARY_DIR. And of course, make sure the library files are in fact in the directory you pointed to

**Comment by hieuhoang** [comment]
any joy, joosep?

**Comment by Soupstraw** [comment]
I'll give it a try later today.

**Comment by Soupstraw** [comment]
Sorry took me a bit longer. Actually our system administrator managed to install it in the meantime, so it's probably something I'm doing wrong. Anyhow, here's the new error after compiling with @hieuhoang 's variables.
``
[100%] Linking CXX executable ../../amun
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `amunmt::Config::AddOptions(unsigned int, char**)':
config.cpp:(.text+0x5764): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
config.cpp:(.text+0x64ae): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
config.cpp:(.text+0x66ec): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
config.cpp:(.text+0x67c1): undefined reference to `boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)'
config.cpp:(.text+0x6891): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
config.cpp:(.text+0x68dd): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
config.cpp:(.text+0x69d0): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
config.cpp:(.text+0x6a24): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
config.cpp:(.text+0x6a78): undefined reference to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
CMakeFiles/libcommon.dir/common/config.cpp.o:config.cpp:(.text+0x6acc): more undefined references to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)':
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x26): undefined reference to `boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)'
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x3c): undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
CMakeFiles/libcommon.dir/common/config.cpp.o: In function `boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const':
config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x17): undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)'
``

**Comment by hieuhoang** [comment]
it look like the same error - the boost library couldn't be found

**Comment by hieuhoang** [comment]
pretty sure this is fixed if boost has be compiled/installed and the env variables have been set correctly. Closing but please reopen if you're still having problems
