### ISSUE TITLE
Marian-nmt: Translation troubles in deep models trained via Nematus framework

### ISSUE THREAD

**Issue by ampersant** [marian-nmt/marian#167]
Hi. I have the following problem:

I train deep models (encoder depth >= 2, decoder depth >=2) via Nematus framework. No matter how big BLEU scores I obtain from training, Marian-nmt fails at translation process, namely it yields as output phrases in selected foreign language, but completely not related to the input in other language. 

For example, for input "hello world" in english it yields in spanish some rubbish related to politics...

I am able to load deep models via Marian. I checked all parameters in running scripts and all necessary corrections were done, but translation still is not working. I tried management of parameters(weights, penalty, beam-search size), but it doesn't help.

I tried detecting flaws while loading deep model with deep encoder with shallow transition and with shallow decoder. I compared Nematus version for training with Marian version. I think that there may be lack of proper mechanism while dealing with multiple layers. I checked the construction process of layers and encoder in Marian and did not find any inconsistencies. According to academic papers, there is potential difference with loading biases in Nematus and Marian. I detected places in Marian's code, but every modifications did not improve the problem stated above, i.e. it still yields rubbish unrelated completely to input.

Could anyone help in this problem? I am really struggling with this issue. I got completely stuck.

Help very, very, very appreciated!!!!!

**Comment by ampersant** [comment]
P.S.: I downloaded Marian-nmt at the beginning of march this year. This version refers to the problem stated above.

**Comment by emjotde** [comment]
Since you seem to have experience in modifying the code, I usually solve things like that by tracing the matrix values in Nematus and Marian and start analyzing things if they start diverging. Marian has the `debug(Expr node, std::string message)` operator. In Nematus there is a set of Theano functions that allows to inspect computation values on the fly.

To be honest, what's the rationale for training things with Nematus in this context? Just switch to Marian. 

BTW. Using less signs of urgency (!!!!) would be appreciated.

**Comment by ampersant** [comment]
@emjotde, thanks for quick reply! As you requested, signs of urgency have been deleted in this post.
I will use the method you mentioned in your post.

Regarding Nematus, I was assigned a task to specifically train model via Nematus and then use trained model in Marian(it is not academic coursework by the way).

As I said, I will apply the method recommended by you. However, since I got really stuck in this aspect(to the extent that I am fighting with this problem over 2 months), I would be very thankful if you would be able to elaborate further on the methods to enable me to solve this frustrating riddle.

**Comment by ampersant** [comment]
Last but not least, which areas of Marian's code would you recommend me to investigate thoroughly to overcome this problem with Marian? Although I checked all .cpp and .h C++ code files in related to the construction of layers and rnn mechanism, I did not manage to find gaps...

**Comment by ampersant** [comment]
Last but not least: I would be very thankful for further advices in this issue.

**Comment by emjotde** [comment]
Well, step through the corresponding parts of the architecture and make sure that at each point the computed values are the same. For instance, are the embeddings the same, is the encoder context the same, etc. There is not really a way around that. 

The model code is in `src/models/s2s.h`, the code for the GRU RNN cells is in `src/rnn/cells.h`.

We do not really have much of a commitment to maintain full compatibility with Nematus if these are some rather obscure model variants. If it took you two months to investigate this, I suppose you might have just retrained all your models in that time a couple of times :)

**Comment by ampersant** [comment]
@emjotde, thanks for additional advices! I will investigate this further with your suggestions. I will try to do my best. I will let you know about acquired conclusions within at least 1 week. Once again, thank you very much for your support!

**Comment by ampersant** [comment]
@emjotde, I tried using debug(Expr node, string message) function, but in building processes of code I constantly obtain error messages in conversion of pointers of appropriate type.
Tried alternatives in code of other already built functions, like  using <sstream> library to enable usage of graphviz() function. Tried mimicing the structure of graphviz() function, but it failed. 
I know that alternative way of obtaining output on console is the use of LOG() function, however it works to some extent as more flexible cout for handling different variables.
It might be the fact that I am doing something wrong, however just to ensure: would you be able to check whether function Debug() gives on the console output in the form of elements of matrices? If so, would you be able to indicate variables in Marian code that enable to use this function properly? I mean, for example, I thought that "params_" or "p" variables may lead to getting access to the elements of the matrices, but they do not.

I would be extremely thankful for advices in this matter.

Thanks for help in advance.

**Comment by ampersant** [comment]
@emjotde, thank you very much for your quick reply! Also, apologies for "bombarding" you with  lots of information. I only wanted to show you in this way that I really made a decent attempt and in spite of persistency I got stuck(unfortunately...).  

There is one subtlety, namely that in order to show you some part of my "struggles" in the form of code or outputs, I must at first refer to my project leaders in person so as  to avoid confidentiality issues (I know this may sound bizzare and insane but they told that in any case of showing direct output from code or just code, I must talk with them to get permission. Nevertheless, I am allowed to state briefly, without going into details, what I do). Now they are away from the office, so I can reach them tommorow. I do not want to get into troubles with such issues, so at first I will talk with them tommorow so as to meet their "rules".

Once again, huge apologies for such unnecessary sophistication :(

**Comment by ampersant** [comment]
@emjotde, apologies for my reaction. I panicked. I think that the best way to both give me constructive hint and to avoid commit you way too much, I would like to encourage you to consider the following possibility: 

For example, in src/graph/expression_graph.h inside function Expr param(std::string name, Shape shape,  Args... args) after line

auto p = params_->get(name);

inside "if" instruction

I found that I am able to read dimensions of matrices in my loaded model. However, after plenty of attempts, I did not manage to make proper use of debug(...) function in this place. I must misunderstand something, but I can't see what. And the problem is that my supervisors are reluctant to show you my "attempts", even in the form of error messages :(
I know this is bizzare, but they are, to some extent, "crazy" :(

Hence, if you would be able to provide me line of code in this file mentioned above and in that place, which I described above,  to get insight into the elements of matrices, I would be really, really, really  thankful. I am a practical person, so such example will hopefully enable me to use debug() function afterwards on my own.

Obviously, your method, if our project suceeds, will be cited and credits will be given to you, so no worries about author rights or doing work for someone. 

Besides, I think that such information would be very useful for other people that use Marian-nmt framework, so it would be also beneficial for community.

**Comment by emjotde** [comment]
The project is completely open source, I don't care about credit. 

Please create a minimal example where you can reproduce the error for code that is not relevant for your project or just for our own code that is already there. Your company cannot say that our own code is secret under their rules.

**Comment by ampersant** [comment]
@emjotde, thank you for your advice. I will download Marian's version at home and will reproduce these code errors. I will try to do it today evening, in the worst case - tommorow evening. In the meantime, I would like to refer to you with 2 uncertainties:
1. The function debug(...) you stated was detected to be located at src/graph/expression_operators.h . However, this function does not have body at all in the entire implementation. Checked on the internet that such cases imply existence of body of such function on the level of binray files. Am I right? The thing is that in the meantime I would like to see its internal structure to be able to understand how to display matrices on the console.

2. I do not understand why debug(...)  function is not visible if it is put in src/graph/expression_graph.h file, even if I include header file, in which debug(...) function is declared. Could you give me some indications at this point or should I assume that no conclusions can be reached without showing you error messages?

I very appreciate your charitable support that I obtained from you hitherto.

As I said, once I return home, I will do things stated above and will let you know about details of errors associated with this the attempts of the usage of debug(...) function.

**Comment by emjotde** [comment]
Of course it has a body, just check the corresponding src/graph/expression_operators.cpp file . 

Next it goes on to https://github.com/marian-nmt/marian-dev/blob/master/src/graph/node.h#L79 which will mark the node in the graph to display debug information during the forward step. 

This then happens in https://github.com/marian-nmt/marian-dev/blob/master/src/tensors/tensor.h#L141
