### ISSUE TITLE
Alignment information missing of one token

### ISSUE THREAD

**Issue by domjehle** [marian-nmt/marian#168]
Hi,

We have discovered that we are missing an alignment of one target token with amun decoding.
We have seen this just once so far, but we were able to reproduce it with that input consistently, even in the current amun build.
We tested all three options (return-alignment, return-nematus-alignment, return-soft-alignment) for alignments and for this specific input we receive 1 alignment less than we have target tokens.

(Anonymized) Example with return-alignments:
8845 3091 3 12 3837 3 3 3 2783 7954 9249 3
Search took 2.109s
Best translation 0 : 4815 403 7 342 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 ||| 0-1 1-0 2-3 3-4 4-6 5-7 6-9 7-9 8-9 9-9 10-9 11-9 12-10 13-10 14-10 15-9 16-9 17-12 18-12 19-12 20-12 21-12 22-12 23-12 24-12 25-12 26-12 27-12 28-12 29-12 30-12 31-12 32-12 33-12 34-12 35-12 36-12 37-12

We have 39 target tokens, but even with index at 0, we only receive 38 alignments instead of 39.

I attached samples where you can see the alignment of one target token is missing.. Also the config.yml we used (made it a .txt so I could upload it...) so you can see our parameter settings.
[amun_return-alignment.txt](https://github.com/marian-nmt/marian/files/1861165/amun_return-alignment.txt)
[amun_return-nematus-alignment.txt](https://github.com/marian-nmt/marian/files/1861166/amun_return-nematus-alignment.txt)
[amun_return-soft-alignment.txt](https://github.com/marian-nmt/marian/files/1861167/amun_return-soft-alignment.txt)
[config.yml.txt](https://github.com/marian-nmt/marian/files/1861168/config.yml.txt)

 I can make an anonymized vocabulary and the corresponding model available, but it's too large to upload here. I just need the email address (for OneDrive) of someone, who will/wants to investigate.

Best regards,
Dominic

**Comment by hieuhoang** [comment]
The translation doesn't look correct with the repeat word '3'. But you're right, the number of alignments should be respected nevertheless.

I may have time to debug this but I would like to use the model in the regression test so that, once fixed, it won't happen again. If you're able to open source the (anonymised) model, I'll take a look at it

**Comment by domjehle** [comment]
Hi,
I've shared the files with you via OneDrive to your email address at gmail. Let me know, if there is anything else you need.

**Comment by hieuhoang** [comment]
Thanks. I tried downloading it but the file seems to be empty. 

Also, can you please post the link here so that I know you can openly share the data to make a regression test

**Comment by domjehle** [comment]
Hi,
I'm sorry about the broken file. I renamed it and it wasn't updated...
It is 560 MB large, one of the reasons I am not allowed by github to post it here, but here is a link https://bit.ly/2H6AlRu.
Yes, you may use it for regression testing, but you have to host it somewhere else, we provide it only for 2 more months on this share.
Thanks!

**Comment by hieuhoang** [comment]
i can't reproduce your output. What is the exact command you ran, the GPU, CUDA/gcc/OS version you are using? Due to float point differences, the inference is not guaranteed to be exactly the same on different hardware and software, which could account for the diference.

O

**Comment by domjehle** [comment]
Hi,
the exact command was '$MARIAN/build/amun -c model/config.yml', then once started up, paste the input sentence. I have attached the config.yml again.
In our standard case where we noticed this issue, we use CPU decoding. We run our decoding in docker containers based on Ubuntu 16.04 docker image.
Amun was compiled with gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9 for our docker images).
We set beam size to 7 for our decoding, but I couldn't see a difference in translation when using beam size 5 (default value that I guess you used?).
[config.yml.txt](https://github.com/marian-nmt/marian/files/1879791/config.yml.txt)

**Comment by hieuhoang** [comment]
i think i know what it is - there's an edge case problem when it goes over the maximum target length (3 times the source length). 

Will debug more when I have time

**Comment by hieuhoang** [comment]
been looking into this, it's definitely due to the output reaching the maximum length. I'm not able to fix it but I've added --max-length-multiple to make the debug reproduceable on my machine. Set it to 1.

If anyone wants to fix it, my advise is to look in history.cpp line 19 and go from there. Please share your code if you manage to fix it
