### ISSUE TITLE
How do I access the length of source sentences inside the attention function?

### ISSUE THREAD

**Issue by Avmb** [marian-nmt/marian#169]
I'm still experimenting with the attention mechanism.

Is there a way to read the length of the encoded sentences from within GlobalAttention's [constructor](https://github.com/EdinburghNLP/marian-dev-private/blob/master/src/rnn/attention.h#L41) ?  
I can't just use of encState->shape([0]) since they are padded.

**Comment by Avmb** [comment]
I guess I can get the EncoderState mask and sum it over the first axis.

**Comment by emjotde** [comment]
Yes, that would work too, especially if you only need it during the forward/backward computation. If you need it during construction, remember the values of mask etc. are initialized lazily.

**Comment by Avmb** [comment]
Ok, I'll see if I can make it work.
Happy Easter!
