### ISSUE TITLE
run marian-server on CPU

### ISSUE THREAD

**Issue by chanberg** [marian-nmt/marian#176]
Hi,

is it possible to run marian-server on CPU? I found the “--cpu-threads” option here: https://marian-nmt.github.io/docs/cmd/marian-server/ 
But when I try running the server with “--cpu-threads”, I get the following error:

Error: unrecognised option '--cpu-threads'

I am using this marian version: https://github.com/marian-nmt/marian/tree/8c119e7cc6f06a2f1332f08e94580fe1af705bd3 
Do I need a more recent version?

Thanks!

**Comment by emjotde** [comment]
Very possible I forgot to support that. Will take a look today.

**Comment by emjotde** [comment]
Oh, yes. Very definitely a newer version.

**Comment by chanberg** [comment]
Great, thanks!
