### ISSUE TITLE
Why the release package has no source code

### ISSUE THREAD

**Issue by arthurxlwang** [marian-nmt/marian#177]
Please forgive me in case I didn't operate correctly.
I download the release version 1.4.0. The folder of src/marian is empty.
So it cannot be compiled. How to solve it?

Thanks.

**Comment by arthurxlwang** [comment]
Thank your for the reply, but the problem remains.

$cmake .. -DCMAKE_BUILD_TYPE=Release
-- Compiling with CUDA support
fatal: Not a git repository (or any of the parent directories): .git
-- Boost version: 1.57.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   timer
--   iostreams
--   python
--   thread
--   chrono
--   regex
--   date_time
--   atomic
-- Found Python
CMake Error at src/CMakeLists.txt:6 (add_subdirectory):
  The source directory

    /export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/marian-1.4.0/src/marian

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/marian-1.4.0/build/CMakeFiles/CMakeOutput.log".
See also "/export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/marian-1.4.0/build/CMakeFiles/CMakeError.log".

**Comment by emjotde** [comment]
Can you try to use git clone instead of the zip?

**Comment by emjotde** [comment]
Oh, wait, I see what happened. The git module is pointing again at an older version. Let me fix this.

**Comment by emjotde** [comment]
Can you try again? Best to remove the previous directory and do a fresh clone.

**Comment by arthurxlwang** [comment]
Yes.  The approach of Downloading zip still does not work.
The git clone works fine.   Thanks.

**Comment by emjotde** [comment]
Yes. I suppose the cmake expects a git repository. Which the zipfile does not provide. I wonder if we can disable zip download somehow.
