### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by arthurxlwang** [marian-nmt/marian#178]
I got the errors of  redefinition of argument 'optimize'  from the following compilation:

git clone https://github.com/marian-nmt/marian.git
cd marian
mkdir build && cd build
cmake .. DCMAKE_BUILD_TYPE=Debug
make -j

============================================================
Cmake 3.6
C++5.4
Cuda8.0

=============================================================

Log: 
[ 51%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_singleton.cu.o
[ 51%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_sync.cu.o
nvcc fatal   : redefinition of argument 'optimize'
CMake Error at marian_generated_expression_graph.cu.o.Debug.cmake:203 (message):
  Error generating
  /export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/github/marian/build/src/marian/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_graph.cu.o

nvcc fatal   : redefinition of argument 'optimize'
CMake Error at marian_generated_node.cu.o.Debug.cmake:203 (message):
  Error generating
  /export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/github/marian/build/src/marian/src/CMakeFiles/marian.dir/graph/./marian_generated_node.cu.o

nvcc fatal   : redefinition of argument 'optimize'
CMake Error at marian_generated_expression_operators.cu.o.Debug.cmake:203 (message):
  Error generating
  /export/disk/NLP/NLPLib/xlCodes/exCudaCodes/marian/github/marian/build/src/marian/src/CMakeFiles/marian.dir/graph/./marian_generated_expression_operators.cu.o

**Comment by arthurxlwang** [comment]
The normal build works better
cmake .. DCMAKE_BUILD_TYPE=Debug

But there are still two errors

/usr/local/lib/libboost_python.so: undefined reference to `PyUnicodeUCS2_AsWideChar'
/usr/local/lib/libboost_python.so: undefined reference to `PyUnicodeUCS2_FromEncodedObject'

**Comment by emjotde** [comment]
Can you include some context around that? It's difficult to guess for me where that comes from.

**Comment by arthurxlwang** [comment]
The full output is:

make -j8
[  3%] Built target fast_align
[  3%] Built target libcnpy
[  4%] Built target atools
[ 21%] Built target libyaml-cpp
[ 37%] Built target libyaml-cpp-amun
[ 37%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_sparse_tensor.cu.o
[ 39%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/graph/marian_generated_expression_graph.cu.o
[ 39%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/graph/marian_generated_expression_operators.cu.o
[ 39%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/graph/marian_generated_node.cu.o
[ 40%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/graph/marian_generated_node_operators.cu.o
[ 40%] Linking CXX executable ../../../../extract_lex
/usr/local/lib/libboost_python.so: undefined reference to `PyUnicodeUCS2_AsWideChar'
/usr/local/lib/libboost_python.so: undefined reference to `PyUnicodeUCS2_FromEncodedObject'
collect2: error: ld returned 1 exit status
make[2]: *** [extract_lex] Error 1
make[1]: *** [src/amun/3rd_party/extract_lex/CMakeFiles/extract_lex.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 40%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/tensors/marian_generated_tensor.cu.o
[ 53%] Built target libcommon
[ 54%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/tensors/marian_generated_device_gpu.cu.o
[ 64%] Built target cpumode
[ 64%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/tensors/marian_generated_memory_piece.cu.o
[ 64%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/kernels/marian_generated_tensor_operators.cu.o
[ 65%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/kernels/marian_generated_dropout.cu.o
[ 65%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/kernels/marian_generated_cudnn_wrappers.cu.o
[ 65%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/layers/marian_generated_param_initializers.cu.o
[ 67%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/layers/marian_generated_convolution.cu.o
[ 67%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/rnn/marian_generated_attention.cu.o
[ 67%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/rnn/marian_generated_cells.cu.o
[ 68%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/optimizers/marian_generated_clippers.cu.o
[ 68%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/optimizers/marian_generated_optimizers.cu.o
[ 68%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/translator/marian_generated_nth_element.cu.o
[ 70%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/translator/marian_generated_helpers.cu.o
[ 70%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_dropper.cu.o
[ 71%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_async.cu.o
[ 71%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_async_drop.cu.o
[ 71%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_sync.cu.o
[ 73%] Building NVCC (Device) object src/marian/src/CMakeFiles/marian.dir/training/marian_generated_graph_group_singleton.cu.o
Scanning dependencies of target marian
[ 73%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/svd/svd.cpp.o
[ 73%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/cnpy/cnpy.cpp.o
[ 75%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/exception.cpp.o
[ 75%] Building CXX object src/marian/src/CMakeFiles/marian.dir/layers/generic.cpp.o
[ 76%] Building CXX object src/marian/src/CMakeFiles/marian.dir/layers/guided_alignment.cpp.o
[ 76%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/utils.cpp.o
[ 78%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/logging.cpp.o
[ 78%] Building CXX object src/marian/src/CMakeFiles/marian.dir/models/model_factory.cpp.o
[ 78%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/config.cpp.o
[ 79%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/config_parser.cpp.o
[ 79%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/history.cpp.o
[ 79%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/output_collector.cpp.o
[ 81%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/scorers.cpp.o
[ 81%] Building CXX object src/marian/src/CMakeFiles/marian.dir/training/validator.cpp.o
[ 81%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/vocab.cpp.o
[ 82%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/corpus.cpp.o
[ 82%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/text_input.cpp.o
[ 82%] Building CXX object src/marian/src/CMakeFiles/marian.dir/rescorer/score_collector.cpp.o
[ 84%] Linking CXX static library ../../../libmarian.a
[ 84%] Built target marian
make: *** [all] Error 2

**Comment by emjotde** [comment]
As a quick workaround edit `src/amun/3rd_partysrc/amun/3rd_party/CMakeLists.txt`
and comment out the following line like this:

```
# add_subdirectory(extract_lex) 
```

**Comment by arthurxlwang** [comment]
Yes. It works. Thank you for your help.
