### ISSUE TITLE
Compilation Errors

### ISSUE THREAD

**Issue by xumin2501** [marian-nmt/marian#179]
I got the errors from the following compilation:
cmake ..
make -j

logs:
Scanning dependencies of target amun
[ 84%] Building CXX object src/amun/CMakeFiles/amun.dir/common/decoder_main.cpp.o
[ 84%] Linking CXX executable ../../amun
CMakeFiles/amun.dir/common/decoder_main.cpp.o：在函数‘main’中：
decoder_main.cpp:(.text.startup+0x1044)：对‘boost::timer::format[abi:cxx11](boost::timer::cpu_times const&, short)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long) [clone .constprop.769]’中：
config.cpp:(.text+0x3e1d)：对‘boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘amunmt::Config::AddOptions(unsigned int, char**)’中：
config.cpp:(.text+0x5455)：对‘boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)’未定义的引用
config.cpp:(.text+0x6276)：对‘boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)’未定义的引用
config.cpp:(.text+0x6498)：对‘boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)’未定义的引用
config.cpp:(.text+0x656a)：对‘boost::program_options::options_description::options_description(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned int, unsigned int)’未定义的引用
config.cpp:(.text+0x663d)：对‘boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
config.cpp:(.text+0x668a)：对‘boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
config.cpp:(.text+0x6773)：对‘boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
config.cpp:(.text+0x67c8)：对‘boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
config.cpp:(.text+0x681d)：对‘boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:config.cpp:(.text+0x6872): more undefined references to `boost::program_options::abstract_variables_map::operator[](std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)’中：
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x26)：对‘boost::program_options::validation_error::get_template[abi:cxx11](boost::program_options::validation_error::kind_t)’未定义的引用
config.cpp:(.text._ZN5boost15program_options16validation_errorC2ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i[_ZN5boost15program_options16validation_errorC5ENS1_6kind_tERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESA_i]+0x3c)：对‘boost::program_options::error_with_option_name::error_with_option_name(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<bool, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE[_ZNK5boost15program_options11typed_valueIbcE6xparseERNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaISB_EE]+0x17)：对‘boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool*, int)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::xparse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&) const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE6xparseERNS_3anyERKSt6vectorIS7_SaIS7_EE]+0x17)：对‘boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)’中：
config.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x1f2)：对‘boost::program_options::to_internal(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
config.cpp:(.text._ZN5boost15program_options25basic_command_line_parserIcEC2EiPKPKc[_ZN5boost15program_options25basic_command_line_parserIcEC5EiPKPKc]+0x261)：对‘boost::program_options::detail::cmdline::cmdline(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<int, char>::name() const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueIicE4nameEv[_ZNK5boost15program_options11typed_valueIicE4nameEv]+0x25)：对‘boost::program_options::arg[abi:cxx11]’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<std::vector<unsigned int, std::allocator<unsigned int> >, char>::name() const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueISt6vectorIjSaIjEEcE4nameEv[_ZNK5boost15program_options11typed_valueISt6vectorIjSaIjEEcE4nameEv]+0x25)：对‘boost::program_options::arg[abi:cxx11]’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<bool, char>::name() const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueIbcE4nameEv[_ZNK5boost15program_options11typed_valueIbcE4nameEv]+0x25)：对‘boost::program_options::arg[abi:cxx11]’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, char>::name() const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv[_ZNK5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcE4nameEv]+0x25)：对‘boost::program_options::arg[abi:cxx11]’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘boost::program_options::typed_value<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>::name() const’中：
config.cpp:(.text._ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv[_ZNK5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcE4nameEv]+0x25)：对‘boost::program_options::arg[abi:cxx11]’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:config.cpp:(.text._ZNK5boost15program_options11typed_valueIjcE4nameEv[_ZNK5boost15program_options11typed_valueIjcE4nameEv]+0x25): more undefined references to `boost::program_options::arg[abi:cxx11]' follow
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘void boost::program_options::validate<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, int)’中：
config.cpp:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi[_ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi]+0xb0)：对‘boost::program_options::validate(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, int)’未定义的引用
config.cpp:(.text._ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi[_ZN5boost15program_options8validateINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEEvRNS_3anyERKSt6vectorINS3_IT0_S4_ISB_ESaISB_EEESaISE_EEPSA_IT_SaISJ_EEi]+0x519)：对‘boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘void boost::program_options::validate<int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)’中：
config.cpp:(.text._ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l[_ZN5boost15program_options8validateIicEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPT_l]+0x1c9)：对‘boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o：在函数‘void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::vector<unsigned int, std::allocator<unsigned int> >*, int)’中：
config.cpp:(.text._ZN5boost15program_options8validateIjcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPS4_IT_SaISG_EEi[_ZN5boost15program_options8validateIjcEEvRNS_3anyERKSt6vectorINSt7__cxx1112basic_stringIT0_St11char_traitsIS7_ESaIS7_EEESaISB_EEPS4_IT_SaISG_EEi]+0x4cb)：对‘boost::program_options::invalid_option_value::invalid_option_value(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30)：对‘boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38)：对‘boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30)：对‘boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38)：对‘boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30)：对‘boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): more undefined references to `boost::program_options::error_with_option_name::substitute_placeholders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE[_ZTVN5boost15program_options11typed_valueINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEcEE]+0x38)：对‘boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EEcEE]+0x38)：对‘boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIbcEE[_ZTVN5boost15program_options11typed_valueIbcEE]+0x38)：对‘boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueISt6vectorIjSaIjEEcEE[_ZTVN5boost15program_options11typed_valueISt6vectorIjSaIjEEcEE]+0x38)：对‘boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIjcEE[_ZTVN5boost15program_options11typed_valueIjcEE]+0x38)：对‘boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const’未定义的引用
CMakeFiles/libcommon.dir/common/config.cpp.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x38): more undefined references to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, bool) const' follow
CMakeFiles/libcommon.dir/common/god.cpp.o：在函数‘amunmt::God::Init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’中：
god.cpp:(.text+0x9031)：对‘boost::program_options::split_unix(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/search.cpp.o：在函数‘amunmt::Search::~Search()’中：
search.cpp:(.text+0x3907)：对‘boost::timer::format(boost::timer::cpu_times const&, short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
CMakeFiles/libcommon.dir/common/search.cpp.o：在函数‘amunmt::Search::Translate(amunmt::Sentences const&)’中：
search.cpp:(.text+0x467f)：对‘boost::timer::format(boost::timer::cpu_times const&, short, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)’未定义的引用
collect2: 错误：ld 返回 1
make[2]: *** [amun] 错误 1
make[1]: *** [src/amun/CMakeFiles/amun.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
Scanning dependencies of target marian
[ 84%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/cnpy/cnpy.cpp.o
[ 84%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/svd/svd.cpp.o
[ 85%] Building CXX object src/marian/src/CMakeFiles/marian.dir/3rd_party/exception.cpp.o
[ 87%] Building CXX object src/marian/src/CMakeFiles/marian.dir/layers/guided_alignment.cpp.o
[ 87%] Building CXX object src/marian/src/CMakeFiles/marian.dir/layers/generic.cpp.o
[ 87%] Building CXX object src/marian/src/CMakeFiles/marian.dir/models/model_factory.cpp.o
[ 87%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/history.cpp.o
[ 87%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/config.cpp.o
[ 89%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/logging.cpp.o
[ 90%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/config_parser.cpp.o
[ 90%] Building CXX object src/marian/src/CMakeFiles/marian.dir/common/utils.cpp.o
[ 92%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/scorers.cpp.o
[ 92%] Building CXX object src/marian/src/CMakeFiles/marian.dir/translator/output_collector.cpp.o
[ 93%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/corpus.cpp.o
[ 93%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/vocab.cpp.o
[ 93%] Building CXX object src/marian/src/CMakeFiles/marian.dir/rescorer/score_collector.cpp.o
[ 93%] Building CXX object src/marian/src/CMakeFiles/marian.dir/training/validator.cpp.o
[ 93%] Building CXX object src/marian/src/CMakeFiles/marian.dir/data/text_input.cpp.o
[ 95%] Linking CXX static library ../../../libmarian.a
[ 95%] Built target marian
make: *** [all] 错误 2

**Comment by hieuhoang** [comment]
Do you know what os and version you are using, boost version (and diff you
compile it yourself or is out instaled by the os), nvcc and gcc version

Hieu Hoang
Sent while bumping into things

**Comment by xumin2501** [comment]
@hieuhoang centos 7.0,boost 1.58,gcc 5.4.0

**Comment by hieuhoang** [comment]
i'm not able to set up a vm with your configuration as it's quite different from the default distribution. However, my ubuntu 16.04 server has the same gcc and boost as yours, it compile marian ok.  

From the error log, it seems like the boost libraries have not been found. Make sure there are files called libboost_*.a or libboost_*.so and that the boost env variable are set correctly. My env variables are
  export BOOST_ROOT=/home/hieu/workspace/boost/boost
  export BOOST_LIBRARYDIR=$BOOST_ROOT/lib64
