### ISSUE TITLE
Propose Logo for Marian-nmt

### ISSUE THREAD

**Issue by mirzazulfan** [marian-nmt/marian#180]
Hi. 
I'm graphic designer. I wanted to contribute to your project and I designed a logo for your project. If you like it, you can use it. it's free. I'll send you files and pr.
![marian-nmt](https://user-images.githubusercontent.com/36124339/40579792-20ebb782-615a-11e8-8fa5-024c971a49b4.png)

**Comment by emjotde** [comment]
Oh wow. That is really cool. Thanks. Do you have experience with git? I would then give you commit access and you contribute the logo to the repo yourself. 

In that case it would probably become part of the MIT license Marian is under, too. Do you have any objections against that? 

You would of course retain copyright and we will also put your name on the webpage, with a link to a portfolio if you like?

**Comment by mirzazulfan** [comment]
I'm glad to hear it, you can download all files (SVG, PDF, PNG, CDR) logo and editables files here [GDrive](https://drive.google.com/drive/folders/1rjrS0WaMx62QiAALWLR3JOOgJcvE6aaj)
i've created a PR #181 please check.
Thanks @emjotde

**Comment by mirzazulfan** [comment]
Hi @emjotde .. tell me if you need some change or anything. I'll fix it. Thanks
