### ISSUE TITLE
@ (at) symbol on translations

### ISSUE THREAD

**Issue by devcem** [marian-nmt/marian#182]
I know it's not an issue but i couldn't find any information why translation returns at symbol with some words. Do you know any why it appears at symbol on output?

**Comment by emjotde** [comment]
Can you give us an example? Sounds like stray BPE segment markers.

**Comment by devcem** [comment]
**Here is an example :** 
We'll be adding some new stuff to make it even more awesome.

**And it's output :** 
fanoušci přid@@ ávají některé nové věci , aby to zvládli ještě víc

I downloaded models from statmt.org and tested with en-cs.

I used this line to execute it :
amun -m model.npz -s vocab.en.json -t vocab.cs.json <<< "We'll be adding some new stuff to make it even more awesome."

It might be about pre-trained models, if this is the case. I'll try to train it with different datasets or parameters but i just wanted to know what they are exactly.

Also this is where i downloaded pre-trained models : http://data.statmt.org/wmt16_systems/en-cs/

**Comment by devcem** [comment]
I think, i solved the problem. As you said it's BPE segment markers. Thank you for comment @emjotde
