### ISSUE TITLE
Can the toolkit be compiled with Cuda9.x ?

### ISSUE THREAD

**Issue by lionheartxlw** [marian-nmt/marian#185]

**Comment by snukky** [comment]
Yes, I usually compile it with cuda 9.1.

**Comment by emjotde** [comment]
I will allow myself to close this issue as there is no problem in compiling marian with cuda 9 that I know of.

**Comment by FrzMe** [comment]
Currently the nvcc compilation specifies "-arch=sm_30; ". Is there a reason for this? Should this be removed? Should a higher target be specified?
Also currently -gencode=arch=compute_70,code=compute_70 for cuda9/volta is not present. Should it be added?

**Comment by hieuhoang** [comment]
I would support moving the compute capability/arch up a bit. Do a pull request and we'll talk about it
