### ISSUE TITLE
how to use vocabulary selection?

### ISSUE THREAD

**Issue by wenyong-h** [marian-nmt/marian#188]
On the [features page of marian](https://marian-nmt.github.io/features/), vocabulary selection is mentioned,
but i can not find any doc for this feature.
It seems `shortlist` in the code is for vocabulary selection.
Could you provide some guides for using vocabulary selection.

**Comment by NValerij** [comment]
My investigations of the same question led me to this article: [https://arxiv.org/abs/1805.12096](https://arxiv.org/abs/1805.12096) (mentioned in FAQ "How can I make the decoding faster?")
There is an explanation of technique used in "4.1 Shortlist".

**Comment by snukky** [comment]
How to use lexical shortlists is described here: https://marian-nmt.github.io/docs/#lexical-shortlists
The mentioned scripts are available in marian-dev: https://github.com/marian-nmt/marian-dev/tree/master/scripts/shortlist

**Comment by wenyong-h** [comment]
Thanks for your information!
