### ISSUE TITLE
Could NOT find SparseHash (missing:  SPARSEHASH_INCLUDE_DIR)

### ISSUE THREAD

**Issue by NLPpupil** [marian-nmt/marian#191]
` cmake ..
-- Compiling with CUDA support
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   timer
--   iostreams
--   python
--   thread
--   chrono
--   regex
--   date_time
--   atomic
-- Found Python
-- Git version: 
-- Could NOT find SparseHash (missing:  SPARSEHASH_INCLUDE_DIR) 
CMake Error at src/marian/CMakeLists.txt:2 (add_subdirectory):
  add_subdirectory given source "amun" which is not an existing directory.

CMake Error at src/marian/CMakeLists.txt:6 (add_subdirectory):
  add_subdirectory given source "marian" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/home/wuhaixu/marian/build/CMakeFiles/CMakeOutput.log".
See also "/home/wuhaixu/marian/build/CMakeFiles/CMakeError.log".`

**Comment by NLPpupil** [comment]
Thank you. I installed the dependencies above then it work. The only problem  is a warning:
`-- Not Found Tcmalloc
CMake Warning at src/marian/CMakeLists.txt:85 (message):
  Cannot find TCMalloc library.  Continuing.
`

**Comment by NLPpupil** [comment]
May I ignore this warning?

**Comment by emjotde** [comment]
Yes, that one is optional.
