### ISSUE TITLE
Looking to implement "Constrained decoding"

### ISSUE THREAD

**Issue by walmsley** [marian-nmt/marian#195]
Given a trained model, I'm interested in decoding in a constrained way: in the case of EN->DE translation, this would involve having an input like "Hello world", and a known phrase of interest like "Hallo Welt". My goal is to evaluate only the probability of "Hallo Welt" as an output phrase, given "Hello World" as an input. (I don't care if "Hallo Welt" is the best output, I just want to measure its score.)

@emjotde can you point me in the right direction about where I should dive in to start implementing this in Marian? Thanks!

**Comment by kpu** [comment]
Read about marian-scorer on https://marian-nmt.github.io/docs/

**Comment by walmsley** [comment]
Oh amazing, didn't realize that's what "scorer" entailed. Thanks!

(I'll consider this closed ... unless I run into problems)
