### ISSUE TITLE
Makefile cleanup suggestions

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian#196]
These are some issues and suggestions that @milipili has spotted when we try to deploy Marian on cloud servers:

- The `-march=native` could be an optional flag instead.
  - [`-march=native` ties the binaries to the local machine](https://github.com/marian-nmt/marian/blob/master/CMakeLists.txt#L11) which might not be suitable for a continuous integration environment if the servers on different steps are built on different machines hidden behind the VM.

- The AVX installation could have been explicitly set as an optional flag too.  

- Marian's Amun using C++ 14 while Marian using C++ 11 to compile, 
  - https://github.com/marian-nmt/marian/blob/master/CMakeLists.txt#L11
  - https://github.com/marian-nmt/marian-dev/blob/master/CMakeLists.txt#L27

**Comment by emjotde** [comment]
I believe we cleaned this up.
