### ISSUE TITLE
Model with copy

### ISSUE THREAD

**Issue by AmitMY** [marian-nmt/marian#203]
I have sentences with unknown tokens that I would like to copy to the output. (every sentence has at least 4 unknown tokens).
Meaning, I want to make a copy/pointer network.

I used the configuration with:
```yaml
type: transformer
allow-unk: true
```

But it neither generates "UNK" nor copies the unknown words.  
Does the transformer model not have this? or is this not implemented at all?

**Comment by emjotde** [comment]
We have no copy mechanism for unknown words. If during training you did not introduce unknown words on purpose, e.g. by removing them from the vocabulary there is no way the model will know that it should even produce UNKs. 

One other way would be to introduce special symbols during training, e.g. <unk_0> <unk_1>, etc. on both side of the corpus. Then during translation you can manually replace your unknown words with one of those symbols and reconstruct the the output. 

There is currently some work going on to forcing output during beam search, but not yet in current master.

**Comment by AmitMY** [comment]
Thanks. The unk_0... suggestion can work pretty well for my case, I will see how it goes. Regarding copy mechanism in general, I really think it is an essential part of any NMT solution, as it's impossible to address all language options with a closed vocabulary. Thanks for letting me know about the current work in progress.

**Comment by emjotde** [comment]
I was philosophically inclined to tread this kind of pre-post-processing as something that happens outside the main NMT engine. Even a proper neural copy mechanism is not guaranteed to do what you want and has been shown to have limited positive effect on NMT quality, at least in terms of BLEU, over the heuristic I mentioned above. 

Also I just use BPE subwords, which for me mostly solve all of the above problems.

**Comment by AmitMY** [comment]
I'll try subwords, that's another interesting direction to go in, I'll read more into that. Thanks.

Last time I implemented my own neural copy model (in DyNet) it made wonders to my results (In my use case, I have a lot of entity names.), furthermore, implementing some constraints, like a checklist model vastly passed SOTA results on a specific task, compared to models that used only attention based NMT with all the entities as possible generations. 

I guess my use case is more specific than the general one, but having all of the entities in the vocabulary creates a huge opening for neural hallucinations.

**Comment by emjotde** [comment]
Oh yes, if you do not have anything that is handling unknown words, anything you do will give you huge improvements. I am a huge believer in BPEs, tried other methods but did not get better results. The trick is to have a common BPE inventory and vocabulary for both languages if applicable.

**Comment by emjotde** [comment]
Closing. Maybe something to revisit later.
