### ISSUE TITLE
Fast Lexically Constrained Decoding with Dynamic Beam Allocation for Neural Machine Translation

### ISSUE THREAD

**Issue by panyang** [marian-nmt/marian#204]
Do you have any plan for Fast Lexically Constrained Decoding? 

Paper Link: https://arxiv.org/abs/1804.06609
It has been implemented in SockEye: https://github.com/awslabs/sockeye/tree/master/tutorials/constraints

Lexically Constrained Decoding is very useful, I hope it can be used by Marian. Thanks a lot.

**Comment by kpu** [comment]
@phikoehn expressed some interest in this.  We might also be interested in Edinburgh.

**Comment by phikoehn** [comment]
I am working on this right now (branch xml), hopefully getting a first working version done by the end of the week. i would appreciate any help.

**Comment by panyang** [comment]
@kpu @phikoehn thanks for your help

**Comment by mjpost** [comment]
Feel free to post here or email me if I can be of any help. The code is almost entirely [self-contained](https://github.com/awslabs/sockeye/blob/master/sockeye/lexical_constraints.py) though the logic does get a bit hairy. If you're following my implementation, note [this PR](https://github.com/awslabs/sockeye/pull/511) which corrects the documentation for maintaining the constrained state for each item on the beam.

**Comment by panyang** [comment]
close this issue
