### ISSUE TITLE
Machine Translation Marathon - Project ideas?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#207]
Hi all,
We will be at the Machine Translation Marathon in Prague. Do you guys have ideas or demands for a fun project to propose?

**Comment by emjotde** [comment]
I think one thing we should add is support for convolutions. This is a serious gap currently.

**Comment by emjotde** [comment]
A Microsoft-themed topic would be the implementation of dual-learning, supervised and unsupervised.

**Comment by emjotde** [comment]
Also, maybe going towards document-level translation?

**Comment by snukky** [comment]
My loose ideas for the MTM project I've collected so far:
* factored models
* self-adaptive translation (this needs to be updated & finished)
* document-level translation
* constrained beam search
* FP16 training 
* multi-language models (something other than the Google's method)

**Comment by alvations** [comment]
+1 factored model and convolution =)

Maybe ensemble different models with different vocabularies?

**Comment by emjotde** [comment]
Different models works, but different vocabularies doesn't really make sense?

**Comment by alvations** [comment]
Isn't that the fun of the challenge? =)
Not sure how to go about implementing it though.

**Comment by CatarinaSilva** [comment]
I've started to implement a way to guide the translation according to this:  https://arxiv.org/pdf/1804.02559.pdf 

Not sure it's enough for a project but if someone is at the MTM and doesn't mind I would love to get some feedback on the way I'm implementing it.

**Comment by emjotde** [comment]
I think we already have a bunch of more interesting ideas here :)

**Comment by CatarinaSilva** [comment]
That's what I thought @emjotde however I would love to have some feedback if some people with more experience on Marian are there :)

**Comment by emjotde** [comment]
@CatarinaSilva I responded to @snukky, that was not meant as a comment on your idea which is of course appreciated. If you are at the MTM too, we will be happy to help.

**Comment by CatarinaSilva** [comment]
Btw, document-level translation sounds quite interesting, what strategy were you guys thinking about?

**Comment by emjotde** [comment]
@chrishokamp Oh cool, will be nice to meet properly in person. Source factors are a matter of 30 mins. Target factors are something of a challenge. But I guess we can get through multiple things and then announce Marian 1.7 after the week, the MTM Anniversary Edition :)

**Comment by emjotde** [comment]
@CatarinaSilva I have not good idea yet. My hunch is that document-level MT is more about data (I have nice ideas for that) than architecture. Just concatenation or multi-encoder might make most of the effort. I would go for WMT rather than IWSLT which is currently the standard set for document-level, but it is also very small. Showing a proper improvement on WMT would be nice result.

**Comment by alvations** [comment]
Related to convolutions, this is some "radical" idea that looks fun too: https://arxiv.org/pdf/1808.03867.pdf

**Comment by kpu** [comment]
Regarding constrained beam search: good plan, just coordinate with #204.  

I like FP16 training; it seems this will be a pervasive change of kernels to typed (as opposed to the focused change for multiplication only).  That is parallelizable once a plan is made in advance.

**Comment by kpu** [comment]
Python interface to Marian? *duck*

**Comment by alvations** [comment]
> Python interface to Marian? duck

Lol, another round of https://github.com/alvations/mosesdecoder/blob/pytuna/scripts/training/pytuna/moses.py ?

**Comment by emjotde** [comment]
*goes back in time, scratches Kenneth's name from Marian paper*

**Comment by alvations** [comment]
But regarding the Python *duck*, I think it's helpful =)

Having a more Pythonic interface (though still calling CLI) for `marian` and `marian-decoder` will help a lot in onboarding new users. Personally, it's hard to onboard a colleague when they can easily do things like:

```python
from companyGorF.something import seq2seq

model = Seq2Seq(data='path/to/data', src='en', trg='de', layers=1, hyperparam1=xyz ... )
mode.train(someargs=xyz)
```

Asking them to do this instead makes them cringe:

```
~/marian -v ... -m .... --something  --hyperparam1 xyz
```

**Comment by emjotde** [comment]
GitHub needs a turd emoji

**Comment by kpu** [comment]
Code documentation?

**Comment by emjotde** [comment]
@kpu That's a good idea. In the same vein I was thinking about scanning for instance PyTorch and implementing all the operators they have, so that we are sort of feature complete.

**Comment by emjotde** [comment]
@alvations what do you mean by yaml config for parameters?

**Comment by alvations** [comment]
@emjotde from PyTorch (specifically fairseq), the model zoo is one thing that marian lacks. 

Also, the arguments (`args`) in the model zoo are the possible features they allow: 
 - https://github.com/pytorch/fairseq/blob/master/fairseq/models/transformer.py#L552
 - https://github.com/pytorch/fairseq/blob/master/fairseq/models/lstm.py#L466
 - https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv.py#L608
 - https://github.com/pytorch/fairseq/blob/master/fairseq/models/fconv_self_att.py#L505


About the yaml file, it's more like https://google.github.io/seq2seq/nmt/#defining-the-model (somewhat like what we did for EMS in Moses)

**Comment by emjotde** [comment]
We are working on something similar, just getting rid of boost::program_options. Next step is to make each model type have it's own options and we are there. There was a time were I intended to do this, but got stuck in other work. That being said, literally all those parameters can be set in our config, just not hierarchally.

**Comment by alvations** [comment]
Ah, I've an idea. The Python API can generate the yml file like in Python/Ruby's JIT. And functions like `Model.train()` or `Model.translate()` will simply call the trainer or decoder on CLI. I don't mind writing this, should be quite fun.

**Comment by emjotde** [comment]
@alvations not sure what you are saying?

**Comment by hieuhoang** [comment]
making Marian more a general purpose DL toolkit. At the moment, it's optimized for an encoder-decoder architecture. It would be nice to use it for non-MT stuff too

**Comment by emjotde** [comment]
This kind of goes against the whole idea though.

**Comment by hieuhoang** [comment]
MT doesn't just mean creating translation systems.

**Comment by emjotde** [comment]
On the other hand it is general purpose. There is nothing that forbids you from using it for other things than enc-dec even now. It's just that enc-dec is well-defined framework. If you just want to do anything there cannot be a framework for anything.

**Comment by alvations** [comment]
In a not-so machine translation use case: https://sigir-ecom.github.io/ecom18DCPapers/ecom18DC_paper_7.pdf 

Maybe supporting other modalities (image, speech, raw vectors of floats, etc.) as input might be nice too.

**Comment by alvations** [comment]
@emjotde related to

> The Python API can generate the yml file like in Python/Ruby's JIT. And functions like Model.train() or Model.translate() will simply call the trainer or decoder on CLI. I don't mind writing this, should be quite fun.

I'm trying to automatically parse the help from any Marian versions and came up with this regex https://regex101.com/r/3CplWT/2/

Just like to clarify what these mean when there's `[=arg(=*)] (=0)`:

```
--exponential-smoothing [=arg(=1e-4)] (=0)
-n [ --normalize ] [=arg(=1)] (=0)
--word-penalty [=arg(=0)] (=0)
```

For example, `--exponential-smoothing [=arg(=1e-4)] (=0)`, does it mean:

 - If the `--exponential-smoothing` flag is not set, the default is 0 , i.e. `(=0)`,
 - If the flag is set but no value is et, the default is 1e-4, i.e. `[=arg(=1e-4)]`

Is the above right?

**Comment by emjotde** [comment]
Uhm, I am still not sure what you are trying to achieve, let's not hijack this thread for this. though. Maybe take a look at --dump-config ?

**Comment by alvations** [comment]
@emjotde I promise it will be relevant to @kpu's

> Python interface to Marian? duck

I'm trying to do the reverse of `--dump-config` and bridging the Python API to `--config config.yml` =)

But yeah, I'm doing something silly enough and getting a headstart for the MTM project. It might end up nowhere but that might solve some crazy problems in doing things like benchmarking Fairseq vs Marian vs T2T.

**Comment by emjotde** [comment]
@alvations I just not sure if @kpu wasn't only joking :) Be careful with turning that into a project.

**Comment by emjotde** [comment]
OK then, maybe time to distill a couple of ideas here to put them into the MTM document. 

* A WMT baseline for document-level MT
* Improving operator coverage and documentation (this also goes into Hieu's request for more general models and could include convolutions)
* Source (easy) and target factors (harder)
* Finish constrained decoding

**Comment by alvations** [comment]
Even if @kpu was joking, a first version is finished. 

https://github.com/alvations/pytuna/blob/master/bleufin.py outputs https://github.com/alvations/pytuna/blob/master/config.yml

**In the near future:** 

 - Creating more automated generated classes (e.g. `class Transformer`) through https://github.com/alvations/pytuna/blob/master/jaunetail.py

 - Possibly hooking the config.yml up with https://github.com/aeroxis/sultan or https://github.com/google/python-fire should do some training through the command-line and make the Python interface looks like a "Just-In-Time" command line caller =)

 - And the Python API could read the `train.log` and pipe to tensorboard / torchvision for monitoring. 

----

It was silly but fun. Now I've to get back to real work ;P

**Comment by emjotde** [comment]
* also maybe reinforcement learning or minimum-risk training

**Comment by kpu** [comment]
I think a python wrapper around the command line is a bad idea.  Almost by definition there's not much value added over the command line interface or server mode.  Only when one can manipulate graphs does it get interesting, which would be much deeper and against the manifesto.

**Comment by alvations** [comment]
@kpu so proper Python API to the C++ objects? BTW, why is accessing the graph from Python against the manifesto? Avoid Tensorflow like software?

**Comment by emjotde** [comment]
@alvations Why would we want to be another python toolkit? There's a million of the around with not so great C++ APIs. Would be better to get the C++ part more usable.

**Comment by emjotde** [comment]
Also I want to be minimal-dependency (@snukky is soon getting rid of boost), going for python with all it's anacondas schmondas is the opposite of that.

**Comment by kpu** [comment]
A properly built python API is an optional add-on, not the only API.

**Comment by kpu** [comment]
> Would be better to get the C++ part more usable.
Currently the code documentation on https://marian-nmt.github.io/docs/ consists of a link to https://marian-nmt.github.io/docs/marian/classes.html which is a dump of class names with no high-level design guidance.

**Comment by alvations** [comment]
> Why would we want to be another python toolkit? There's a million of them around with not so great C++ APIs, despite the fact that their underlying engine is C++. 

Because it reaches more people =)
Takes a while before people get used to the C++ codebase (myself included). 

And things like `validate.sh` could have been a lot more robust if it does less C++ -> STDOUT -> Python/Perl -> STDOUT -> C++

But I get it, it's not very helpful if it's just an API to access the CLI. 

> Would be better to get the C++ part more usable.

Yeah, that part needs some work. I remember that there's a link on creating your own decoder but it's kind of lost on the new website and github wiki. More of those example would have made the need for Pythonic interface less important.

**Comment by emjotde** [comment]
Yeah, I warming up to the idea to just do proper house-keeping at the MTM, combined with extending the operator inventory.

**Comment by hieuhoang** [comment]
That would be a shame not to do something interesting but it does need doing at some point

**Comment by emjotde** [comment]
Thinking about the document-level MT thing. That would be less coding probably, but interesting as an experiment.

**Comment by frankseide** [comment]
"If there is one thing we should steal from the Python people it's their way of creating websites with documentation." The other Python thing that is really useful is that the comments that are used to create documentation can also be used as test cases. doctest will parse the documentation comments and run any example in there and verify that its output is the same as given in the example. Not sure if this can be done in C++ at all.

**Comment by emjotde** [comment]
TBH, I just do not want to have to maintain this.

**Comment by phikoehn** [comment]
In case anybody is interested in the constraint decoding during the Marathon (or otherwise): 

The XML branch has a basic functioning version of this. Pretty much just add the setting `--xml-input` when invoking the decoder, and it can process fun stuff like this:

`<x translation="Trump">Obama</x> empfängt<x translation="Net@@ any@@"> Net@@ any@@ </x> ahu`

It spits out gazillion debugging comments at the moment. This is a very rough version but it works.

TODOs:
- Batched decoding version is broken, this should be an easy fix that I did not want to embark on on a late Sunday night
- The Code uses traditional pointers with major memory leakage. If anybody who understands shared pointers and wants to clean them up, that would be very welcome.
- There is currently no smart logic to ensure that a translation that satisfied all constraints is actually produced (it is preferred if it is produced by a hard-coded bonus)
- Hypothesis generation based on xml maybe should be restricted based on minimum attention weights to the input and minimum probability of the output to avoid degenerative decoder behavior
- Really smart would be also blocking out attention to words that have been covered with satisfied constraints - see http://aclweb.org/anthology/N18-2081.pdf
- All this needs some proper testing

**Comment by hanyh** [comment]
I too think the lexical  constrained decoding is quite useful, like this http://aclweb.org/anthology/N18-2081.pdf
And the more faster implementaion using dymanic beam allocation : https://arxiv.org/pdf/1804.06609v1.pdf
This is supported in Sockeye  https://github.com/awslabs/sockeye/tree/master/tutorials/constraints

**Comment by emjotde** [comment]
MTM is over.
