### ISSUE TITLE
undefined reference to marian::Config::has

### ISSUE THREAD

**Issue by zezke** [marian-nmt/marian#211]
Despite using a fresh Ubuntu 16.04 LTS installation and the recommend software versions (CUDA, CMake...) I cannot build this project. This is the error I am seeing.

`[ 93%] Building CXX object src/marian/src/CMakeFiles/marian_conv.dir/command/marian_conv.cpp.o
[ 94%] Building CXX object src/marian/src/CMakeFiles/marian_decoder.dir/command/marian_decoder.cpp.o
[ 94%] Building CXX object src/marian/src/CMakeFiles/marian_vocab.dir/command/marian_vocab.cpp.o
[ 95%] Building CXX object src/marian/src/CMakeFiles/marian_scorer.dir/command/marian_scorer.cpp.o
[ 95%] Building CXX object src/marian/src/CMakeFiles/marian_server.dir/command/marian_server.cpp.o
[ 95%] Building CXX object src/marian/src/CMakeFiles/marian_train.dir/command/marian.cpp.o
[ 95%] Linking CXX executable ../../../marian-vocab
../../../libmarian.a(logging.cpp.o): In function 'createLoggers(marian::Config const*)':
logging.cpp:(.text+0x1a9e): undefined reference to 'marian::Config::has(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
logging.cpp:(.text+0x1aec): undefined reference to 'marian::Config::has(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
logging.cpp:(.text+0x1c9c): undefined reference to 'marian::Config::has(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
../../../libmarian.a(vocab.cpp.o): In function 'marian::Vocab::create(InputFileStream&, OutputFileStream&, unsigned long)':
vocab.cpp:(.text+0x2554): undefined reference to 'YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
vocab.cpp:(.text+0x2977): undefined reference to 'YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
vocab.cpp:(.text+0x2dd9): undefined reference to 'YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
vocab.cpp:(.text+0x31cd): undefined reference to 'YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
../../../libmarian.a(vocab.cpp.o): In function 'YAML::Node::Node<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
vocab.cpp:(.text._ZN4YAML4NodeC2INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKT_[_ZN4YAML4NodeC5INSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEERKT_]+0xfa): undefined reference to 'YAML::detail::node_data::set_scalar(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceRemainder'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_ValueError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_And'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PySlice_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PySequence_SetSlice'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_Sort'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyImport_ImportModule'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_OverflowError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PySequence_GetSlice'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyType_IsSubtype'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyClass_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyLong_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_FromString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_SetAttrString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_Insert'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyRun_FileExFlags'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_RuntimeError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyComplex_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Copy'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyFile_AsFile'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_CallFunction'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyUnicode_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Size'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_Size'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyEval_CallFunction'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyStaticMethod_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_Reverse'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_NoMemory'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_SetString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_FromStringAndSize'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyBaseObject_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'Py_InitModule4_64'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_IsInstance'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyModule_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_Append'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyMem_Free'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyType_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceLshift'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyProperty_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_InternFromString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Values'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_ClearWeakRefs'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Keys'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyInt_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to '_PyObject_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyInt_FromLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceMultiply'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyArg_ParseTupleAndKeywords'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Subtract'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to '_Py_NoneStruct'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_DelItem'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to '_PyType_Lookup'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyCallable_Check'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_Clear'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Xor'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyLong_AsUnsignedLongLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_ExceptionMatches'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceAdd'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyImport_Import'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyUnicodeUCS4_AsWideChar'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyRun_StringFlags'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyInt_AsLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyFile_FromString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyMethod_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Or'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_NewException'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceOr'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyLong_AsUnsignedLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_ReferenceError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to '_Py_NotImplementedStruct'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyEval_GetGlobals'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_SetObject'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_GetItem'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyComplex_RealAsDouble'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_TypeError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PySequence_DelSlice'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_SetItem'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyType_Ready'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Items'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to '_PyEval_SliceIndex'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Lshift'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_IsTrue'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_GetItemString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Add'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Divide'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyBool_FromLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyTuple_GetItem'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceSubtract'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyFloat_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_IndexError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Clear'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Rshift'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_RichCompare'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_Size'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyLong_AsLongLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyBool_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Multiply'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyIter_Next'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_WarnEx'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_StopIteration'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_Update'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyType_GenericAlloc'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_AsString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_CallMethod'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceAnd'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_GetAttr'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_GetAttrString'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyMem_Malloc'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyTuple_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyCFunction_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyList_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyMethod_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyDict_GetItem'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyTuple_New'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceXor'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_Format'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyObject_SetAttr'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceRshift'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyCFunction_NewEx'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyStaticMethod_Type'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyLong_FromUnsignedLong'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyString_FromFormat'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_AttributeError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyExc_ImportError'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyTuple_Size'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyUnicodeUCS4_FromEncodedObject'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyErr_Occurred'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_InPlaceDivide'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyNumber_Remainder'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyWeakref_NewRef'
/usr/lib/x86_64-linux-gnu/libboost_python.so: undefined reference to 'PyComplex_ImagAsDouble'
collect2: error: ld returned 1 exit status
src/marian/src/CMakeFiles/marian_vocab.dir/build.make:197: recipe for target 'marian-vocab' failed
make[2]: *** [marian-vocab] Error 1
CMakeFiles/Makefile2:656: recipe for target 'src/marian/src/CMakeFiles/marian_vocab.dir/all' failed
make[1]: *** [src/marian/src/CMakeFiles/marian_vocab.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....`

Any idea what I am doing wrong?

**Comment by emjotde** [comment]
Whoa, that's an impressive collection of errors. Let's see if we can pick this apart. 
Can you try this repository instead: http://github.com/marian-nmt/marian-dev ?
This is the development version on might have fewer dependencies.

**Comment by zezke** [comment]
I've tested it on a different machine and it works perfectly out of the box. No clue what the difference is but at least I can run my experiments now.  Thanks!
