### ISSUE TITLE
Clarify documentation on batched decoding

### ISSUE THREAD

**Issue by kpu** [marian-nmt/marian#217]
According to https://marian-nmt.github.io/docs/cmd/marian-decoder/ `--mini-batch arg (=1)` is "Size of mini-batch used during update".  Updates do not make sense in a decoder.  

Maxi was confused by https://marian-nmt.github.io/features/#translation-speed which states "Amun also features 'batched' translation, i.e. multiple sentences are being translated at once on a single GPU." as if to imply that Marian does not support batching.

**Comment by emjotde** [comment]
Not to sound snarky, but all of the person involved here know how to do PRs :)
