### ISSUE TITLE
Using pre-trained model from tensor2tensor

### ISSUE THREAD

**Issue by Raghava14** [marian-nmt/marian#218]
Hi,
I have trained a model for English-German translation using the Transformer  network provided in tensor2tensor walkthrough with shared subword vocabulary. Is there any way I can port the model into Marian  so that I could decode the sentences faster instead of training a whole model from scratch.
Thank you.

**Comment by emjotde** [comment]
Sorry. This is not supported. I read in an issue that this was somehow accomplished by conversion scripts, but this is apparently not public.
