### ISSUE TITLE
Bad results with pretrained model wmt17_systems/en-de Nematus Model

### ISSUE THREAD

**Issue by simonefrancia** [marian-nmt/marian#219]
Hi, 
I am trying to use Nematus models(http://data.statmt.org/wmt17_systems/en-de/) with Marian for S2S en-de Translation task; i use this command as written in documentation:

```
./marian-decoder 
	--type nematus 
	--models /wmt17_systems/en-de/model.l2r.ens1.npz 
	--vocabs /wmt17_systems/en-de/vocab.en.json /wmt17_systems/en-de/vocab.de.json  
	--dim-vocabs 51100 74383   	
	--enc-depth 1     
	--enc-cell-depth 4     
	--enc-type bidirectional      
	--dec-depth 1   
	--dec-cell-base-depth 8  
	--dec-cell-high-depth 1   
	--dec-cell gru-nematus 
	--enc-cell gru-nematus   
	--tied-embeddings true

```

After doing this, I got very very bad results like these:

```
hello ---> ingen 
my name ---> me und
hi ---> it

```

My question is : is there something that I am missing like changing parameters or that is not so good model? 

Any advice is well accepted

Thanks

**Comment by snukky** [comment]
We use exactly this model for our regression tests, and according to our config (https://github.com/marian-nmt/marian-regression-tests/blob/master/models/wmt17_systems/marian.en-de.yml), `--layer-normalization` might be missing in your parameters.

**Comment by simonefrancia** [comment]
You are fantastic! 
Thanks a lot for your advice, now it's working much better!
Another question:
all models that I can use with pretrained, are these (http://data.statmt.org/wmt17_systems) ?
Configurations for each task are different or are all the same?

**Comment by emjotde** [comment]
As far as I am aware, they are the same. If the results look remotely reasonable, then they are probably working. Otherwise thing go completely haywire as you have seen already.

**Comment by snukky** [comment]
Each system has different vocabulary sizes and also `--dim-emb` may vary sometimes. But you shouldn't be able to set those values incorrectly as Marian will complain quickly about them.

**Comment by simonefrancia** [comment]
Thanks for your advice.
I tried also to integrate German to English translator with this command:

```
./marian-decoder \
> --type nematus \
> --models /wmt17_systems/de-en/model.l2r.ens1.npz \
> --vocabs /wmt17_systems/de-en/vocab.de.json /wmt17_systems/de-en/vocab.en.json  \
> --dim-vocabs 74383 51100 \
> --enc-depth 1     \
> --enc-cell-depth 4     \
> --enc-type bidirectional      \
> --dec-depth 1   \
> --dec-cell-base-depth 8  \
> --dec-cell-high-depth 1   \
> --dec-cell gru-nematus \
> --enc-cell gru-nematus   \
> --tied-embeddings true \
> --layer-normalization true```


 and results are appreciable, as you can see.

```UK@@ 24 hours
I need more hours with you
you &apos;ve spent the weekend
Vilnius
we &apos;ve spent the late nights
things Right unify us
but now everything IS Baby
roll the Atlantic
and play me in the video@@ game me nearby
```

First question: is there also a post-processing task that treats special parts of output like "&apos;" "video@@ "? 

Second question: do you know also where can i find a nematus pretrained model for italian-english or english-italian?

Thanks

**Comment by emjotde** [comment]
1) This kind of post-processing needs to handled out-side Marian.
2) We don't really know, you would need to ask the Nematus people maybe?

**Comment by simonefrancia** [comment]
Thanks for your support. 
I close this issue
