### ISSUE TITLE
Did it support mix cpu and GPU?

### ISSUE THREAD

**Issue by Rpersie** [marian-nmt/marian#220]
Now I want to do Nerual network on GPU and  beam search on CPU. Did it support this architecture ? Thank you !

**Comment by emjotde** [comment]
Currently not. We either search on CPU or GPU. Your scenario had no use-case for us for now. What are you planning to do?

**Comment by Rpersie** [comment]
Thank you for your response !
For example, in some condition, I want to translate a sets of sequences as fast as possible. 
So I design to create multithreads to get sequences from the testset. Then every thread puts the sequences on the GPU to compute network prob individually. Last the prob is put back to the cpu to do beamsearch.  So I can use the multicore CPU and GPU as far as possible.

**Comment by emjotde** [comment]
I did some experiments with interleaved computation. Usually the cost from going from CPU to GPU or back is so high that you lose any advantage you might have from parallel computation. You will get much more advantage from batching.

**Comment by Rpersie** [comment]
Thank you !
Do you mean that the batch docoding is pushing a batch sequences one time. The GPU Compute all the sequences NN prob parallelly ? And after the NN compute, it do beam search on the batch one by one ?

**Comment by emjotde** [comment]
The beam search is done in parallel as well in batch decoding.

**Comment by emjotde** [comment]
Just to be clear, that's already implemented in Marian. For instance use `--mini-batch 32 --maxi-batch 100 --maxi-batch-sort src`.
This will translate 32 sentences at once, preload 100 batches and sort sentences into batches by source length.
