### ISSUE TITLE
'YAML::TypedBadConversion<float>' during training

### ISSUE THREAD

**Issue by kellymarchisio** [marian-nmt/marian#221]
I can successfully train a model with the following parameters:
```
$MARIAN/build/marian \
        --train-sets $src_data $trg_data \
        --vocabs $src_vocab $trg_vocab \
        --model model/model.$SRC-$TRG.npz \
        --save-freq 10000 --devices $GPU \
        --log model/train.$SRC-$TRG.log
```

I would like to add validation, so I ran:
```
$MARIAN/build/marian \
        --train-sets $src_data $trg_data \
        --vocabs $src_vocab $trg_vocab \
        --model model/model.$SRC-$TRG.npz \
        --early-stopping 5 --after-epochs 10 \
        --valid-set $src_valid $trg_valid \
        --valid-freq 10000 --save-freq 10000 --devices $GPU \
        --valid-metrics ce-mean-words perplexity translation \
        --valid-log model/train.$SRC-$TRG.valid.log \
        --valid-script-path validate.sh \
        --valid-translation-output data/valid.bpe.$TRG.output --quiet-translation \
        --log model/train.$SRC-$TRG.log 
```

However this fails with:
```
terminate called after throwing an instance of 'YAML::TypedBadConversion<float>'
  what():  bad conversion
train.sh: line 94: 19738 Aborted                 $MARIAN/build/marian --train-sets $src_data $trg_data --vocabs $src_vocab $trg_vocab --model model/model.$SRC-$TRG.npz --early-stopping 5 --after-epochs 10 --valid-set $src_valid $trg_valid --valid-freq 10000 --save-freq 10000 --devices $GPU --valid-metrics ce-mean-words perplexity translation --valid-log model/train.$SRC-$TRG.valid.log --valid-script-path validate.sh --valid-translation-output data/valid.bpe.$TRG.output --quiet-translation --log model/train.$SRC-$TRG.log
```

I experimented with adding back in the validation parameters one-by-one. All can be added add training commenced successfully, except:
`--valid-sets $src_valid $trg_valid ` and `--valid-script-path validate.$TRG.sh` 

I've tried adding the file names in directly instead of using variables.  Adding each of these in isolation to the successful first command as below also elicits the error:
```
$MARIAN/build/marian \
        --train-sets $src_data $trg_data \
        --vocabs $src_vocab $trg_vocab \
        --model model/model.$SRC-$TRG.npz \
        --valid-script-path validate.sh \
        --save-freq 10000 --devices $GPU \
        --log model/train.$SRC-$TRG.log
```

Do we know the cause, and how I can work around this?

**Comment by emjotde** [comment]
Hi, 
I cannot reproduce this with my version. 

* Are you continuing a previous training, i.e. is model/model.$SRC-$TRG.npz poiting to an existing model?
* Can you try https://github.com/marian-nmt/marian-dev ?

**Comment by kellymarchisio** [comment]
- I'm continuing previous training, so yes, model/model.$SRC-$TRG.npz points to an existing model. I've now tried training a model from scratch, and I don't see the error.
- Unfortunately I've had some issues building -v1.6 and -dev, so I'm still running -v1.5 (I apologize - I should have mentioned that in my previous message)

**Comment by frankseide** [comment]
There have been a lot of updates and fixes recently. Can you open an issue for your build problems with v1.6?

**Comment by emjotde** [comment]
I second that. However, since there have also been lots of updates in marian-dev versus 1.6, let's move this to the https://github.com/marian-nmt/marian-dev repo. Could you describe your build problems with that repo there?

**Comment by kellymarchisio** [comment]
Sure, I'll do that by early next week.
