### ISSUE TITLE
Error: out of memory while using de-en model

### ISSUE THREAD

**Issue by gvskalyan** [marian-nmt/marian#223]
I am not able to translate German to English when the input consists of as few as 20k sentences.
I was doing back translation en->de and de->en , used your model and did not face any problem for translating English into German for the entire set(800k sentences).
But when the German output is provided as input to de->en model it is throwing an error after running for few minutes(until it exhausts the available RAM of GPU), meanwhile it is even utilising the GPU without starting to give the translations

Transformer model trained on WMT-14 data

Configuration :  Paperspace machine with  30GB RAM
                                                                    8 x CPU
                                                                    24 GB GPU DEDICATED

**Comment by gvskalyan** [comment]
363 tokens in a particular sentence (repeated punctuation characters separated by whitespace )

**Comment by emjotde** [comment]
That's most likely the problem. Can you please post the complete command you use for translation?

**Comment by gvskalyan** [comment]
do
    cat data/$prefix.bpe.de \
        | $MARIAN/build/marian-decoder -c model/model.npz.decoder.yml -m model.npz -b 4 -n \
        | sed 's/\@\@ //g' \
        | ../tools/moses-scripts/scripts/recaser/detruecase.perl \
        | ../tools/moses-scripts/scripts/tokenizer/detokenizer.perl -l en \
        > data/en.output
done

**Comment by kpu** [comment]
Translation of a 363-token "sentence" mostly made out of punctuation characters is going to be garbage anyway. 
It sounds like you're doing backtranslation.  Suggest filtering to at most ~60 words.

**Comment by gvskalyan** [comment]
Yes since it is back translation I did not bother about the output of the first model .
But will preprocess the translation and retry.
Thank You.

**Comment by emjotde** [comment]
You can use `--max-length 80 --max-length-crop` to cut input to a length of 80 while keeping the line in the output so your line alignment does not get screwed up.
