### ISSUE TITLE
Cumulative updates

### ISSUE THREAD

**Issue by nurv** [marian-nmt/marian#226]
Hey, we are looking into this [paper](https://code.fb.com/ai-research/scaling-neural-machine-translation-to-bigger-data-sets-with-faster-training-and-inference/) from Facebook, particularly cumulative updates. Marian doesn't seem to support this. Is this possible, and how hard it is to implement?

Thanks

**Comment by emjotde** [comment]
Oh we had that for years, just specify `--optimizer-delay N`.

**Comment by snukky** [comment]
Added _faq_ label.
