### ISSUE TITLE
Saving models

### ISSUE THREAD

**Issue by Jmallins** [marian-nmt/marian#229]
Hi, 

When trying to save models I get the following error:

Saving model weights and runtime parameters to /home/jmallinson/marian/test/model2.npz.orig.npz
[2018-12-02 16:15:35] Error: Swap requires at least two graphs
[2018-12-02 16:15:35] Error: Aborted from virtual void marian::DefaultCommunicator::swapParams(const std::vector<std::shared_ptr<marian::TensorBase> >&) const in /home/jmallinson/marian/src/training/communicator.h:206

**Comment by alvations** [comment]
What's your output of `df -h` on the terminal?  I suspect the disk is out of space.

**Comment by emjotde** [comment]
You are training on one GPU right? Remove the --sync-sgd option.

**Comment by Jmallins** [comment]
> You are training on one GPU right? Remove the --sync-sgd option.

Thanks that works :)

**Comment by frankseide** [comment]
@emjotde, is this something you could look at? I don't understand the logic of `DefaultCommunicator::swapParams()`.

**Comment by emjotde** [comment]
Yes, I will. We can close this issue here, as this one https://github.com/marian-nmt/marian-dev/issues/390 is already reported. I have to admit I forgot about it. Will probably be handled today.

**Comment by emjotde** [comment]
@Jmallins Can you give me the the version of your executable?
```
./marian --version
```

**Comment by Jmallins** [comment]
> @Jmallins Can you give me the the version of your executable?
> 
> ```
> ./marian --version
> ```

v1.7.0 56fc65d 2018-11-27 14:12:26 -0800
