### ISSUE TITLE
Compiling under ubuntu18 with gcc-7.3.0 and CUDA-10

### ISSUE THREAD

**Issue by SamuelLarkin** [marian-nmt/marian#232]
TL;DR
Turns out that in version 1.7.0 there is a missing `include <random>` in `src/data/sentencepiece_vocab.cpp`

Hi,
  I'm trying to compile Marian under Ubuntu 18 with gcc-7.3.0 (default compiler) using CUDA-10 and I'm getting an error message when running `cmake` that it couldn't define `CUDA_cublas_device_LIBRARY`.  Doing a quick google lookup, it seems that [libcublas_device was *deprecated* in CUDA-9.2](https://devtalk.nvidia.com/default/topic/1043972/jetson-agx-xavier/where-can-i-find-libcublas_device-so-or-libcublas_device-a-/post/5297729/#5297729)

```
......
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "marian_conv" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_vocab" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_train" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_decoder" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_scorer" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src

-- Configuring incomplete, errors occurred!
```

**Comment by emjotde** [comment]
Hi, I just ran into that problem yesterday. CMake 3.10 shipped with ubuntu 18.04 is too old for the new Cuda versions. 3.12 works. 




Get Outlook for Android







On Mon, Dec 10, 2018 at 12:14 PM -0800, "Samuel Larkin" <notifications@github.com> wrote:












Hi,

I'm trying to compile Marian under Ubuntu 18 with gcc-7.3.0 (default compiler) using CUDA-10 and I'm getting an error message when running cmake that it couldn't define CUDA_cublas_device_LIBRARY.  Doing a quick google lookup, it seems that libcublas_device was deprecated in CUDA-9.2
......
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUDA_cublas_device_LIBRARY (ADVANCED)
    linked by target "marian_conv" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_vocab" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_train" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_decoder" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src
    linked by target "marian_scorer" in directory /space/group/nrc_ict/download/build/ubuntu18/marian.git/src

-- Configuring incomplete, errors occurred!

**Comment by emjotde** [comment]
Well yes, 3.7 is even older than 3.10, so same problem? 




Get Outlook for Android







On Mon, Dec 10, 2018 at 12:29 PM -0800, "Samuel Larkin" <notifications@github.com> wrote:












Thanks but I forgot to mention that I'm using cmake-3.7.2.

I've cloned Marian's github repository and I checked out version 1.7.0.

**Comment by SamuelLarkin** [comment]
Yes sorry, I made the previous comment for documentation.

**Comment by snukky** [comment]
It is likely that any version of Marian using CUDA 10 requires cmake 3.12.2+. We have a notice about this on the 'Quick start' page. Maybe not easy enough to see.

**Comment by snukky** [comment]
@SamuelLarkin Have you tried to compile protobuf yourself following https://marian-nmt.github.io/docs/#sentencepiece? Did it not work for you? I would like to see what was the error, find a solution, and update our instructions if necessary. Thanks.

**Comment by SamuelLarkin** [comment]
@snukky , I can't install libprotobuf, I'm on a 'bare system'.  Thus, I compiled libprotobuf but I wanted to compile not only protobuf-cpp.  I'll find my commands and edit this post later on what I actually tried in details.

Thanks

**Comment by SamuelLarkin** [comment]
I finally got marian to compile by adding the following include to `sentencepiece_vocab.cpp`
```diff
diff --git a/src/data/sentencepiece_vocab.cpp b/src/data/sentencepiece_vocab.cpp
index 21c38200..568917a9 100755
--- a/src/data/sentencepiece_vocab.cpp
+++ b/src/data/sentencepiece_vocab.cpp
@@ -12,6 +12,7 @@
 #include "common/regex.h"

 #include <sstream>
+#include <random>

 namespace marian {
```
