### ISSUE TITLE
Tutorial missing reference translation

### ISSUE THREAD

**Issue by mila-mila** [marian-nmt/marian#237]
Hello, I am a newbie, following MT Marathon 2018 Labs tutorial, first step on how to translate with a pre-trained model: https://marian-nmt.github.io/examples/mtm2018-labs

When I reach the evaluation part, this line does not work:
cat data/newstest2015.ende.out | ./sacreBLEU/sacrebleu.py data/newstest2015.ende.ref
because data/newstest2015.ende.ref file is missing.

I guess this is the file generated in the previous step with a different name, like this:
/sacreBLEU/sacrebleu.py -t wmt15 -l en-de --echo ref > data/newstest2015.ende.de

Is this correct? Thank you.

I have now moved on to training, there is typo in the Training command, it is missing an 's' in the option --train-set(s):

../../marian-dev/build/marian \
  --model model/model.npz \
  --train-set data/corpus.bpe.ro data/corpus.bpe.en \
  --disp-freq 100

**Comment by snukky** [comment]
Many thanks! Fixed. The training command works with Marian v1.6 and previous versions as those use Boost CLI that can expand option names.
