### ISSUE TITLE
Left-to-right model and right-to-left model can be used to decode together without warning

### ISSUE THREAD

**Issue by OneMoreSecond** [marian-nmt/marian#238]
And give bad results, of course.

**Comment by emjotde** [comment]
Thanks. 

@snukky That would need to be detected in some early validation step in the config. It's actually not trivial when I think of it. I am close to saying that this is a user error :)

**Comment by snukky** [comment]
The `right-left` option is stored in `special:model.yml` in a model .npz file, so checking if all models have the same value should work. I don't see why it's not trivial for a basic usage.

**Comment by frankseide** [comment]
Definitely not a user error. A model knows (or can know) whether it is left-to-right or not. This should drive the decoder.
