### ISSUE TITLE
May i use the nematus to decode with marian(type transformer) deep model?

### ISSUE THREAD

**Issue by cong1** [marian-nmt/marian#239]
Hi,
I have trained a model using the Transformer network.And may i use the nematus to decode with marian(type transformer) deep model?
Or may i use the nematus to decode with marian(type nematus or amun) deep model?

**Comment by emjotde** [comment]
Hi,
most likely not. Our implementation is in Marian since late 2017, Nematus only just added theirs. I don't think they based it on our version.

**Comment by cong1** [comment]
thank you, I know now
