### ISSUE TITLE
make -j error

### ISSUE THREAD

**Issue by sunshinefangxu** [marian-nmt/marian#240]
when I "make -j"  errors occured as follows:
make[2]: *** No rule to make target `../.git/logs/HEAD', needed by `../src/common/git_revision.h'.  Stop.
make[1]: *** [src/CMakeFiles/marian_version.dir/all] Error 2

Please take a look at what caused this problem.

**Comment by frankseide** [comment]
Are you building from inside a git repo clone?

**Comment by syifan** [comment]
I am having the same issue. I am using marian as a submodule of another project. Probably this would not work.

**Comment by snukky** [comment]
This could happen if Marian was compiled from a release tarball (which is not supported), or as a submodule. The latter has been improved and should work at least in marian-dev. Closing, feel free to re-open if the issue still exists.

**Comment by kaivu1999** [comment]
I am facing the same issue.

I have even tried getting the repo from zip instead of git clone.

**Comment by snukky** [comment]
Do you use Marian as a submodule maybe? And actually using repo from zip is known to have this issue, while `git clone` should be fine.

**Comment by kaivu1999** [comment]
Hi @snukky, 
Yes, I used it as a submodule and even tried cloning Marian repo directly, but getting the same error.
