### ISSUE TITLE
g++ version change

### ISSUE THREAD

**Issue by JakubStefko** [marian-nmt/marian#245]
I am trying to change version of g++ used to cmake.
I used commend: `cmake .. -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-7`
in build subdir but the result is still the same (it uses default g++ 8)
System: linux manjaro
![gppproblem](https://user-images.githubusercontent.com/22076033/52171038-df166100-2755-11e9-914a-400c516f22e4.png)

**Comment by tomekd** [comment]
That works for me:
```
cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-7 -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-7  .. -DCMAKE_C_COMPILER=/usr/bin/gcc-7
```

**Comment by snukky** [comment]
This also worked for me:

    CC=/usr/bin/gcc-7 CXX=/usr/bin/g++-7 cmake ..
