### ISSUE TITLE
script for checkpoint averaging (average.py)

### ISSUE THREAD

**Issue by Gldkslfmsd** [marian-nmt/marian#247]
Hello,
can I ask, where do I find the script for checkpoint averaging? What happened with it? It was in `scripts` directory last summer but I can't find it anymore. Last time I found it through https://groups.google.com/forum/#!searchin/marian-nmt/averaging%7Csort:date/marian-nmt/1HYpQzx3Ey0/Q5P1yc8BBAAJ . I would like to use it again.

Thanks!

**Comment by Gldkslfmsd** [comment]
I just found it in history, it was there in 1.6.0:
https://github.com/marian-nmt/marian/blob/bda9b18b6cede63b0476e9c144da3f62f03515b1/scripts/average.py

Does it still work with the newest checkpoints, including Transformer with AAN?

**Comment by emjotde** [comment]
@snukky Can you bring that script back and confirm it works? It should as it just looks at all the tensors and assumes that they match.

**Comment by snukky** [comment]
Tested and added: https://github.com/marian-nmt/marian-dev/commit/993025327f83e47c0b996690f661d4b54f8d2146
