### ISSUE TITLE
how to set parameters when train a language model

### ISSUE THREAD

**Issue by prigioni** [marian-nmt/marian#252]
Error: Aborted from void marian::gpu::fill(marian::Ptr<marian::Backend>, T*, T*, T) [with T = float; marian::Ptr<marian::Backend> = std::shared_ptr<marian::Backend>]

**Comment by emjotde** [comment]
Could you elaborate? this doesn't really allow us to infer anything.

**Comment by snukky** [comment]
Closing due to long inactivity. Please reopen and provide more details if the issue has not been solved.
