### ISSUE TITLE
What is the --optimize  option doing when decoding?

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian#256]
What is the `--optimize`  option doing when decoding? The help message says

 > Optimize speed aggressively sacrificing memory or precision

Are there pointers to the code where these optimization occurs?

**Comment by emjotde** [comment]
This is for CPU decoding, enables 16-bit matrix multiply and auto-tuning. Might help with CPU decoding speed or not, something to try. Doesn't do anything on GPU for the moment.

**Comment by alvations** [comment]
Thanks for the explanation!

What's auto-tuning? CPU decoding on our machines is at least 6x-8x slower =(

**Comment by emjotde** [comment]
Slower than what? GPU? Of course it is.

**Comment by emjotde** [comment]
http://aclweb.org/anthology/W18-2716

**Comment by alvations** [comment]
Ah thanks! 

Yeah was expecting a lot more than 8x slower but I think 8x slower than GPU is bearable considering the cost.

**Comment by emjotde** [comment]
You can a lot faster if you adjust model architecture etc. With a typical model 8x slower is actually really good. The competition is a lot slower or needs to use special tools.
