### ISSUE TITLE
Is NCCL used in CPU decoding? 

### ISSUE THREAD

**Issue by alvations** [marian-nmt/marian#260]
When compiling with `-DCUDA=OFF`, NCCL seems to be still compiling but changing the `.cu` files to `.o`. Is that normal? Is NCCL used in decoding when there's no GPU?

**Comment by emjotde** [comment]
Err, no, it's not used. Is that still the case for `marian-dev`?

**Comment by emjotde** [comment]
Are you sure that NCCL is compiled without CUDA? When I look into the CMakeLists file everything concerning NCCL is clearly inside the IF block that uses or switches off everything CUDA-related. Might be CMake cache issues. Try to confirm this on a fresh clone and build, maybe?

**Comment by snukky** [comment]
A fresh clone of marian-dev (v1.7.8 c65c26d 2019-08-11 18:27:00 +0100) compiled with `cmake .. -DCOMPILE_CUDA=off` does not compile NCCL.
