### ISSUE TITLE
Error- bash: pretrained/newstest2016.tok.tc.bpe.ro: No such file or directory, missing pretrained model

### ISSUE THREAD

**Issue by sanjita-suresh** [marian-nmt/marian#262]
I am trying the [tutorial](https://marian-nmt.github.io/examples/mtm2017/intro/) to translate testsets from Ro-En using pretrained model but I am geting the error below in the data preprocessing step.

```
bash: pretrained/newstest2016.tok.tc.bpe.ro: No such file or directory
ERROR: could not open 'pretrained/truecase-model.ro' at ./moses-scripts/scripts/recaser/truecase.perl line 26.
Tokenizer Version 1.1
Language: ro
Number of threads: 1
Traceback (most recent call last):
  File "./mtm2017-tutorial/scripts/remove-diacritics.py", line 20, in <module>
    ostream.write(line)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "./mtm2017-tutorial/scripts/normalise-romanian.py", line 17, in <module>
    ostream.write(line)
BrokenPipeError: [Errno 32] Broken pipe 
```

**Comment by snukky** [comment]
This tutorial is a bit out-dated and it actually doesn't mention where to get the pretrained model from. I recommend using a newer version of this tutorial: https://marian-nmt.github.io/examples/mtm2018-labs

**Comment by sanjita-suresh** [comment]
@snukky Thank you for the suggestion.

**Comment by snukky** [comment]
A number of Marian models is available from for example [Opus-MT](https://github.com/Helsinki-NLP/Opus-MT) or [BrowserMT](https://github.com/browsermt/students).
