### ISSUE TITLE
Error: CUDA error 2 'out of memory'

### ISSUE THREAD

**Issue by wingsyuan** [marian-nmt/marian#270]
Hi,
@snukky @frankseide 
when  I use the trainning script as follow:
it raise the error: Error: CUDA error 2 'out of memory'
I use four titan xp for training,  Can you tell me with how to set the parameter properly?
Thanks very much!!!

WORKSPACE=9000
EPOCHS=60
B=12

mkdir -p model-sentenpiece

$MARIAN/marian \
    --devices $GPUS \
    --type transformer \   
    --train-sets ../clean_uniq_train.zh ../clean_uniq_train.en \
    --max-length 100 \    
    --sentencepiece-options '--normalization_rule_tsv=data/norm_romanian.tsv' \
    --dim-vocabs 32000 32000 \
    
    -

**Comment by emjotde** [comment]
Hi,
by increasing the vocab size, you have changed the model size. Try to reduce your value for WORKSPACE by 500.

**Comment by wingsyuan** [comment]
@emjotde 
Hi,
thanks for your help..
but when I reduce the value for WORKSPACE to 5500, it still raised the error:Error: CUDA error 2 'out of memory' 

and the value 5000 it raised another:
Error: NCCL error 1 'unhandled cuda error'

**Comment by wingsyuan** [comment]
Hi,
what does the option ‘--mini_batch 1000’ mean with '--mini-batch-fit' ?

**Comment by wingsyuan** [comment]
It is my mistake to set the wrong value.
Thanks.

**Comment by MemduhG** [comment]
Hello, I am getting the same crash trying to run a transformer model. 
```
Error: CUDA error 2 'out of memory' - ....../device.cu:32: cudaMalloc(&data_, size)
Error: Aborted from virtual void marian::gpu::Device::reserve(size_t) in ......./gpu/device.cu:32
```

This is the command I use to run it:
```
WORKSPACE=9000
N=4
EPOCHS=8
B=12

cd $PBS_O_WORKDIR 

  # train model
    $MARIAN_TRAIN \
        --model model/ens1/model.npz --type transformer \
        --train-sets data/all.bpe.en data/all.bpe.tr \
        --max-length 100 \
        --vocabs model/vocab.entr.yml model/vocab.entr.yml \
        --mini-batch-fit -w 5000 --maxi-batch 100 \
        --valid-freq 5000 --save-freq 5000 --disp-freq 500 \
        --valid-metrics ce-mean-words perplexity translation \
        --valid-sets data/valid.bpe.en data/valid.bpe.tr \
        --valid-script-path "bash ../../scripts/validate_tr.sh" \
        --valid-translation-output data/valid.bpe.en.output --quiet-translation \
        --beam-size 12 --normalize=1 \
        --valid-mini-batch 64 \
        --overwrite --keep-best \
        --early-stopping 5 --after-epochs $EPOCHS --cost-type=ce-mean-words \
        --log model/ens1/train.log --valid-log model/ens1/valid.log \
        --enc-depth 6 --dec-depth 6 \
        --tied-embeddings-all \
        --transformer-dropout 0.1 --label-smoothing 0.1 \
        --learn-rate 0.0003 --lr-warmup 16000 --lr-decay-inv-sqrt 16000 --lr-report \
        --optimizer-params 0.9 0.98 1e-09 --clip-norm 5 \
        --devices 0 1 --sync-sgd --seed 1111  \
        --exponential-smoothing \
        --tempdir /storage/plzen1/home/memduh/npfl101/projects/2019-2020-winter/memduh/shuffled
```

I have tried changing the workspace to a number of things, first trying 9500 then 9000, 3500, 5000, 15000, 14000 etc, it all crashes at various points. When I set it to 15000 or 14000 it crashes almost immediately. Is there some other parameter I could change to get things to work?

I am running on two Tesla T4 GPUs which have about 15GB memory each.

**Comment by snukky** [comment]
What's the size of your vocabularies? (can be read from the config logs displayed at the beginning of the training). Is this the only process running on GPUs?

**Comment by MemduhG** [comment]
```
[2020-02-19 11:59:17] [data] Loading vocabulary from JSON/Yaml file model/vocab.entr.yml
[2020-02-19 11:59:17] [data] Setting vocabulary size for input 0 to 33441
[2020-02-19 11:59:17] [data] Loading vocabulary from JSON/Yaml file model/vocab.entr.yml
[2020-02-19 11:59:17] [data] Setting vocabulary size for input 1 to 33441
```

As far as I understand it's the only process on the GPUs, this is nvidia-smi output from when I tried with 2000 workspace:

```+-----------------------------------------------------------------------------+

| NVIDIA-SMI 418.87.01    Driver Version: 418.87.01    CUDA Version: 10.1     |

|-------------------------------+----------------------+----------------------+

| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |

| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |

|===============================+======================+======================|

|   0  Tesla T4            Off  | 00000000:12:00.0 Off |                    0 |

| N/A   64C    P0    71W /  70W |  13937MiB / 15079MiB |     32%      Default |

+-------------------------------+----------------------+----------------------+

|   1  Tesla T4            Off  | 00000000:D8:00.0 Off |                    0 |

| N/A   75C    P0    35W /  70W |  11633MiB / 15079MiB |      0%      Default |

+-------------------------------+----------------------+----------------------+

                                                                               

+-----------------------------------------------------------------------------+

| Processes:                                                       GPU Memory |

|  GPU       PID   Type   Process name                             Usage      |

|=============================================================================|

|    0      9180      C   ...strava1/home/memduh/marian/build/marian 13927MiB |

|    1      9180      C   ...strava1/home/memduh/marian/build/marian 11623MiB |

+-----------------------------------------------------------------------------+


```

**Comment by emjotde** [comment]
Can you post your full log? Also for the future, please open a new issue. Memory errors can be caused by a gazillion of things.

**Comment by MemduhG** [comment]
Here is the full log: https://paste2.org/saBveKhf

I will open a new issue in such cases in the future.

**Comment by emjotde** [comment]
Hm, can you check  your validation sets if they have really long lines in there?

**Comment by Nebisjames** [comment]
[2020-05-05 18:48:50] [config] workspace: 9000
[2020-05-05 18:48:50] [config] Model is being created with Marian v1.9.9 f2347a8 2020-04-27 10:34:10 +0100
[2020-05-05 18:48:50] Using synchronous SGD
[2020-05-05 18:48:50] [data] Loading vocabulary from JSON/Yaml file ./models/EnHi.1/vocab.yml
[2020-05-05 18:48:50] [data] Setting vocabulary size for input 0 to 115
[2020-05-05 18:48:50] [data] Loading vocabulary from JSON/Yaml file ./models/EnHi.1/vocab.yml
[2020-05-05 18:48:50] [data] Setting vocabulary size for input 1 to 115
[2020-05-05 18:48:50] [sqlite] Reusing persistent database ./models/EnHi.1/corpus.sqlite3
[2020-05-05 18:48:50] [comm] Compiled without MPI support. Running as a single process on ubuntu
[2020-05-05 18:48:50] [batching] Collecting statistics for batch fitting with step size 10
[2020-05-05 18:48:50] [memory] Extending reserved space to 9088 MB (device gpu0)
[2020-05-05 18:48:50] Error: CUDA error 2 'out of memory' - /home/imo/news-translit-nmt-master/tools/marian-dev/src/tensors/gpu/device.cu:38: cudaMalloc(&data_, size)
[2020-05-05 18:48:50] Error: Aborted from virtual void marian::gpu::Device::reserve(size_t) in /home/imo/news-translit-nmt-master/tools/marian-dev/src/tensors/gpu/device.cu:38

[CALL STACK]
[0x1db8c8b]         marian::gpu::Device::  reserve  (unsigned long)    + 0x19cb
[0xaf1662]          marian::SyncGraphGroup::  SyncGraphGroup  (std::shared_ptr<marian::Options>,  std::shared_ptr<marian::IMPIWrapper>) + 0xc82
[0x6bb9a0]          std::shared_ptr<marian::SyncGraphGroup> marian::  New  <marian::SyncGraphGroup,std::shared_ptr<marian::Options>&,std::shared_ptr<marian::IMPIWrapper>&>(std::shared_ptr<marian::Options>&,  std::shared_ptr<marian::IMPIWrapper>&) + 0x70
[0x722d5e]          marian::Train<marian::SyncGraphGroup>::  run  ()   + 0x1de
[0x660ae7]          mainTrainer  (int,  char**)                        + 0x447
[0x62b72a]          main                                               + 0x8a
[0x7f8dbd7ef830]    __libc_start_main                                  + 0xf0
[0x65e5d9]          _start                                             + 0x29

train-model.sh: line 49:  5428 Aborted                 (core dumped) $MARIAN/marian --devices $GPUS $OPTIONS --model $MODEL/model.npz --type s2s --train-sets $DATA/$LANGS.train.{src,trg} --vocabs $MODEL/vocab.yml $MODEL/vocab.yml --sqlite $MODEL/corpus.sqlite3 --max-length 100 --mini-batch-fit -w 9000 --mini-batch 100 --maxi-batch 1000 --best-deep --dropout-rnn 0.2 --dropout-src 0.2 --dropout-trg 0.1 --tied-embeddings-all --layer-normalization --exponential-smoothing --learn-rate 0.0001 --lr-decay 0.8 --lr-decay-strategy stalled --lr-decay-start 1 --lr-report --valid-freq 500 --save-freq 2000 --disp-freq 100 --valid-metrics ce-mean-words translation --valid-translation-output $MODEL/dev.out --quiet-translation --valid-sets $DATA/$LANGS.valid.{src,trg} --valid-script-path $MODEL/validate.sh --valid-mini-batch 64 --beam-size 10 --normalize 1.0 --early-stopping 10 --cost-type ce-mean-words --overwrite --keep-best --log $MODEL/train.log --valid-log $MODEL/valid.log


Need Help . how do i sole this error

**Comment by kpu** [comment]
@Nebisjames configure Marian to use less memory?  Hint: `-w` controls how much memory to pre-allocate.

**Comment by Nebisjames** [comment]
Error: Expected exactly 1 arguments to --mini-batch-fit, got 2
Run with --help for more information.

after i change the value its trun out like this

**Comment by Nebisjames** [comment]
How can I ran for a single language

**Comment by emjotde** [comment]
How about you try one of the examples first, like this one:
https://github.com/marian-nmt/marian-examples/tree/c19b7814d71febf1053bd93af6ac314b46204092/transformer

You can change the memory used modifying the --workspace or -w option in the script.
