### ISSUE TITLE
Is Marian Google Group working?

### ISSUE THREAD

**Issue by Gldkslfmsd** [marian-nmt/marian#273]
Hello,
I know this may not be the appropriate place to ask this question, but on the FAQ page there is

> Where can I get support?

> There is a Google discussion group available at https://groups.google.com/forum/#!forum/marian-nmt. You can send questions to the group by e-mail: marian-nmt@googlegroups.com.

This link doesn't work for me, it seems the group doesn't exist. On the email I got automatic reply the same.

Did you move or renamed or deleted the group? Is there a new forum?

**Comment by snukky** [comment]
It still works.

**Comment by Gldkslfmsd** [comment]
You're right. Blame Google for this:

![image](https://user-images.githubusercontent.com/5314653/59367422-55e2ec80-8d3c-11e9-9468-2f98aac31b2d.png)

No clue to join and read the posts. There are secret doors only.

**Comment by magali-joine** [comment]
Link gives me the "not found" error. is there a way to subscribe to the group via email, like subscribe-marian-nmt@xxxx.yyy ?

**Comment by magali-joine** [comment]
It behaves like the group is "hidden" or "private" or something.
However, if you send an email to "marian-nmt+subscribe@googlegroups.com" then reply to confirm via email (don't click the link) you can then access the group via the web to search the history.

**Comment by snukky** [comment]
The group was visible and searchable only for its members. I changed the setting, so that anyone on the web should be able to read it.

**Comment by magali-joine** [comment]
Thank you! Will test.

**Comment by magali-joine** [comment]
Confirmed. Able to view group as non-member logged into groups.google.com.
