### ISSUE TITLE
-Werror=implicit-fallthrough compile error with gcc 7.4.0

### ISSUE THREAD

**Issue by antoniovilarinholopes** [marian-nmt/marian#275]
While trying to compile with gcc 7.4.0 I had a compiling error here regarding fallthrough: https://github.com/marian-nmt/marian/blob/master/src/tensors/cpu/sharp/avx_gemm.cpp#L471

Is the switch case supposed to fallthrough or to break after each label? (related issue #268)

**Comment by snukky** [comment]
Seems it has been fixed with https://github.com/marian-nmt/marian-dev/pull/434
