### ISSUE TITLE
Install failed:   cannot find -lpthreads

### ISSUE THREAD

**Issue by zrlhk** [marian-nmt/marian#277]
[ 49%] Building CXX object src/3rd_party/yaml-cpp/CMakeFiles/libyaml-cpp.dir/yaml-node.cpp.o
[ 49%] Built target pathie-cpp
[ 49%] Built target SQLiteCpp
[ 49%] Built target libyaml-cpp
Scanning dependencies of target marian_cuda
[ 49%] Linking CXX static library libmarian_cuda.a
[ 49%] Built target marian_cuda
make: *** [all] Error 2

and the error log:

/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_02543.dir/link.txt --verbose=1
/opt/rh/devtoolset-7/root/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_02543.dir/CheckFunctionExists.c.o  -o cmTC_02543 -lpthreads 
/opt/rh/devtoolset-7/root/usr/libexec/gcc/x86_64-redhat-linux/7/ld: **cannot find -lpthreads**
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_02543] Error 1 
gmake[1]: Leaving directory `/home/marian/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_02543/fast] Error 2 

I use centos7:

gcc 7.3.1    (with yum install)
cmake 3.14.5   (with source compie)
cuda 10.1
boost 1.70 (with source)

**Comment by zrlhk** [comment]
stuck here speed me two days.
get nothing.
f k

**Comment by zrlhk** [comment]
nvcc  nccl boost openlabs
and many ENV setting
there are so many depence...
the document for marian like SHIT

**Comment by emjotde** [comment]
You must be popular with that attitude.
