### ISSUE TITLE
Add regression tests

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#28]
As said in issue #27. Too many broken things are committed to master without checking.

**Comment by hieuhoang** [comment]
@ugermann ?

**Comment by tomekd** [comment]
It's partly done. Finally we use uedin Jenkins as a CI. I added 3 tests to amunmt-regression-tests repository. They tests the basic configs on cpu/gpu. I have to add tests with filtering, n-best lists, no-bpe. If you have any idea what can be tested, write me here.

**Comment by tomekd** [comment]
Tests run every night at midnight.
