### ISSUE TITLE
install marain-dev meet error when excute "make -j16“

### ISSUE THREAD

**Issue by zll0000** [marian-nmt/marian#280]
validator.cpp:(.text._ZN6marian2io16OutputFileStreamC2ERNS0_13TemporaryFileE[_ZN6marian2io16OutputFileStreamC5ERNS0_13TemporaryFileE]+0x3b): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(int, boost::iostreams::file_descriptor_flags)'
validator.cpp:(.text._ZN6marian2io16OutputFileStreamC2ERNS0_13TemporaryFileE[_ZN6marian2io16OutputFileStreamC5ERNS0_13TemporaryFileE]+0xf4): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
validator.cpp:(.text._ZN6marian2io16OutputFileStreamC2ERNS0_13TemporaryFileE[_ZN6marian2io16OutputFileStreamC5ERNS0_13TemporaryFileE]+0x166): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'
validator.cpp:(.text._ZN6marian2io16OutputFileStreamC2ERNS0_13TemporaryFileE[_ZN6marian2io16OutputFileStreamC5ERNS0_13TemporaryFileE]+0x17c): undefined reference to `boost::iostreams::file_descriptor_sink::file_descriptor_sink(boost::iostreams::file_descriptor_sink const&)'

**Comment by snukky** [comment]
Closing due to lack of information, and it's for an old version of Marian.
