### ISSUE TITLE
What should I do if I want to train a model with transformer encoder and sru decoder?

### ISSUE THREAD

**Issue by MichaelZhouwang** [marian-nmt/marian#283]
Hi,
I want to train a model with transformer encoder and sru decoder? I notice that I am able to set --transformer-decoder-autoreg to rnn. However, how can I set the decoder type to be sru? The decoder-cell option seems to be in the s2s type, will it works if I set it to be sru with training model type as transformer? Thanks!

**Comment by emjotde** [comment]
Hi,
Yes. that will work. However, what exactly do you mean by a SRU decoder. The current setting will keep a structure that is similar to a transformer model with multi-head target-source attention and filter layers in each block. The SRU will replace only the self-attention layer in the decoder, the rest of the block remains as before.

**Comment by MichaelZhouwang** [comment]
Hi,
Thanks for your response. I would like to use the transformer encoder to provide source side information for the decoder. For the decoder I would like it to be the same in the traditional seq2seq setting with a single layer SRU cell (hopefully it would be faster than transformer decoder). I have set the decoder-depth to be 1. Will the decoder performs like a normal SRU which attends to the transformer encoder outputs when generating target tokens autoregressively and updates its cell/hidden states?

**Comment by emjotde** [comment]
Ah, we actually have a `--model transformer_s2s`, that one should be exactly what you want. `--dec-cell sru` should work here. It will be a variant of the conditional RNN cell from Nematus. Here it puts the attention mechanism between two stacked RNN cells. `--dec-cell gru` gives you quite exactly the Nematus implemenations, changing it to SRU is probably the closest to what you want. I have not tested this for a while.

**Comment by MichaelZhouwang** [comment]
Thanks. It seems to work fine. However, I notice that when changing the model type from transformer to transformer_s2s, the training speed degrades a lot. Is that normal? (perhaps it is because the transformer decoder is training in a non-autoregressive fashion while sru is autoregressive? but I see in the paper of marian that a shallow rnn trains faster than transformer in terms of word/s..)

**Comment by emjotde** [comment]
I would say "yes" to your hypothesis on the non-autoregressive vs. autoregressive speed. Is the speed difference for one decoder layer? That would not be surprising. In the paper it's a 6 layer transformer model vs. a shallow 2-layer-ish RNN.

**Comment by MichaelZhouwang** [comment]
Ah yes. That makes sense. Thanks a lot for your help!

**Comment by emjotde** [comment]
Ah, there is also the `--dim-rnn N` parameter you may want to set. The default is 1024 while the transformer models look at the embedding size to determine model size.

**Comment by MichaelZhouwang** [comment]
I saw that --transformer-dim-aan is by default to be 2048 and the --dim-rnn is 1024, which causes an error. So I have changed the --transformer-dim-aan to 1024 to match the dimension for the SRU. Now It works and training seems to be fine. Thanks!

**Comment by emjotde** [comment]
Hm... with transformer_s2s there should be no AAN anywhere so that would be weird error.

**Comment by MichaelZhouwang** [comment]
So it could be the problem of FFN? I changed them all. So in marian if I set an option that does not belong to the model type (e.g. dec-cell for transformer), will this option be automatically ignored?

**Comment by emjotde** [comment]
Yes, everything is evaluated at runtime. So if a layer is not in the execution path the error has no way to fire. For transformer_s2s the AAN-related options should have no effect.

**Comment by MichaelZhouwang** [comment]
Thanks!
