### ISSUE TITLE
compiling under ubuntu 16.04 with openblas fails

### ISSUE THREAD

**Issue by jlquinn** [marian-nmt/marian#285]
On Ubuntu 16.04, the version of cmake is 3.5.1.  If MKL is not installed, cmake tries to fall back to OpenBLAS, but fails because the FindBLAS module doesn't understand OpenBLAS.  If I clone the relevant files into the cmake dir and hack in openblas, the build succeeds.

CMake doesn't add support for finding OpenBLAS until 3.6.

**Comment by emjotde** [comment]
Hi,
I would discourage using OpenBLAS though, I find MKL to be much faster, unless something has changed recently.

**Comment by snukky** [comment]
We now provide `cmake/FindCBLAS` in the repo, which I hope solves this issue. Closing.
