### ISSUE TITLE
Using pre-trained BERT/ELMO model?

### ISSUE THREAD

**Issue by RikVN** [marian-nmt/marian#287]
Hi,

is there any way I can use a pretrained BERT/ELMO model to initialize the vectors during encoding? I work with small datasets (semantic parsing), so these initial representations can increase the scores by a lot.

Thanks in advance for answering.

**Comment by emjotde** [comment]
We have some experimental code in development branches that can convert the official Google BERT models to something readable. Currently though I would not dare to call that usable.

**Comment by RikVN** [comment]
Thanks, I'll keep an eye on that!
