### ISSUE TITLE
Training cost gets nan after a few thousand steps/batches

### ISSUE THREAD

**Issue by greentoonz** [marian-nmt/marian#288]
Hi,

We are trying to train transformer with a large corpus of over 200m sentence pairs. The GPU server has eight 32G v100 cards. CUDA is v10.1. We used the latest cmake (3.15.2) to compile marian.

However, the training cost goes up to nan within one epoch (often less than half epoch). The cost starts at around 10 and keeps reducing for a while, then begins climbing until nan appears. And the dev output becomes gibberish.

Here are some paramters for the training:
segments: just over 200M
workspace: 30000
devices: 8 cards 32G each
transformer (default settings)
emb-dim: 512
max-length: 100
vocab-size: 50000
min-batch-fit: true
adam with 0.9 0.98 1e-09
learning rate: 0.001
lr-warmup: 91000 (equivalent to one epoch)
lr-decay-inv-sqrt: 91000
clip-norm: 5

We have tried different sets of (lr, warmup, decay), but to no avail. Any direction to solve the problem is much appreciated.

Thanks,
Guchun

**Comment by lkfo415579** [comment]
your lr-warmup is too large. normally it will be 10000 or 16000.

**Comment by snukky** [comment]
What exactly do you mean by default settings for a transformer, could you post all parameters you set? Which Marian version is it?

**Comment by greentoonz** [comment]
@lkfo415579 Thanks. We actually have found the stable setting, where lr=0.0003 and warmup=35000.

@snukky Sorry, I should have been more clear. It's the transformer base setting. The version is "Marian v1.7.6 1d4ba73 2019-05-11 17:16:31 +0100".

Thanks.
