### ISSUE TITLE
Run two marian-server in only one GPU at the same time

### ISSUE THREAD

**Issue by ttwelve12** [marian-nmt/marian#291]
Hi everyone~
Marian is fast in decoding. When i run a marian-server in GPU by jMeter, i find it only use 40% GPU-Util and translate each sentence in 200~300ms.
![image](https://user-images.githubusercontent.com/25807749/65023856-4cce7080-d966-11e9-941f-57235f0ab376.png)
![image](https://user-images.githubusercontent.com/25807749/65024716-f82bf500-d967-11e9-8d86-f05123a10f02.png)

 I want to make full use of GPU so i run another marian-server in the same GPU. I find GPU-Util is still not full, but translation speed for each sentence is slower, 600~700ms.
![image](https://user-images.githubusercontent.com/25807749/65025068-9750ec80-d968-11e9-81c3-f5b72744d095.png)
![image](https://user-images.githubusercontent.com/25807749/65025090-a33cae80-d968-11e9-9e72-2ee77b3e9cbe.png)
What caused such a big difference? Thank you everyone~

**Comment by lkfo415579** [comment]
it depends on mini-batch.
when mini-batch is getting larger the usage of gpu will be increased and avg decoding time will be lower.

**Comment by ttwelve12** [comment]
@lkfo415579 I think mini-batch is not the reason, because i use marian-server to translate sentences one by one. My doubt is that i want to make full use of GPU so i run two marian-server in the same GPU, but find the translation speed is lower. Thant you~

**Comment by lkfo415579** [comment]
GPU can only decode once at the same time.

**Comment by ttwelve12** [comment]
@lkfo415579 Thank you to solve my problem~
