### ISSUE TITLE
is gpu version shortlist possible?

### ISSUE THREAD

**Issue by david-pureal** [marian-nmt/marian#294]
I have successfully try the cpu version lexical shortlist, making the decoding 2 times faster.
According to the article 4.1, shortlist is only for cpu-bound accelaration. My question is how about the gpu version? Will marian implement it on schedule?
Thanks!

**Comment by snukky** [comment]
Yes, lexical shortlists should work for both CPU and GPU decoding. It just brings a smaller improvement on GPUs.

(The article mentioned in the question: https://www.aclweb.org/anthology/W18-2716.pdf)

**Comment by david-pureal** [comment]
> Yes, lexical shortlists should work for both CPU and GPU decoding. It just brings a smaller improvement on GPUs.
> 
> (The article mentioned in the question: https://www.aclweb.org/anthology/W18-2716.pdf)

Thanks for your reply. I have read the paper,

**Comment by snukky** [comment]
I have tried, but do not have exact numbers now.

**Comment by david-pureal** [comment]
cool, I have read the src code of cpu shortlist, could you give me some hints to implement the gpu version?

**Comment by snukky** [comment]
Lexical shortlists on GPUs have been available since its CPU version is available.
