### ISSUE TITLE
Wno-error=deprecated-copy

### ISSUE THREAD

**Issue by tarnh** [marian-nmt/marian#298]
https://github.com/marian-nmt/marian/issues/275 has been fixed, but currently I'm getting a ton of `-Werror=deprecated-copy` errors when compiling with gcc 9:
https://pastebin.com/NRdUM5k4

May you please let compile with `-Wno-error=deprecated-copy` ?

**Comment by snukky** [comment]
I think this is no longer the case in newer versions of Marian. Please feel free to re-open if the issue still exists.
