### ISSUE TITLE
How marian-server access is made

### ISSUE THREAD

**Issue by sdlmw** [marian-nmt/marian#299]
Hi everybody，

ws://localhost:{port}/translate，What is the access format for this request? GET or POST? What are the parameters?

thanks

**Comment by tomekd** [comment]
It's a [websocket](https://en.wikipedia.org/wiki/WebSocket) server not HTTP one. So there is not GET and POST and parameters.

**Comment by sdlmw** [comment]
thanks @tomekd .  I have one more question. What happens to words that the engine doesn't learn? Does the engine output the original word?

**Comment by snukky** [comment]
No, there is no automatic copying of unknown words. Subword segmentation with BPE or SentencePiece is a common approach to solve the issue with unks.
