### ISSUE TITLE
How much memory is needed to compile?

### ISSUE THREAD

**Issue by rococode** [marian-nmt/marian#311]
I'm getting a 

`virtual memory exhausted: Cannot allocate memory`

error when I try to compile (on the `make -j` step).

I'm running this on an AWS EC2 `g4dn.xlarge` machine which has 16GB RAM. Do I need more than that just to compile? When I run the make I indeed see `free` show memory usage steadily going up until the error appears and the build crashes.

**Comment by emjotde** [comment]
Hi,
with `make -j` you run many build processes, they quickly add up. Try `make -j 8` or whatever works.

**Comment by hieuhoang** [comment]
We should changed the docs should to -j 4.

**Comment by emjotde** [comment]
I think this is oddly specific to AWS machines. I noticed `make` gets the number of CPUs/threads wrong there (because they are VMs?) and dispatches a much larger amount of processes than available threads.

**Comment by hieuhoang** [comment]
Without the number, make will run in parallel without limit which is always
a bad idea. Best not encourage people to do that

**Comment by emjotde** [comment]
At least a comment about the potential memory issue is a good idea. Usually people compile on larger machines if they have GPUs, though.

**Comment by rococode** [comment]
Thank you for the very quick responses! `make -j 8` worked successfully for me.
