### ISSUE TITLE
What is the update time for the next stable release?

### ISSUE THREAD

**Issue by mozatkey** [marian-nmt/marian#317]
we tested marian-dev, it has a better  performance,  thanks for the work.  But I can't use a non-release version in production, What is the update time for the next stable release?

**Comment by emjotde** [comment]
On it. Gimme a few hours.

**Comment by emjotde** [comment]
Version 1.9.0 released. Sorry for the long wait, and thank you for reminding me to finally do that.

**Comment by mozatkey** [comment]
Nice work! thks @emjotde

**Comment by emjotde** [comment]
BTW @mozatkey if you are using Marian in production, we will be happy to add your company logo with link to our website: https://marian-nmt.github.io/ (bottom)

If interested here's the corresponding github issue for logos: https://github.com/marian-nmt/marian/issues/230
