### ISSUE TITLE
Generating random outputs when beam size is increased to 2 or more

### ISSUE THREAD

**Issue by shubham-IISc** [marian-nmt/marian#318]
Hi, 
I am using the following command:
${marian_build}/marian-decoder \
        --devices 4 5 6 \
        --workspace $workspace \
        --seed 11 \
        --log ${log_folder}/${model_id}.eval \
        --quiet-translation \
        --models ${model_folder}/${model_id}.npz.best-cross-entropy.npz \
        \
        --input $predict_input \
        --vocabs $vocabs \
        --beam-size $ensemble_beam_size \
        --mini-batch 512 \
        --n-best \
> $output

Any idea about what could be going wrong as its just an argument. 
Thanks,
Shubham

**Comment by emjotde** [comment]
You would need to tell us what the actual problem is.

**Comment by emjotde** [comment]
Closing, no answer.
