### ISSUE TITLE
Does marian supports "Dynamic cost scaling for mixed precision training"?

### ISSUE THREAD

**Issue by huangjq0617** [marian-nmt/marian#322]
I found the "--cost-scaling" option in [src/common/config_parser.cpp](https://github.com/marian-nmt/marian/blob/3c7a88f4e974d90a91c11a0ff804f7a494b81937/src/common/config_parser.cpp#L498), but I can't find the corresponding implement for this.
So, does marian supports "Dynamic cost scaling for mixed precision training"? If not, how does it handle the nan problem of loss when optimization use float16?
Thank you!

**Comment by emjotde** [comment]
Fp16 works for decoding right now. I am still working on training.

**Comment by emjotde** [comment]
Closing this as we plan to make fp16 training available in 1.10.
