### ISSUE TITLE
Padding batched inputs

### ISSUE THREAD

**Issue by sshleifer** [marian-nmt/marian#327]
Do `marian_decoder` or `marian_train` use padding to make batches on inputs a fixed shape? 
If so, which token/id is used to indicate padding?

**Comment by frankseide** [comment]
We use padding, but it is not represented by a specific value but rather a mask.

**Comment by emjotde** [comment]
The masking is generally able to take care that padding symbols do not get propagated. We do however fill the batch with the same id as the </s> (end of sentence) symbol which is vocabulary dependent. </s> does not receive gradients during training in its padding positions.

**Comment by sshleifer** [comment]
Makes sense, thanks!
