### ISSUE TITLE
Documentation for cpu translation

### ISSUE THREAD

**Issue by Bachstelze** [marian-nmt/marian#328]
The current documentation declares different states for the cpu translation.
> https://marian-nmt.github.io/docs/#translation Currently, marian-decoder supports only translation on GPUs. A CPU version of Marian is planned.

> https://marian-nmt.github.io/docs/cmd/ marian-decoder: CPU and GPU translation using NMT models trained with Marian.

Or do I confuse it with amun?

**Comment by emjotde** [comment]
Oh, interesting how that slipped through. We had CPU translation (and training and scoring) in Marian since early 2018. Thanks for pointing this out. Just use `--cpu-threads N` to parallelize over input batches.

**Comment by Bachstelze** [comment]
OK, thanks for the quick response.

**Comment by snukky** [comment]
Fixed. Thanks!
