### ISSUE TITLE
comparable model and training to nematus

### ISSUE THREAD

**Issue by anrizal** [marian-nmt/marian#331]
Support Request
I am trying to replicate results from a paper that made using nematus (for training and decoding). 
Reading the documentation https://marian-nmt.github.io/docs/, I am a bit unsure which type should I choose for training from scratch.

Should I choose s2s, nematus, amun or nematus2 

Thank you

**Comment by snukky** [comment]
It depends which model from Nematus you would like to compare with. In Marian, an RNN model is called 's2s' and a transformer model is simply 'transformer'. Please see our https://github.com/marian-nmt/marian-examples for examples how to train both types of models with Marian from scratch.

**Comment by anrizal** [comment]
Alright, thank you
