### ISSUE TITLE
How to set the epoch parameter？

### ISSUE THREAD

**Issue by MIC10086** [marian-nmt/marian#338]
Hello, I can not find a parameter about the training epochs, could you tell me about that?

**Comment by emjotde** [comment]
Hi,
Do you mean a parameter that stops training after a certain amount of epochs? That would be for instance `--after-epochs 10` for 10 epochs.

**Comment by MIC10086** [comment]
Ok,
Thank you very much!

**Comment by MIC10086** [comment]
> Hi,
> Do you mean a parameter that stops training after a certain amount of epochs? That would be for instance `--after-epochs 10` for 10 epochs.

Ok,
thank you very much!

**Comment by snukky** [comment]
The question has been answered. Closing.
