### ISSUE TITLE
How to translate using Python

### ISSUE THREAD

**Issue by q2044757581** [marian-nmt/marian#346]
I have trained a model but i want to use Python to write an interaction API
Can you give an example?

**Comment by snukky** [comment]
AFAIK there is no official Python API. Huggingface has one, but you would need to look for examples there. You can also compile and use marian-server, which is a simple web server and the demo client we provide is in Python (https://marian-nmt.github.io/docs/#web-server).

**Comment by q2044757581** [comment]
ok, tks
