### ISSUE TITLE
marian-server not in /build

### ISSUE THREAD

**Issue by q2044757581** [marian-nmt/marian#347]
why i can't see **marian-server** in the path **/build**,  but marian/marian-conv/marian-decoder/marian-scorer/marian-vocab are in this path

**Comment by snukky** [comment]
marian-server is compiled only if `COMPILE_SERVER` is added to the cmake command, for example `cmake .. -DCOMPILE_SERVER=on`.

**Comment by q2044757581** [comment]
ok, tks
