### ISSUE TITLE
Translation of Arabic to English is not working

### ISSUE THREAD

**Issue by makamkumar** [marian-nmt/marian#355]
### Bug description
Please add a clear and concise description of the bug, including observed and if possible expected behavior.

### How to reproduce
Describe steps or include command to reproduce the behavior.

### Context
* Marian version: Paste the output of `--version` here
* CMake command: Type the cmake command you used and attach the output of `--build-info all`
* Log file: Attach your training/decoding logs

Add any other information about the problem here.

**Comment by makamkumar** [comment]
I tried installing the service and tried normal left to right languages they worked perfectly fine.
However the right to left languages none worked.
e.g. How to get a translation of a passage from Arabic to say English or Spanish?
I tried but the output is not coming out. Is there something I am missing out?
Thanks in Advance otherwise a beautiful piece of work

**Comment by emjotde** [comment]
I am sorry, but what service are we talking about? And what models?

**Comment by adjouama** [comment]
Well, very difficult to understand your issue. 
Myself I trained English-Arabic models and it works just fine. 

Did you train your model using parallel corpora English-Arabic or Spanish-Arabic ?

**Comment by makamkumar** [comment]
I am trying to try Marian in implementing Arabic to English translation. 
The model is downloaded from Huggingface https://huggingface.co/Helsinki-NLP/opus-mt-ar-en.
When I run the issue is the model is not recognised and says " Check if the Model is downloaded.
Please help as I am unable to resolve the issue. Moreover, Other models are working fine hence only issue is with Arabic. Even other similiar languages are not working

**Comment by snukky** [comment]
OPUS or Huggingface teams will be better contacts to help you to solve this issue. We have not trained those models and not implemented the Huggingface interface, so it is hard for us to debug that.

**Comment by makamkumar** [comment]
However other models downloaded work
Moreover I tried other methods with pipeline they work well only the service is not working so the issues must with code here

**Comment by makamkumar** [comment]
However other models downloaded work
Moreover I tried other methods with pipeline they work well only the service is not working so the issues must with code here
Any pretrained models for Arabic ?

**Comment by emjotde** [comment]
As @snukky said, we are not really associated with these models.

**Comment by makamkumar** [comment]
Any pre-trained models available for Arabic to English to test the pipeline for confidence?
