### ISSUE TITLE
Sentencepiece Checkout fails in 1.9.0

### ISSUE THREAD

**Issue by johko** [marian-nmt/marian#358]
### Bug description
In Marian 1.9.0 when running `cmake $MARIANPATH -DUSE_SENTENCEPIECE=on -DCOMPILE_CPU=on -DCOMPILE_SERVER=ON -DCOMPILE_CUDA=off && make`
when getting to the steps where all the 3rdParty repos get checked out, the process fails when getting to Sentencepiece with these error messages:
`fatal: reference is not a tree: 1d33bb67c3b6b2a51d3c9ffd55f37725801da39d
Unable to checkout '1d33bb67c3b6b2a51d3c9ffd55f37725801da39d' in submodule path 'src/3rd_party/sentencepiece'`

### How to reproduce
Run cmake with the given config and run make right after

### Context
* Marian version: 1.9.0
* CMake command: cmake $MARIANPATH -DUSE_SENTENCEPIECE=on -DCOMPILE_CPU=on -DCOMPILE_SERVER=ON -DCOMPILE_CUDA=off && make
* Log file: 
cmake $MARIANPATH -DUSE_SENTENCEPIECE=on -DCOMPILE_CPU=on -DCOMPILE_SERVER=ON -DCOMPILE_CUDA=off && make
 ---> Running in 5206aa129f7c
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Project name: marian
-- Project version: v1.9.0+3c7a88f4
Submodule 'examples' (https://github.com/marian-nmt/marian-examples) registered for path 'examples'
Submodule 'regression-tests' (https://github.com/marian-nmt/marian-regression-tests) registered for path 'regression-tests'
Submodule 'src/3rd_party/fbgemm' (https://github.com/marian-nmt/FBGEMM) registered for path 'src/3rd_party/fbgemm'
Submodule 'src/3rd_party/nccl' (https://github.com/marian-nmt/nccl) registered for path 'src/3rd_party/nccl'
Submodule 'src/3rd_party/sentencepiece' (https://github.com/marian-nmt/sentencepiece) registered for path 'src/3rd_party/sentencepiece'
Cloning into '/marian/examples'...
Cloning into '/marian/regression-tests'...
Cloning into '/marian/src/3rd_party/fbgemm'...
Cloning into '/marian/src/3rd_party/nccl'...
Cloning into '/marian/src/3rd_party/sentencepiece'...
Submodule path 'examples': checked out 'c19b7814d71febf1053bd93af6ac314b46204092'
Submodule path 'regression-tests': checked out '6a08849b23f6c14eefbe12f4eb73dc638b962587'
Submodule path 'src/3rd_party/fbgemm': checked out '84e66a976046180187724aff60a236c5378fde7c'
Submodule 'third_party/asmjit' (https://github.com/asmjit/asmjit.git) registered for path 'src/3rd_party/fbgemm/third_party/asmjit'
Submodule 'third_party/cpuinfo' (https://github.com/pytorch/cpuinfo) registered for path 'src/3rd_party/fbgemm/third_party/cpuinfo'
Submodule 'third_party/googletest' (https://github.com/google/googletest) registered for path 'src/3rd_party/fbgemm/third_party/googletest'
Cloning into '/marian/src/3rd_party/fbgemm/third_party/asmjit'...
Cloning into '/marian/src/3rd_party/fbgemm/third_party/cpuinfo'...
Cloning into '/marian/src/3rd_party/fbgemm/third_party/googletest'...
Submodule path 'src/3rd_party/fbgemm/third_party/asmjit': checked out '4da474ac9aa2689e88d5e40a2f37628f302d7e3c'
Submodule path 'src/3rd_party/fbgemm/third_party/cpuinfo': checked out 'd5e37adf1406cf899d7d9ec1d317c47506ccb970'
Submodule path 'src/3rd_party/fbgemm/third_party/googletest': checked out '0fc5466dbb9e623029b1ada539717d10bd45e99e'
Submodule path 'src/3rd_party/nccl': checked out 'b56650c7f59b8cd40d18809784a6d6be38ef8acb'
**fatal: reference is not a tree: 1d33bb67c3b6b2a51d3c9ffd55f37725801da39d
Unable to checkout '1d33bb67c3b6b2a51d3c9ffd55f37725801da39d' in submodule path 'src/3rd_party/sentencepiece'**
CMake Warning at CMakeLists.txt:55 (message):
  CMAKE_BUILD_TYPE not set; setting to Release
-- Checking support for CPU intrinsics
-- SSE2 support found
-- SSE3 support found
-- SSE4.1 support found
-- SSE4.2 support found
-- AVX support found
-- AVX2 support found
-- AVX512 support found
CMake Warning at CMakeLists.txt:293 (message):
  COMPILE_CUDA=off : Building only CPU version
-- Found Tcmalloc: /usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so
-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_INCLUDE_DIRS MKL_INTERFACE_LIBRARY MKL_SEQUENTIAL_LAYER_LIBRARY MKL_CORE_LIBRARY) 
-- Looking for sgemm_
-- Looking for sgemm_ - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
-- Checking for [openblas]
-- Checking for [openblas] -- includes found
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- Checking for [openblas] -- libraries found
-- CBLAS library found: /usr/lib/x86_64-linux-gnu/libopenblas.so
-- cblas.h include directory: /usr/include/x86_64-linux-gnu
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1") 
-- Found OpenSSL
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
CMake Error at src/3rd_party/CMakeLists.txt:60 (add_subdirectory):
  The source directory
    /marian/src/3rd_party/sentencepiece
  does not contain a CMak_

Add any other information about the problem here.

**Comment by emjotde** [comment]
Sorry. That was my mistake. Try now?

**Comment by johko** [comment]
Running great now. Thank you
