### ISSUE TITLE
Marian message on training - zmq_msg_recv(#0): timeout

### ISSUE THREAD

**Issue by pinheiroo27** [marian-nmt/marian#373]
I'm receiving this messages on the training:

get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout
get_container_pid(3209823): zmq_msg_recv(#0): timeout

I think it's a message from the ZeroMQ library, but what does it mean?

I'm running Marian inside a docker using Cuda 11.3.0

**Comment by emjotde** [comment]
Hi,
No idea what that is. Also what's the ZeroMQ library and why would that affect us?
