### ISSUE TITLE
Error "terminate called after throwing an instance of 'YAML::InvalidNode'" raised in marian-decoder 1.11.0

### ISSUE THREAD

**Issue by TingxunShi** [marian-nmt/marian#391]
### Bug description

Run marian-decoder and pass in a model trained by 1.10.0, it raises the following error:

```text
> head text | marian-1.11.0/build/marian-decoder --models model.npz.best-bleu.npz --vocabs vocab.src.yaml vocab.tgt.yaml --normalize 0.4 

terminate called after throwing an instance of 'YAML::InvalidNode'
  what():  invalid node; this may result from using a map iterator as a sequence iterator, or vice-versa
Aborted
```

The same command succeeded in 1.10.0.

### Context
* Marian version: Paste the output of `--version` here
v1.11.0 f00d0621 2022-02-08 08:39:24 -0800

* CMake command: Type the cmake command you used and attach the output of `--build-info all`
```bash
cmake .. -DUSE_SENTENCEPIECE=off \
    -DCOMPILE_CPU=off \
    -DUSE_CUDNN=on \
    -DUSE_ONNX=off \
    -DPROTOBUF_LIBRARY=/usr/local/lib/libprotobuf.so \
    -DPROTOBUF_INCLUDE_DIR=/usr/local/include/google/protobuf \
    -DPROTOBUF_PROTOC_EXECUTABLE=/usr/local/bin/protoc
```

* Log file: Attach your training/decoding logs

Add any other information about the problem here.

**Comment by ZJaume** [comment]
Faced the same issue. It's solved in marian dev with [this](https://github.com/marian-nmt/marian-dev/commit/7d654603bf6abaa6a0e474f1bb7551cddfcb4c67) commit. Also compiling with -DCOMPILE_CPU=on avoids the issue.

**Comment by TingxunShi** [comment]
> Faced the same issue. It's solved in marian dev with [this](https://github.com/marian-nmt/marian-dev/commit/7d654603bf6abaa6a0e474f1bb7551cddfcb4c67) commit. Also compiling with -DCOMPILE_CPU=on avoids the issue.

Thanks, it works!
