### ISSUE TITLE
running marian-server in secure fashion (wss)

### ISSUE THREAD

**Issue by AMBacelar** [marian-nmt/marian#400]
### Feature description
Not sure if I am missing something obvious or not, but there does not appear to be a secure web socket implementation of marian-server.
I can see inside /src/command/marian_server.cpp that is is the base web server being set up.

Is there an obvious reason that I'm missing for why this is the case?

### Example
Add a usage examples for the new feature, e.g. a command line.
something like: `marian-server-secure -p 443 -cert=/path/to/cert/file -key=/path/to/key/file` is what I'd be looking for.

maybe it can be the same file, and it should create a secure server if the two relevant values are passed in, and just a regular one otherwise.

**Comment by snukky** [comment]
`marian-server` was just a demo to show how to build a server-based Marian app. I don't think we currently have plans to extend it, but ofc contributions are very welcome!
