### ISSUE TITLE
Clean-up code, remove tabs

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#43]
There are loads of tabs in the code. Let's get rid of those.

**Comment by hieuhoang** [comment]
astyle --style=k&r -s2 
?

**Comment by emjotde** [comment]
Context?

**Comment by hieuhoang** [comment]
run it with the daily regression test. Allow people to run astyle themselves to get their code consistent. 

there's minor details - different versions of astyle produce slightly different format. We should settle on a specific version & exact args

**Comment by emjotde** [comment]
Looks good actually.

**Comment by hieuhoang** [comment]
before we do it, we should merge the different branches. It's a nightmare to do it afterwards

**Comment by tomekd** [comment]
We can also add pre-commit checking:
https://github.com/springlobby/springlobby/blob/master/git-hooks/pre-commit

**Comment by hieuhoang** [comment]
commit hooks aren't mandatory. How will you enforce it, especially on git pull requests? You're gonna go blue in the face getting crossed with people about tabs

**Comment by hieuhoang** [comment]
it's a good idea though to suggest to people to run reformat as a pre-commit hook. Rather than just checking and refusing to commit

**Comment by tomekd** [comment]
that's ok. I can prepare a such script.

**Comment by emjotde** [comment]
@snukky Since we have a formatter now, I guess this can be closed?
