### ISSUE TITLE
--n-best list fails with --mini-batch > 1

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#55]
Specifying --n-best with mini-batch sizes larger than 1 fails with a cuda error in nth_element.

**Comment by hieuhoang** [comment]
it's prob dependent on model 'cos it works for me with mini-batch 22

**Comment by emjotde** [comment]
OK, I will make the model available. That's even weirder actually. N-best list extraction should be completely independent from GPU calculations.

**Comment by hieuhoang** [comment]
I think the segfaults have been fixed. Please git pull and try again. I'll close this issue if there are no further reports
