### ISSUE TITLE
Review web site and complain here

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#56]
Hi assignees, 
Would be cool if you guys could take a look at the website (https://amunmt.github.io/) and complain here if something is weird or wrong.

**Comment by ugermann** [comment]
I'd add "Nvidia" to all the GPU model names in the comparison charts.

**Comment by tomekd** [comment]
Some ideas:
 * on the main page: "Some features" -> "Main features"
 * lack who is in charge of amunmt (contributors?, uni?)
 * maybe it's worth to mention CUDA (which is not pure C++).

**Comment by hieuhoang** [comment]
I think there should be explicit mention of Marian. I know it was my suggestion to call it amun 'cos it has a lot more followers, but the assumption was that the 2 would be merged. Until they are merged, it's a bit confusing to run amun and only get the inference and not the training

**Comment by emjotde** [comment]
@hieuhoang They are merged in the marian-integration branch. This will soon be merged into master.

**Comment by hieuhoang** [comment]
ah ok. The compilation is seamless which is good. Maybe make the explanation about Marian more prominent, or ignore me unless there are questions from newbies

Other comments:
  1. Ubuntu 16.04 cmake - no need to '(due to CUDA related bugs in earlier versions)' since that's the version that comes with it,
  2. Ubuntu 14.04 cmake - maybe say '(needs to be installed separately from source)'. Current comment sounds like an excuse rather than being helpful & direct.
  3. CPU version - its important to say what they'll be missing by explicitly qualifying that CPU-version is inference only.
  4.  'CPU version **should** be a lot more forgiving' - we don't know that for sure. It may send people who can't get it to compile to try CPU-only and will waste their time if it's not true
  5. Can we make the footer info in the amunmt@googlegroups.com emails English? It's Polish @ the mo. Is this the group I set up, maybe I'll do it myself
  6. Fast and deployment-ready -> Fast, deployment-ready. Not actually sure what deployment ready means

**Comment by emjotde** [comment]
Should we do a contributors page?

**Comment by emjotde** [comment]
@hieuhoang Is the google group still Polish for you? I changed the group language, but I see it still in Polish, but that might be location-based?

**Comment by fiqas** [comment]
The site looks good. Contributors page is a good idea, should anyone be
interested in hitting you guys up personally.



2017-04-05 8:04 GMT+01:00 Marcin Junczys-Dowmunt <notifications@github.com>:

**Comment by tomekd** [comment]
suggestion: on publications site: (for me) much readable would be format: title [pdf|bib], e.g.

*Is Neural Machine Translation Ready for Deployment? A Case Study on 30 Translation Directions*  [[pdf](http://workshop2016.iwslt.org/downloads/IWSLT_2016_paper_4.pdf)|[bib](iwslt.bib)]

Esp. when more papers will appear.

**Comment by emjotde** [comment]
BTW, I am using the :+1:  button as way to check off which points I have fixed. It's not a means of approval :)

**Comment by emjotde** [comment]
@hieuhoang Concerning the CPU version and foregiveness. Actually it is tested. I have tried it on multiple distributions, including older Redhat. CPU version is usually quite painless.

**Comment by alvations** [comment]
@emjotde should just create a label named `fixed` and label it =)

**Comment by hieuhoang** [comment]
so someone's gonna announce Amun's arrival somewhere? moses mailing list, mt list etc, corpora list?

**Comment by kpu** [comment]
Misspelled "ommit" -> "omit" https://amunmt.github.io/usecases/training/

**Comment by kpu** [comment]
No documentation on how to change model or use Marian's computation graph?

**Comment by kpu** [comment]
Upgrade source code references to links: https://amunmt.github.io/usecases/training/

**Comment by kpu** [comment]
Rename "documentation" to command-line reference: https://amunmt.github.io/docs/ .

**Comment by kpu** [comment]
https://amunmt.github.io/quickstart/ should include a git clone command before the build instructions.

**Comment by kpu** [comment]
Make one page with commands I can run from download to training and inference.  Copy-paste. 
1. sudo apt-get install ...
2. git clone ...
3. Compiling
4. Download data starting from raw parallel text.
5. Preprocess text.
6. Run training. 
7. Run translation.
User should be able to blindly copy-paste commands and expect it to work.  Don't implicitly change directories between commands like https://amunmt.github.io/quickstart/ does after building.  
Good initial user experience is key to adoption.

**Comment by emjotde** [comment]
@hieuhoang Yes, just want to have the webpage set up as well as possible. Once I am happy with that we can announce it.

**Comment by tomekd** [comment]
+1 for @kpu last suggestion.  Something similar to "training baseline" at moses page.

**Comment by emjotde** [comment]
Anyone want to turn https://amunmt.github.io/usecases/training/ into a more explanatory example?

**Comment by phikoehn** [comment]
Hi,

I wrote some code notes here:
http://www.statmt.org/jhu/?n=NMTWinterSchool.AmuNMT

I wonder, if these would be worth putting on the site.

-phi

**Comment by emjotde** [comment]
@phikoehn Oh yes, I saw this a while ago and was impressed. I would not add this now for the first launch, but definitly something to add later. I will create an issue for that in the site's repo.

**Comment by hieuhoang** [comment]
+1 for @kpu docs on computation graph

**Comment by emjotde** [comment]
@hieuhoang, TBH, I do not want people to mess around with that yet.

**Comment by kpu** [comment]
Who is the target audience here?  If it's MT researchers, I don't see how you can launch without the ability to edit the graph.

**Comment by emjotde** [comment]
Let's rephrase that. I do not want to document that yet. I was planning to that with time. And even in the Edinburgh team, how many people are actively modifying Nematus, three?
