### ISSUE TITLE
Add rescorer to amunmt

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#57]
For future reference, add a n-best list rescorer to amunmt

**Comment by tomekd** [comment]
It's almost done in the mosesplugin branch. The only thing to do is creating an app, which loads God and files.

**Comment by emjotde** [comment]
We would also need one using marian architecture. It's not too urgent, just a reminder for myself.

**Comment by emjotde** [comment]
Actually we should only use marian, as it can handle amun models too.

**Comment by tomekd** [comment]
The only thing I need is a function, which works as  ``scorer.SetSourceSentence()`` and ``scorer.Decode()``. 
See``NMT::RescoreNBestList`` at https://github.com/amunmt/amunmt/blob/plugin/src/plugin/nmt.cpp#L241

**Comment by emjotde** [comment]
Addressed by #80
