### ISSUE TITLE
Toolkit name?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#61]
Hi contributors,
The Edinburgh people are raising concerns with the name of the toolkit, as the the prefix AMU is strongly tied to my University which makes it difficult for Edinburgh to brand or get funding for further developments. This is a valid point. 

On the other hand we have a toolkit which is by now quite recognizable as it has been mentioned in a couple of papers. Luckily there has been no paper with the name in the title yet, so I guess we would be good to change it. 

One suggestion is to use Marian as the name for the whole toolkit. I am a little bit sceptical about that as it was more of a joke name which somehow stuck, but maybe I can be convinced.

Feel free to add comments.

**Comment by hieuhoang** [comment]
ah, that's a shame, didn't think of that. I don't mind what we call it

**Comment by alvations** [comment]
Sticking with the Pharoah -> Moses -> Joshua joke, errr `Elijah` or `Eliza`? As long as it won't be called the original name of `cdec` =)

**Comment by emjotde** [comment]
"Judas" was mentioned, but I am not brave enough for that.

**Comment by alvations** [comment]
Inspiration: https://en.wikipedia.org/wiki/List_of_major_biblical_figures

Perhaps a female name? To get more diversity?

**Comment by emjotde** [comment]
The woman are all named Mary. Which is again close to Marian.

**Comment by jgwinnup** [comment]
Glad I'm not the first to suggest continuing on the Biblical theme...

**Comment by alvations** [comment]
Oh but Marian is rather ambiguous  https://en.wikipedia.org/wiki/Marian , lol

**Comment by emjotde** [comment]
It's actually a male name in Polish. And that's where the name for the training toolkit came from. So, sort of a cop-out.

**Comment by phikoehn** [comment]
I kinda like Marian. It has a nice ring to it.

**Comment by alvations** [comment]
https://www.behindthename.com/name/marian-2

**Comment by emjotde** [comment]
For context https://en.wikipedia.org/wiki/Marian_Rejewski

Mathematician, first one to break the Enigma, born in the same city as me (Bydgoszcz), went to the same University (AMU in Poznan), I taught Math for a couple of weeks at his high school (again in Bydgoszcz). I think @tomekd actually went to that high school?

**Comment by lexibirch** [comment]
I like Marian. It is a simple name and the Polish connection is appropriate. It also makes me think of Leonard Cohen. It would be a shame to have to sing: so long Marian :)

**Comment by kpu** [comment]
I vote for Marian.  Wasn't the plan that adding decoding to Marian would subsume AmuNMT?

**Comment by emjotde** [comment]
Codewise, I didn't really think of a name. AmuNMT sounded more professional to me.

**Comment by emjotde** [comment]
Another problem I forgot about... I explicitly excluded the amunmt (orgname) repos amunmt and marian in my future Microsoft employee agreement. So we would be stuck with the orgname, but could switch to marian as a repo name for the toolkit.
