### ISSUE TITLE
Nematus trained model with the option "tie_decoder_embeddings" doesn't work correctly with AmuNMT

### ISSUE THREAD

**Issue by lczarne** [marian-nmt/marian#70]
I have a model trained with Nematus with the option "tie_decoder_embeddings" turned on. The real change it causes is the lack of the separately trained "ff_logit_W" matrix. When building the model in build_sampler() method in nmt.py Nematus copies "Wemb_dec", transposes it and saves it as the "ff_logit_W". 

AmuNMT doesn't support that so I manually copy and transpose "Wemb_dec" and save it as "ff_logit_W" with the Python code:
`np.savez(new_model_path,ff_logit_W=model['Wemb_dec'].T,**model)
`
Model prepared in that way works properly with the Nematus translation but unfortunately gives incorrect and meaningless output with the AmuNMT.

example for DE-EN model:

input:

> im Gegensatz zu Kanada sind die US @-@ Bundesstaaten für die Durchführung der Wahlen in den einzelnen Staaten verantwortlich .

Nematus translation output:

> unlike Canada , US states are responsible for the conduct of the elections in each of the States .

AmuNMT translation output:

> Kop@@ rigi@@ percent Con@@ approval tioning AAA tioning rent tioning rent tioning 29@@ interchange 438 interchange 438 438 438 tioning Delhi tioning Delhi tioning Delhi tioning supervise 438 tioning Delhi tioning Delhi tioning supervise 438 tioning Delhi tioning rent tioning supervise 438 tioning Delhi tioning supervise 438 tioning Delhi tioning rent tioning supervise 438 tioning Delhi tioning supervise 438 tioning Delhi tioning supervisek

**Comment by emjotde** [comment]
Just checking, are you sure Nematus is not just using the original matrix? Have you disabled the matrix ties in Nematus? What are the dimensions for your matrices?

**Comment by lczarne** [comment]
I tested it once again. In the first test I might turn on "tie_decoder_embeddings" in an insufficient way and it still proceeded in a normal way (and used the original matrix). Now I ensured the Nematus code uses the option and it turnes out the output is wrong. For example I presented above it gives:

`in to to to to to to to to to to to to to to to to to to to . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .`

So it means simply copying and transposing the matrix with:
`np.savez(new_model_path,ff_logit_W=model['Wemb_dec'].T,**model)
`
doesn't work well in both Nematus and AmuNMT and works differently in these two libraries. Still I don't know the way to use model with "tie_decoder_embeddings" in AmuNMT. I will further investigate different results in Nematus for manually copied matrix and default behavior.

**Comment by emjotde** [comment]
Sorry, cannot really help you there. I do not know exactly what Nematus is doing, and we do not support that feature in the moment. I can leave the issue open, but at the moment this is not high priority.

**Comment by lczarne** [comment]
Sorry for the confusion but there are many places in the code where this option can be set. I performed a lots of tests with different configurations to be sure. 

Copying and transposing "Wemb_dec" to "ff_logit_W" manually **works correct with Nematus**. 
When I turn off "tie_decoder_embeddings" it gives me correct output. When I won't do this step manually it gives me:

>  "KeyError: 'ff_logit_W'

**So the final conclusion is that Nematus translation works correct with this manual step performed and AmuNMT gives incorrect output.**

**Comment by lczarne** [comment]
Sure. I uploaded the model with files needed for sample translation at https://github.com/lczarne/nematus_amunmt_sample

**Comment by tomekd** [comment]
@lczarne,

good news. I have just implemented support for tie_embs. Please test it, and if it works, close the issue.

Best wishes,
Tomasz

**Comment by lczarne** [comment]
It works well now! Thanks! Closing the issue.
