### ISSUE TITLE
Minimum Risk Training

### ISSUE THREAD

**Issue by choltz95** [marian-nmt/marian#73]
Nematus supports Minimum Risk Tuning - is this something that might be explored in the future for amunmt/marian?

**Comment by emjotde** [comment]
I plan to work on that and it is moving slowly in that direction, but i cannot really offer a time frame at the moment.

**Comment by emjotde** [comment]
Just bumping this up. We have batched translation now, so MRT or a similar variant of reinforcement learning is next on the list. I hope I will be able to work on this in the next few weeks.

**Comment by emjotde** [comment]
Closing. MRT and Reinforcement learning are things I always want to do, but never have time to implement.

**Comment by tomsbergmanis** [comment]
Hi @emjotde! I was wondering if there is any developments in MRT direction?
