### ISSUE TITLE
Renaming AmuNMT to Marian

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#75]
Reacting to #61:

I am in the process of renaming "AmuNMT" to "Marian" and turning the "Marian" repository into "Marian-train". Things may be a bit out of whack for a couple of days until all urls and references have been corrected. Feel free to correct obvious things yourself if you see them. 

The webpage deployment script is currently broken, so there is no update of the marian-nmt.github.io site. I have also registered the amunmt organization again to be able to redirect things here. 

Since repo names now overlap it is probably best to remove the local repositories, clone and compile from scratch to avoid confusion, sorry for that.

**Comment by mjpost** [comment]
+1 on the new name which is great. Why have two repositories, though, instead of just rolling training and decoding into one repo named "marian"? I understand that AmuNMT/marian is much faster than the decoder in (now) marian-train, but there must still be a lot of shared code and an eventual path to merge them?

**Comment by emjotde** [comment]
Hi, 
the `marian` repo contains everything that's currently believed to be more or less stable. It pulls in everything automatically from the `amunmt-stable` (need to change that name too) branch from `marian-train`. So the code is shared. 

`marian-train` master is thought to be more of an experimental repo where things can go sideways sometimes. In the future we will get rid of one of them.

**Comment by tomekd** [comment]
To close?

**Comment by emjotde** [comment]
The mailing list is left.

**Comment by emjotde** [comment]
Also the benchmarks on the website still have amunmt in them. So I keep this open as a reminder for myself.
