### ISSUE TITLE
Implement new regression tests

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#76]
Hi,
my wish list:

1. Test if translations for a given model and input stay the same
1. Test if hard and soft alignment are returned and match a given alignment
1. Test if n-best list format with and without alignments works correctly
1. Test if amun and s2s produce the same output for the same input and model.
1. Test if marian produces the same costs for a given corpus, random seed and number of iterations. 
1. Test if marian produces the same gradients for a given mini-batch and the above conditions.

**Comment by ugermann** [comment]
Can #5 even be accomplished? Isn't there some randomness on GPUs even with the same seed and input, because you can't control the order in which numbers are added up?

**Comment by emjotde** [comment]
@ugermann It's pretty stable actually. You might need some rounding to maybe two or three places behind the comma, but should be feasible.

**Comment by emjotde** [comment]
@ugermann And to clarify, I mean the costs reported by marian on stderr, these are averaged across many batches and rounded. The floating point issues are probably not significant there.

**Comment by emjotde** [comment]
Assigning Tomasz to do 1-3. In Jenkins I suppose?

**Comment by tomekd** [comment]
Yes.

**Comment by emjotde** [comment]
OK, so what's the current status of these things and other test stuff?
Also mentioned in issue #29 and https://github.com/marian-nmt/marian-train/issues/29 and https://github.com/marian-nmt/marian-train/issues/44

**Comment by ugermann** [comment]
Currently, Jenkins runs this with every new commit to the master branch:

```
mkdir -p build
rm -rf build/*
cd build
cmake -DCOMPILE_TESTS=ON -DCOMPILE_EXAMPLES=ON -DUSE_CUDNN=ON ..
make -j
```

If I understand it correctly, -DCOMPILE_TESTS=ON runs the unit tests designed nby @snukky.

**Comment by snukky** [comment]
@emjotde: I've started creating regression tests for marian-train yesterday. I will finish after the weekend.
