### ISSUE TITLE
Averaging models fails | Assertion `fp' failed.

### ISSUE THREAD

**Issue by mehmedes** [marian-nmt/marian#77]
After finishing training, when I train to average the 4 best models into a

 single model ...
```
MODELS=`cat model/valid.log | grep valid-script | sort -rg -k8,8 -t ' ' | cut -f 4 -d ' ' | head -n 4 | xargs -I {} echo model/model.iter{}.npz | xargs`
../../scripts/average.py -m $MODELS -o model/model.avg.npz
```
... I end up with
```
amun: /home/mehmedes/amunmt/src/amun/3rd_party/cnpy/cnpy.cpp:156: cnpy::npz_t cnpy::npz_load(std::__cxx11::string): Assertion `fp' failed.
Aborted (core dumped)
```
I'm on ``` 0f50f93 ``` 
[log.zip](https://github.com/marian-nmt/marian/files/1066324/log.zip)

**Comment by emjotde** [comment]
Does  model/model.avg.npz exists and does it have a reasonable size?

**Comment by mehmedes** [comment]
No. It hasn't been created. I've used the ``` run-me.sh ``` for training.
[run-me.zip](https://github.com/marian-nmt/marian/files/1066333/run-me.zip)

**Comment by emjotde** [comment]
What happens if you paste this into your command line?

```
cat model/valid.log | grep valid-script | sort -rg -k8,8 -t ' ' | cut -f 4 -d ' ' | head -n 4 | xargs -I {} echo model/model.iter{}.npz
```
and this:
```
../../scripts/average.py -m model/model.iter690000.npz model/model.iter680000.npz -o model/model.avg.npz
```

And unrelated: what GPUs are you using? Curious because of the Words/s rate.

**Comment by mehmedes** [comment]
Thank you!!
The second command revealed I was missing numpy.
After installing it, averaging works fine. I'm sorry for bothering with this really no-issue.

Concerning my GPUs. I'm using two 1080s. I suppose I ended up with this training rate because I increased netword vocabularies to 85,000. When I use 65,000/55,000 as suggested in your script I have around 6500 words per second.
Should I worry about my training rate being too low despite two1080s?

**Comment by emjotde** [comment]
Hi,
if you update to recent master, you should get quite a speed improvement.

**Comment by mehmedes** [comment]
Ok. Thank you. I will give it a try!

**Comment by emjotde** [comment]
And probably better BLEU too, There was a bug in amun with layer-normalization that probably hurt about 0.2 BLEU.

**Comment by mehmedes** [comment]
After the update training speed increased > 30 %! Thank you!
