### ISSUE TITLE
Fingerprint/Feature list/version number for models

### ISSUE THREAD

**Issue by hieuhoang** [marian-nmt/marian#79]
I'm getting different outputs using the same model, depending on what executable (amun/gpu, amun/cpu, s2s) and what version of the code I'm using. This is getting out of hand.

We should have some procedure to make sure that a model doesn't run if a feature it needs hasn't been implemented

**Comment by emjotde** [comment]
Models trained with Marian have this information in special:model.yml.npy within the npz file. 

Example:

```
dim-emb: 512                                                                                          
dim-pos: 0                                                                                            
dim-rnn: 1024                                                                                         
dim-vocabs:                                                                                           
  - 50000                                                                                             
  - 50000                                                                                             
layer-normalization: false                                                                            
layers-dec: 1                                                                                         
layers-enc: 1                                                                                         
skip: false                                                                                           
tied-embeddings: false                                                                                
type: s2s
```

**Comment by emjotde** [comment]
On the other hand, for amun models this should not be happening. If you have different resutls for simple amun models, these are bugs not versions.

**Comment by hieuhoang** [comment]
aye, I'm using geovedi's models.

1. why is this in the special, difficult-to-read object in the npz file & not in the config file? It's the same format as the config file.
2. is it being read in by s2s or amun? 
3. What happens if it encounters an unknown param? Does it crash or carry on regardless? It should crash
4. what happens if there is a matrix in the npz file it doesn't know about? That suggest there is extra functionality that s2s/amun doesn't know about - it should crash

**Comment by emjotde** [comment]
1. Distributed in one file and user does not need to know about that, s2s needs to know about that. 
2. Currently in s2s, I consider amun legacy code :)
3. s2s knows all parameters Marian knows, it will throw exceptions for contradictory options, for instance the following will result in exception: `{type: amun, layers-dec: 2}`.
4. s2s does not care. If someone does shenianigans like this it's the persons resposibility not ours.

**Comment by emjotde** [comment]
There was also a bug in amun which I fixed a couple of days ago. it would have affected translation with models that have layer-normalization.

**Comment by emjotde** [comment]
@hieuhoang Did you have something like that in mind, or would you like something more?

**Comment by hieuhoang** [comment]
No. There will always be bugs. 

At the moment, we can't rule out version mismatch, ie the model has a feature that we don't have in amun/s2s. Ideally, they should stop if they encounters an unknown matrix/param. The sheniangans are of our own making

**Comment by emjotde** [comment]
hm. I am unaware of a situation like this. Example?

**Comment by hieuhoang** [comment]
https://github.com/marian-nmt/marian/issues/70

**Comment by tomekd** [comment]
@hieuhoang : #70 was different. @lczarny tried to implement fake tie_embs by model manipulation. And it didn't work.

**Comment by emjotde** [comment]
Exactly. We cannot foresee what people do with models if they mess around with them manually. Also this model was changed in a way that intended to fool amun. So any test would not have worked anyway.

**Comment by hieuhoang** [comment]
you're right, thats a bad example. I'll hold fire until something else comes up

**Comment by emjotde** [comment]
@hieuhoang With the coming refactoring I am going to change the options for using multiple layers. For instance `dec-depth` instead of `layers-dec`. That's a breaking change. How would you handle this?

**Comment by hieuhoang** [comment]
hmm. I would personally try & keep backward compatibility for a while. Does options_ have a set() method? Or if it's just 1 or 2 changes, it might be a idea just to stop and tell people to change their config file.

My worry isn't the args that you can see but the matrices in the npz file you can't see. My preference would be to treat them like args - stop if you don't understand what to do with an unknown object

**Comment by emjotde** [comment]
I think I would prefer a breaking change that early in. Probabely hardly anyone uses the deep models right now. And there will be so much more functionality.

**Comment by emjotde** [comment]
I have done some thinking, and I believe your problem with too many matrices cannot really be solved do to Marian's dynamic nature. You only know what matrices you need when the graph has actually be built. There is no other way to know it. And even worse, you might not need all parameters for all computation graphs of the same model. Imagine a multi-decoder model which has alternating languages for different batches. The model can choose to use different parameters for different expansions. In other words, you can't know what you don't know.

**Comment by hieuhoang** [comment]
I disagree, a union of the models that should explain all the matrices. We can defer this for another time.

The version number added to marian-train is a start

**Comment by emjotde** [comment]
In theory, it's unbounded though.

**Comment by hieuhoang** [comment]
yes, but even matrices in dynamic graphs would follow a naming pattern, eg. obj_layer2, obj_layer3, obj_layer4....

finding an unknown object obj_whatever should make you suspect something is wrong. The next time I stumble 'cos of this, I will add warnings

**Comment by emjotde** [comment]
As I said, you do not know what your naming pattern is unless you execute the graph. Isn't this a variant of the halting problem?

**Comment by hieuhoang** [comment]
no
