### ISSUE TITLE
A more user-friendly high-level API?

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#81]
Hi everyone,
As an example, the current way of building an LSTM cell looks like this:
```
    auto cell = rnn::cell("lstm")(graph,
                                  "dcoder_cell1",
                                  512,
                                  1024,
                                  dropout_prob = 0.2,
                                  normalize = true);
```
I am now thinking of switching to a more factory-based approach. The idea would be to base all object construction internally on YAML descriptions that can be converted to objects and the other way round. Ultimately, the goal would be to describe as much as possible of the S2S architecture in a config file. 
A corresponding YAML file woud maybe look like this:

```
cell:
  type: lstm
  name: decoder_cell1
  dimInput: 512
  dimState: 1024
  dropout: 0.2
  normalize: true
```

One idea for a new interface could be mostly string based:

```
    auto cell = rnn::cell()
                  ("type", "lstm")
                  ("name", "decoder_cell1")
                  ("dimInput", 512)
                  ("dimState", 1024),
                  ("dropout", 0.2)
                  ("normalize", true)
                .create(graph);
```
 
Or maybe with accessors as below. The approach below could be othogonal to the one above, and also allows for sort of grammar checking at compile time. Options that do not exist will cause compile errors.

```
    auto cell = rnn::cell()
                  .type("lstm")
                  .name("decoder_cell1")
                  .dimInput(512)
                  .dimState(1024)
                  .dropout(0.2)
                  .normalize(true)
                .create(graph);
```
If the YAML file is given the following should also work:
```
    auto cell = rnn::cell().parse(yaml).create(graph);
```

Opinons? Better ideas?

**Comment by tomekd** [comment]
I think this issue should be in marian-train repository.

**Comment by emjotde** [comment]
True, but has more visibility here.
