### ISSUE TITLE
Segmentation fault for CPU decoding with --mini-batch > 1

### ISSUE THREAD

**Issue by snukky** [marian-nmt/marian#82]
If you run amun on CPU (e.g. `--d 0 --gpu-threads 0 --cpu-threads 16`) with `--mini-batch` > 1, a segmentation fault will be caused. See the example from `examples/translate`. Setting `--mini-batch 1` solves the problem. We can provide a more user-friendly error message.

**Comment by hieuhoang** [comment]
Agree. We can force mini-batch=1 for CPU, or print out an error message

**Comment by tomekd** [comment]
I think we should ignore mini-batch/maxi-batch in CPU mode.

**Comment by emjotde** [comment]
We should implement mini-batch in CPU mode!

**Comment by kpu** [comment]
Yes, especially since Xeon Phi is a CPU and NERSC has invited applications that would use 2000 Xeon Phis at once.  Like translating the web.

**Comment by tomekd** [comment]
@snukky : I fix tht bug. Please test it and if it works for you, close this issue.

**Comment by snukky** [comment]
It works.

**Comment by emjotde** [comment]
It's more a workaround than a fix. After all it does not have batched decoding in CPU mode.
