### ISSUE TITLE
feature request: replace UNK with phrase table

### ISSUE THREAD

**Issue by geovedi** [marian-nmt/marian#90]
currently i'm doing it as post-processor in a python wrapper using alignment as the guide. would be great if this feature can be added.

**Comment by emjotde** [comment]
Noted. Might take a while though. In the meantime the guided-alignment option might be of interest. You can feed precalculated word alignments into the training process an the resulting attention should become more similar to actual alignments.

**Comment by geovedi** [comment]
yes, i've using `guided-alignment` for a while now. 😉

**Comment by emjotde** [comment]
Oh, cool. Have you noticed improvements in that regard?

**Comment by geovedi** [comment]
looks like it's fast to converge. i'm only testing with symmetrical alignment (`grow-diag-final-and`) produced by `fast_align` and `atools`. haven't try the forward or reverse ones.

**Comment by emjotde** [comment]
that's fine. I wouldn't even look at the others.

**Comment by emjotde** [comment]
@phikoehn You do not happen to have anything lying around that goes into that direction?

**Comment by lkfo415579** [comment]
@geovedi  would you tell us how to use **guided-alignment** correctly in detail?
