### ISSUE TITLE
Remove warnings for optional matrixes

### ISSUE THREAD

**Issue by emjotde** [marian-nmt/marian#97]
`Optional matrix not found, continuing: encoder_r_gamma2`

These warnings still look scary and do not really bring anything to the table, also they are about the non-standard case, why should they even appear?

Maybe set the to a lower level in the logger and only display them when someone sets the requiered log-level?

**Comment by hieuhoang** [comment]
they're useful to me but change it to however you want

**Comment by emjotde** [comment]
Ugh, do not want to have to dab into that old code.

**Comment by tomekd** [comment]
OK. I will turn it off.

**Comment by emjotde** [comment]
Any progress?
